---
permalink: try/task_use_demonode.html 
sidebar: sidebar 
keywords: element demo node, virtual machine, element software, element api, vmware deployment 
summary: Element デモノードは、 VMware 仮想マシン版の Element ソフトウェアで、 NetApp HCI 製品と SolidFire 製品の主要なストレージ機能の多くを簡単にデモできます。 
---
= Element のデモノードを使用してストレージ機能を試します
:icons: font
:imagesdir: ../media/


[role="lead"]
Element デモノードは、 VMware の Virtual Machine （ VM ；仮想マシン）バージョンの Element ソフトウェアで、 NetApp HCI 製品と SolidFire 製品の主要なストレージ機能の多くを簡単にデモできます。開発者は、デモノードを使用することで、物理ハードウェアを必要とせずに Element API に対してコードを実行できます。VMware の導入を容易にする OVA ファイルとしてパッケージ化されています。



== サポートされる機能：

Element デモノードは、デモおよび開発用のツールとしてのみ使用します。デモノードを使用する前に、次の機能上の制限事項に注意してください。

* Element デモノードはクラスタリングをサポートしていません。シングルノードクラスタとしてのみ機能します。
* Element のアップグレードはサポートされていません。Element の新しいバージョンのデモを行うには、新しいデモノード VM をインストールする必要があります。
* ストレージのパフォーマンスを示すことはその目的ではありません。デモノードで観察されたパフォーマンスからは、物理クラスタのパフォーマンスはわかりません。
* NetApp HCI クラスタまたは SolidFire クラスタにデモノードを追加することはできません。
* VRF VLAN はサポートされていません（標準のタグ付き VLAN がサポートされます）。
* マルチドライブスライスサービス（ MDSS ）はサポートされません。
* Element デモノードは、 VMFS データストアでのみサポートされます。VVOL はサポートされません。
* ハードウェアベースの構成と監視機能はデモノードでは動作しません。
* ボリュームあたり最大 10 個の Snapshot をサポートします。
* ノード / クラスタあたり最大 20 個のアカウントをサポートします。
* サポートされるアカウントあたりのボリューム数は最大 100 個です。
* サポートされる VVOL の数はアカウントあたり最大 200 個です。
* 最大ボリュームサイズが 100GiB に対応しています。



NOTE: Element ソフトウェアに関するその他の制限事項がすべて適用されます。詳細については、最新の Element ソフトウェアリリースノートを参照してください。



== VM の要件

* 240 GB の合計容量（ VM の仮想ディスクのサイズと数は変更できません。ハイパーバイザーで提供された追加のストレージはゲスト OS で無視されます）。
* 60 GB のルートディスク
* シックプロビジョニング / eager-zeroed-thick （ 30 GB のメタデータドライブ 1 本または 50 GB のブロックドライブ 3 本）またはシンプロビジョニング / eager-zeroed-thick （ * 推奨）（ 30 GB のメタデータドライブ 1 本、または 50 GB のブロックドライブ 3 本）
* vCPU × 2 （フル予約）
* 16GB の RAM （完全にリザーブ）
* シングル HBA ：すべてのディスク、 LSI Logic パラレル
* 2 つの vNIC 、両方の vmxnet3 （ 1 つの管理、 1 つのストレージ）




== ホストの要件

* Element デモノード 11.7 VM の ESXi 6.0 または 6.5
* Element デモノード 12.0 および 12.2 の VM の ESXi 6.5
* Element デモノード 12.3 VM 用 ESXi 6.7 および 7.0
* マルチコア 64 ビットインテル ® アーキテクチャー




== Element のデモノードをダウンロード

Element のデモノードソフトウェアは、 .ova ファイルにパッケージ化された VMware ファイルのセットです。



== VMware ESXi に Element デモノードをインストールします

VMware ESXi に Element デモノードをインストールするには、次のタスクを実行します。

* <<Configure network interfaces>>
* <<Register the demo node on an ESXi server>>
* <<Start the demo node on an ESXi server>>




=== ネットワークインターフェイスを設定

Element デモノードには、 2 つの仮想マシンネットワークが必要です。1 つはストレージトラフィック用で、もう 1 つは管理トラフィック用です。ジャンボフレームをサポートするようにストレージネットワークを設定する必要があります。



=== ESXi サーバでデモノードを登録します

ESXi サーバに Element のデモノードを登録するには、 vSphere Client を使用して demo ノードの .ova ファイルを導入する必要があります。

.手順
. vSphere Client にログインし、インベントリパネルから ESXi ホストを選択します。
. [ * ファイル * （ File ） ] > [* OVF テンプレートの展開（ Deploy OVF Template ） ] を選択
+
OVF テンプレートの展開ウィザードが起動します。

. Select template * ページで、ダウンロードした OVA ファイルを参照し、 * Open * を選択します。
. 「 * 次へ * 」を選択します。
. [ 名前と場所 *] ページで、展開したテンプレートの名前と場所を指定し、 [ 次へ *] を選択します。
. [ リソースの選択 *] ページで、テンプレートを実行する場所を参照し、 [ 次へ *] を選択します。
. 詳細を確認して、「 * 次へ * 」を選択します。
. [ ストレージの選択 ] ページで、仮想マシンファイルを保存する場所を選択し、 [ 次へ * ] を選択します。
. [ ネットワークの選択 * ] ページで、 OVA ファイルで使用されるネットワークをインベントリ内の 2 つの個別の仮想マシンネットワークにマップし、 [ 次へ * ] を選択します。
. [* Ready to Complete] （完了する準備ができました）ページで、作成する仮想マシンの詳細を確認し、 [* Finish （完了） ] を選択します。



NOTE: デモノードの導入が完了するまでに数分かかることがあります。



=== ESXi サーバでデモノードを起動します

VMware ESXi コンソールから Element にアクセスするには、デモノード VM を起動する必要があります。

.手順
. vSphere Client で、作成したデモノード VM を選択します。
. [Summary] * タブを選択して、この VM の詳細を表示します。
. VM を起動するには、 * 電源オン * を選択します。
. 「 Web コンソールの起動」を選択します。
. TUI を使用して、デモノードを設定します。詳細については、を参照してください link:../setup/concept_setup_configure_a_storage_node.html["ストレージノードを設定"^]。




== サポートの利用方法

Element デモノードは、ベストエフォート型のボランティアベースで利用できます。サポートについては、に質問を投稿してください https://community.netapp.com/t5/Simulator-Discussions/bd-p/simulator-discussions["Element のデモノードフォーラム"^]。



== 詳細については、こちらをご覧ください

* https://www.netapp.com/data-storage/solidfire/documentation/["SolidFire オールフラッシュストレージのリソースページ"^]

