---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: 導入後は、すべてのネットアップストレージコンポーネントをアップグレードすることで、 SolidFire Element ストレージシステムを最新の状態に保つことができます。 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= アップグレード手順の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
導入後も SolidFire Element ストレージシステムを最新の状態に保つには、すべてのネットアップストレージコンポーネントを順番にアップグレードします。

これらのコンポーネントには、管理サービス、NetApp Hybrid Cloud Control、Elementソフトウェア、管理ノード、および（インストール環境に応じて）Element Plug-in for vCenter Serverが含まれます。

[NOTE]
====
* 2023年11月以降、署名キー証明書（プライベートおよびパブリック）の有効期限が2023年11月5日に切れたため、NetAppハイブリッドクラウドコントロールまたはREST APIを使用してコンポーネントのアップグレードを開始することはできません。NetAppハイブリッドクラウドコントロールまたはREST APIを使用して管理サービス、Elementソフトウェア、およびストレージファームウェアをアップグレードする前に、この問題をバージョン12.8で回避することができますlink:task_hcc_upgrade_management_node.html["管理ノードのインプレースアップグレードの実行"]。
+
バージョン12.8の新しい管理ノードを導入する場合は、NetApp Hybrid Cloud ControlまたはREST APIを使用して、に記載されている順序でコンポーネントのアップグレードを実行できます<<sys_upgrade,システムのアップグレード順序>>。

* 次のノードはサポートされていません。次のいずれかのノードをサポート対象外のElementバージョンにアップグレードしようとすると、Element 12.xでサポートされていないことを示すエラーが表示されます。
+
** Element 12.8、SF4805、SF9605、SF19210、およびSF38410ストレージノード以降。
** Element 12.7以降、SF2405およびSF9608ストレージノード、FC0025およびSF-FCN-01 FCノード。


* Element 12.5以降では、ElementソフトウェアのアップグレードでNetApp HealthToolsがサポートされなくなりました。Element 11.0または11.1を実行している場合は、最初にが必要です https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["HealthToolsを使用してElement 12.3にアップグレードします"^] NetApp Hybrid Cloud Controlを使用してElement 12.5以降にアップグレードします。


====
。 <<sys_upgrade,システムのアップグレード順序>> コンテンツでは、 SolidFire オールフラッシュストレージシステムのアップグレードを完了するために必要な作業について説明します。これらの手順は、単独ででではなく、大きなアップグレード手順の一部として実行することを推奨します。コンポーネントベースのアップグレードまたは更新が必要な場合は、手順の前提条件を参照して、さらに複雑な作業が対処されるようにしてください。

。 link:task_sf_upgrade_all_vsphere.html["vSphere のアップグレード順序"] Element Plug-in for vCenter Server のコンテンツでは、 Element Plug-in for vCenter Server を再インストールするために必要な、アップグレード前とアップグレード後の追加の手順について説明します。

.作業を開始する前に
* 管理ノード 11.3 以降が実行されていることを確認します。新しいバージョンの管理ノードには、個々のサービスを提供するモジュラアーキテクチャが採用されています。
+

TIP: バージョンを確認するには、管理ノードにログインし、ログインバナーに表示される Element のバージョン番号を確認します。11.3 を使用していない場合は、を参照してください link:task_hcc_upgrade_management_node.html["管理ノードをアップグレードします"]。

* 管理サービスをバージョン 2.1.326 以上にアップグレードしておきます。
+
NetApp Hybrid Cloud Control を使用したアップグレードは、それよりも前のバージョンのサービスバンドルでは利用できません。

* すべてのノードのシステム時間が同期され、 NTP がストレージクラスタとノードに対して正しく設定されていることを確認しておきます。各ノードには、ノード Web UI （「 https://[IP address 」： 442 ）に DNS ネームサーバを設定する必要があります。時刻のずれに関連する未解決のクラスタ障害はありません。
* に十分な時間を設定しておきます link:task_hcc_upgrade_element_software.html#element-upgrade-time["Element ソフトウェア"] および link:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["ストレージファームウェア"] アップグレード：Elementソフトウェア12.5以降にアップグレードする場合は、Elementソフトウェアのバージョンとファームウェアの更新によってアップグレードプロセスの時間が異なります。




== [[sys_upgrade]システムのアップグレード順序

Element 12.5以降では、次の順序でNetApp SolidFire オールフラッシュストレージシステムをアップグレードできます。

.手順
. link:task_hcc_upgrade_element_prechecks.html["ストレージをアップグレードする前に、Element ストレージのヘルスチェックを実行します。"] 。
. link:task_hcc_upgrade_management_node.html["（オプション）管理ノードをアップグレードします"]。
+

NOTE: ストレージクラスタ上の Element ソフトウェアをアップグレードするために、管理ノードのオペレーティングシステムをアップグレードする必要がなくなりました。管理ノードのバージョンが 11.3 以降である場合は、 NetApp Hybrid Cloud Control を使用して管理サービスを最新バージョンにアップグレードするだけで Element をアップグレードできます。管理ノードのオペレーティングシステムをアップグレードする理由がほかにもある場合は、セキュリティの修正など、管理ノードのアップグレード手順に従ってください。

. link:task_hcc_update_management_services.html["Hybrid Cloud Control から管理サービスを更新します"]。
+
[IMPORTANT]
====
** 管理サービス 2.27 バンドルには、管理ノード 12.8 とのみ互換性のある vCenter Server 5.5 用の Element プラグインが含まれています。管理サービス 2.27 に更新する場合は、管理ノードと管理サービス間の互換性を確保するために、アップグレード シーケンスを変更し、Element 12.8 にアップグレードした後に管理サービス バンドルを更新する必要があります。
** 管理サービス 2.21.61 から 2.26.40 に更新する場合は、Element 12.8 にアップグレードする前に、管理サービス バンドルを更新する必要があります。


====
+

IMPORTANT: 管理サービスをバージョン 2.16 以降に更新していて、管理ノード 11.3 ～ 11.8 を実行している場合は、管理サービスを更新する前に、管理ノード VM の RAM を増やす必要があります。

. link:task_hcc_upgrade_element_software.html["Element ソフトウェアとストレージファームウェアをアップグレードします"]。
. link:task_hcc_upgrade_storage_firmware.html["（オプション） Element ストレージファームウェアのみをアップグレードします"]。
+

NOTE: このタスクは、メジャーリリース以外で新しいストレージファームウェアアップグレードがリリースされたときに実行することができます。

. link:task_vcp_upgrade_plugin.html["Element Plug-in for vCenter Server をアップグレードします"]。


[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]

