---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_activeIQ.html 
summary: 管理ノード（ mNode ）を使用して、 SolidFire オールフラッシュストレージで Active IQ を有効にすることができます。 
keywords: netapp, Element, api, enable, active iq, activeiq 
---
= Active IQ とネットアップによる監視を有効にします


[role="lead"]
インストールまたはアップグレード時に Active IQ ストレージの監視を有効にしていない場合、有効にすることができます。SolidFire オールフラッシュストレージシステムのインストール時に SolidFire Active IQ をセットアップしなかった場合は、この手順の使用が必要になることがあります。

Active IQ コレクタサービスは、履歴データのレポートおよびほぼリアルタイムのパフォーマンス監視用に、設定データと Element ソフトウェアベースのクラスタパフォーマンス指標を SolidFire Active IQ に転送します。ネットアップ監視サービスを使用すると、ストレージクラスタのエラーを vCenter に転送してアラート通知を送信できます。

.作業を開始する前に
* ストレージクラスタで NetApp Element ソフトウェア 11.3 以降が実行されている必要があります。
* バージョン 11.3 以降を実行する管理ノードを導入しておきます。
* インターネットにアクセスできる。外部接続のないダークサイトからは、 Active IQ コレクタサービスを使用できません。


.手順
. インストールのベースアセット ID を取得します。
+
.. 管理ノードでインベントリサービス REST API UI を開きます。
+
[listing]
----
https://[management node IP]/inventory/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアント ID を「 m node-client 」として入力します。
... セッションを開始するには、 * Authorize * を選択します。
... ウィンドウを閉じます。


.. REST API UI で、 * 一部のユーザに一時的な処理を開始 / インストール * を選択します。
.. [* 試してみてください * ] を選択します。
.. [* Execute] を選択します。
.. コード 200 の応答本文から ' インストールの ID をコピーします
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: インストール環境には、インストールまたはアップグレード時に作成されたベースアセットの構成が含まれています。



. テレメータの有効化：
+
.. 管理ノードの mNode サービス API UI にアクセスします。管理ノードの IP アドレスに「 /mnode 」を続けて入力します。
+
[listing]
----
https://[management node IP]/mnode
----
.. 「 * Authorize * （認証）」または任意のロックアイコンを選択し、次の手順を実行します。
+
... クラスタのユーザ名とパスワードを入力します。
... クライアント ID を「 m node-client 」として入力します。
... セッションを開始するには、 * Authorize * を選択します。
... ウィンドウを閉じます。


.. ベースアセットを設定します。
+
... PUT /assets/｛ asset_id ｝ * を選択します。
... [* 試してみてください * ] を選択します。
... JSON ペイロードに次のコマンドを入力します。
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... 前の手順のベース ID を * asset_ID * に入力します。
... [* Execute] を選択します。
+
Active IQ サービスは、アセットが変更されるたびに自動的に再起動されます。アセットを変更すると、設定が適用されるまで短時間の遅延が発生します。





. NetApp Hybrid Cloud Control の vCenter コントローラアセットをまだ追加していない場合は、管理ノードの既知のアセットに追加します。
+

NOTE: ネットアップ監視サービスにはコントローラアセットが必要です。

+
.. コントローラサブアセットを追加する場合は、「 * POST /assets/｛ asset_id ｝ /controllers * 」を選択します。
.. [* 試してみてください * ] を選択します。
.. クリップボードにコピーした親ベースアセットの ID を * asset_id * フィールドに入力します。
.. 必要なペイロード値を「 type 」に「 vcenter 」、 vCenter クレデンシャルを指定して入力します。
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: 「 ip 」は vCenter の IP アドレスです。

.. [* Execute] を選択します。




[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]

