---
permalink: concepts/concept_solidfire_concepts_nodes.html 
sidebar: sidebar 
keywords: what is, node, management node, storage node, fibre channel, state, pending, active 
summary: ノードは、クラスタにグループ化され、ブロックストレージまたはコンピューティングリソースとしてアクセスされるハードウェアです。 
---
= ノード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードは、ブロックストレージとコンピューティング機能を提供するためにクラスタにグループ化されたハードウェアリソースまたは仮想リソースです。

NetApp Element ソフトウェアでは、クラスタのさまざまなノードロールを定義します。ノードロールのタイプは次のとおりです。

* <<管理ノード>>
* <<ストレージノード>>
* <<Fibre Channel ノード>>


<<ノードの処理の状態,ノードの状態>> クラスタの関連付けによって異なります。



== 管理ノード

管理ノードは、アップグレード後にシステムサービスを提供するために使用される仮想マシンです。監視と計測のほか、クラスタのアセットと設定の管理、システムテストとユーティリティの実行、トラブルシューティングのためのネットアップサポートアクセスの有効化などを行います。link:../concepts/concept_intro_management_node.html["詳細はこちら。"]



== ストレージノード

SolidFire ストレージノードは、 Bond10G ネットワークインターフェイスを通じて相互に通信する一連のドライブを搭載したサーバです。ノード内のドライブには、データの格納用と管理用にブロックスペースとメタデータスペースが確保されます。各ノードには、 NetApp Element ソフトウェアの工場出荷時のイメージが含まれています。

ストレージノードには次のような特徴があります。

* 各ノードには一意の名前が付けられます。管理者が名前を指定しない場合、ノードにはデフォルトで「 SF-XXXX 」という名前が付けられます。 XXXX は、システムによってランダムに生成される任意の 4 文字です。
* 各ノードに高性能な専用の Non-Volatile Random Access Memory （ NVRAM ；不揮発性 RAM ）書き込みキャッシュが搭載されており、システム全体のパフォーマンスの向上と書き込みレイテンシの低減が実現します。
* 各ノードはストレージと管理の 2 つのネットワークに接続され、それぞれに 2 つの独立したリンクを使用して冗長性とパフォーマンスを確保します。各ノードには各ネットワークの IP アドレスが必要です。
* 新しいストレージノードで構成されるクラスタを作成したり、既存のクラスタにストレージノードを追加してストレージの容量とパフォーマンスを拡張したりできます。
* クラスタに対するノードの追加や削除は、サービスを中断することなくいつでも実行できます。




== Fibre Channel ノード

SolidFire Fibre Channel ノードは Fibre Channel スイッチへの接続を提供し、 Fibre Channel スイッチは Fibre Channel クライアントに接続できます。Fibre Channel ノードは、 Fibre Channel プロトコルと iSCSI プロトコル間のプロトコルコンバータとして機能するため、新規または既存の任意の SolidFire クラスタへの Fibre Channel 接続を追加できます。

Fibre Channel ノードには次の特徴があります。

* Fibre Channel スイッチがファブリックの状態を管理し、相互接続が最適化されます。
* 2 つのポート間のトラフィックはスイッチ経由でのみ送信され、他のポートには送信されません。
* ポートの障害は分離され、他のポートの動作には影響しません。
* 1 つのファブリック内で複数のポートペアが同時に通信することができます。




== ノードの処理の状態

設定のレベルによって、ノードは次のいずれかの状態になります。

* * 利用可能 *
+
ノードにはクラスタ名が関連付けられておらず、まだクラスタに含まれていません。

* * 保留中 *
+
ノードが設定され、指定したクラスタに追加できるようになります。

+
このノードにアクセスするための認証は必要ありません。

* * 保留中アクティブ *
+
互換性のある Element ソフトウェアをノードにインストールしています。完了すると、ノードは Active 状態に移行します。

* * アクティブ *
+
クラスタに参加しているノード。

+
このノードを変更するには、認証が必要です。



上記の各状態では、一部のフィールドは読み取り専用です。



== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

