---
permalink: concepts/concept_rn_whats_new_element.html 
sidebar: sidebar 
keywords: netapp, solidfire, element, storage, solidfire enterprise sds 
summary: ネットアップでは、 SolidFire および Element ソフトウェアを定期的に更新して、新機能、拡張機能、およびバグの修正を提供しています。 
---
= Elementソフトウェアの新機能
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットアップでは、 SolidFire および Element ソフトウェアを定期的に更新して、新機能、拡張機能、およびバグの修正を提供しています。Element 12.8は最新リリースで、セキュリティおよびシステムコンポーネントのアップデート、運用の改善、および解決済みの問題が含まれています。


NOTE: ソフトウェアとファームウェアの累積更新は、ストレージクラスタで実行されているElementの現在のバージョンに基づいて、Element 12.8のアップグレードの一環としてインストールされます。たとえば、クラスタでElement 12.5を実行している場合は、Element 12.8に直接アップグレードして、Element 12.7と12.8の両方から累積的な更新を取得できます。サポートされているアップグレードパスについては、ナレッジベースの記事を参照して https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software["NetApp Elementソフトウェアを実行するストレージクラスタのアップグレードマトリックス"^]ください。



== 要素12.8

Element 12.8の新機能の詳細については、こちらをご覧ください。



=== ボリュームのロードバランシング

Element 12.8では、ボリュームロードバランシング機能が導入されています。この機能を使用すると、QoSポリシーに設定されている最小IOPSではなく、各ボリュームの実際のIOPSレベルに基づいてノード間でボリュームを分散できます。ボリュームの負荷分散機能は、ボリュームの負荷分散にのみ使用できます。仮想ボリュームのバランス調整には使用できません。ボリュームロードバランシング機能は、デフォルトでは無効になっています。この機能を有効または無効にするには、APIパラメータでlink:../api/reference_element_api_enablefeature.html["EnableFeature"]およびlink:../api/reference_element_api_disablefeature.html["無効な機能"]APIメソッドを使用するか、link:../storage/task_system_manage_cluster_volume_load_balancing.html["ボリュームのロードバランシング"]Element UIのオプションを使用し `VolumeLoadBalanceOnActualIOPS`ます。



=== ノードの利用率情報の表示

Element 12.8では、および `ListNodeStats`APIメソッドを使用し `GetNodeStats`て、ノードの利用率情報を表示できます `nodeHeat`。 `nodeHeat`オブジェクトはオブジェクトのメンバー `nodeStats`であり、一定期間の設定されたIOPSに対するプライマリの合計IOPSまたは合計IOPSの比率に基づいてノード利用率の情報が表示されます。

また、Element UIのノードの[View Details]画面で、ノード利用率をの割合として表示することもできます `recentPrimaryTotalHeat`。



=== ボリュームのI/O統計の表示

Element 12.8では、および `ListVolumeStatsByVolume`APIメソッドを使用して、 `GetVolumeStats`ボリュームのI/O使用率の統計を表示できます `sliceIopsStats`。I/O統計は、ボリュームの読み取りIOPSと書き込みIOPSの情報を使用して計算され、過去24時間と過去1時間の2つの期間にわたって測定されます。link:../api/reference_element_api_volumestats.html#object-members["詳細はこちら。"]です。



=== iSCSIセッションのCHAPアルゴリズム

ホストiSCSIイニシエータは、Element iSCSIターゲットとのiSCSIセッションを作成するときに使用するChallenge-Handshake Authentication Protocol（CHAP；チャレンジハンドシェイク認証プロトコル）アルゴリズムのリストを要求します。Element 12.8以降では、Element iSCSIターゲットがiSCSIセッションに使用するように選択した、サポートされるCHAPアルゴリズムを表示できます。



=== VMハードウェアバージョンのアップグレード

既存の管理ノードをElement 12.8にインプレースアップグレードする場合は、アップグレード前に、管理ノードのVMハードウェアのバージョンがESXi 6.7（VMハードウェアバージョン14）以降に対応していることを確認する必要があります。link:../upgrade/task_hcc_upgrade_management_node.html#step-1-upgrade-vm-hardware-version-on-a-management-node["詳細はこちら。"]です。



== 要素12.7

Element 12.7の新機能の詳細については、こちらをご覧ください。



=== セキュアCHAPアルゴリズム

Element 12.7には、セキュアなFIPS準拠のChallenge-Handshake Authentication Protocol（CHAP）アルゴリズムSHA1、SHA-256、SHA-256がサポートされています。 link:../storage/task_data_manage_accounts_work_with_accounts_task.html["詳細はこちら。"]。



=== ダイナミックブロック（BIN）の同期レート

ノードの追加、アップグレード、メンテナンスなどのクラスタ処理やドライブの追加などのクラスタ処理では、ブロック（bin）の同期がトリガーされ、クラスタレイアウトの新しいノードまたは更新されたノードにブロックデータが分散されます。デフォルトの同期速度として1つの低速を使用すると、これらの処理に長い時間がかかり、大規模なノードの処理能力は活用されません。Element 12.7以降、ストレージノード上のコア数に基づいて動的に同期速度が調整されるため、これらの処理を大幅に高速化できます。

たとえば、Element 12.7を実行する大規模な28コアストレージノード（H610S、SF19210、およびSF38410）を既存のクラスタに追加すると、データの同期速度は60MBpsではなく110MBpsに自動的に調整されます。また、NetApp Hybrid Cloud Controlを使用したElement 12.3.x以降からElement 12.7へのアップグレード時などに、これらの大規模なストレージノードをノードメンテナンスモードから解除すると、変更されたブロックデータ速度の同期レートが20MBpsではなく110MBpsに自動的に調整されます。

中規模な16コアストレージノード（H410S）と小規模な12コアストレージノード（SF4805）をElement 12.7クラスタに追加した場合、データの同期速度は60MBpsのままになります。 ただし、Element 12.3.xからElement 12.7へのアップグレード時に変更されたブロックをノードメンテナンスモードから解除すると、同期レートは、メディアストレージノードでは20Mbpsから60Mbpsに、小規模ストレージノードでは40Mbpsに自動的に調整されます。

ストレージノードを削除しても、ブロックの同期速度には影響しないため、クライアントのI/Oへのパフォーマンスの影響はありません



=== ガベージコレクションの改善

ストレージノードが大規模なクラスタの場合：1PBの使用済みスペースがあるH610S-4では、上書きされて非常に高いワークロードが実行されています。 また、重複排除機能と圧縮機能が高いため、大容量ノードのデフォルトのブルームフィルタサイズが700GB以上から1048576ビットに拡大されているため、ガベージコレクション操作を維持できるようになりました。この変更は、ストレージノードをElement 12.7にアップグレードすると自動的に有効になり、小規模なノードには影響しません。



=== スケールの改善

Element 12.7では、既存のクラスタに複数のストレージノードのブロックドライブとメタデータドライブを追加する際に、特定の順序を指定する必要がなくなりました。Element UIまたはAPIを使用すると、使用可能なすべてのドライブを選択し、同時に一括で追加することができます。Element 12.7は、すべてのブロックサービスが同時に同期されるように、データ同期を自動的に管理します。各ノードのブロックサービスが同期を完了すると、そのノード上のメタデータドライブがボリュームをホストできるようになります。この拡張性の向上により、読み取り応答のレイテンシが大幅に低減され、新しく追加したストレージノード間でデータを同期する際のパフォーマンスの低下を防ぐことができます。



=== ストレージノードのファームウェアの更新

Element 12.7には、ストレージファームウェアバンドルバージョン2.164.0が含まれています。このバンドルには、新しいシステムコンポーネントのサポートが含まれています。 link:https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.164.0.html["詳細はこちら。"]。


NOTE: Element 12.7リリースでは、新しいファームウェアアップデートはありません。ただし、ストレージノードで実行されている現在のファームウェアバンドルに基づいて、Element 12.7にアップグレードすると累積的な更新がインストールされます。



=== SolidFire Active IQ のドキュメント

SolidFire Active IQ UIでQoS管理ページに移動して、クラスタに関する推奨事項とノードスロットル情報を確認できるようになりました。また、クラスタダッシュボードに合計Snapshot数が表示されるようになりました。最近の改善点としては、アクティブボリュームのプライマリノードとセカンダリノードの情報の追加、ノードのプライマリボリュームでの平均スループット、IOPS、平均レイテンシなどがあります。

これで、ElementソフトウェアのドキュメントからSolidFire Active IQ のドキュメントにアクセスできるようになりました。 link:https://docs.netapp.com/us-en/element-software/monitor-storage-active-iq.html["詳細はこちら。"]。



=== NetApp Bugs Onlineには、解決済みの問題と既知の問題があります

解決済みの問題と既知の問題の一覧については、NetApp Bugs Onlineツールを参照してください。これらの問題は、Elementソフトウェアおよびその他の製品で参照できます https://mysupport.netapp.com/site/products/all/details/element-software/bugsonline-tab["NetApp Bugs Online では"^]。



== Element 12.5

Element 12.5の新機能の詳細については、こちらをご覧ください。



=== ストレージノードへのアクセスの向上

Element 12.5では、署名付きSSH証明書を使用して、個々のノードへのリモートアクセスが向上していますストレージノードへのセキュアなリモートアクセスを提供するために、ストレージノードのRTFI実行時に「sfreadonly」という新しい権限制限付きローカルユーザアカウントが作成されるようになりました。sfreadonlyアカウントを使用すると'基本的な保守やトラブルシューティングの目的で'ストレージ・ノードのバックエンドにアクセスできますクラスタ管理者ユーザの「supportAdmin」アクセスタイプを設定し、ネットアップサポートが必要に応じてクラスタにアクセスできるようになりました。



=== 強化されたカスタム保護ドメインの管理性

Element 12.5には、既存のカスタム保護ドメインをすばやく簡単に表示したり、新しいカスタム保護ドメインを設定したりできる新しいユーザインターフェイスが用意されています。



=== クラスタの新しい障害、イベント、アラートが追加されました

Element 12.5では、新しいクラスタ障害コード「BmcSelfTestFailed」および「CpuThermalEventThreshold」が導入され、システムのトラブルシューティングが強化されています。Element 12.5では、「nodeOffline」、「volumeOffline」、「driveHealthFault」、「networkEvent」など、既存のクラスタイベントおよびアラートの堅牢性も向上しています。 と「cSumEvent」です。



=== クラスタ作成UIから保存データのソフトウェア暗号化を有効にします

Element 12.5では、クラスタ作成UIの新しいチェックボックスが追加され、クラスタ作成時にSolidFire オールフラッシュストレージクラスタの保存データの暗号化をクラスタ全体で有効にすることができます。



=== ストレージノードのファームウェアの更新

Element 12.5には、ストレージノードのファームウェアの更新が含まれています。 link:../concepts/concept_rn_relatedrn_element.html#storage-firmware["詳細はこちら。"]。



=== セキュリティの強化

Element 12.5には、Apache log4jの脆弱性に対するElementソフトウェアの影響を緩和する機能が含まれています。仮想ボリューム（VVol）機能が有効になっているNetApp SolidFire ストレージクラスタは、Apache log4jの脆弱性の影響を受けやすくなっています。NetApp Element ソフトウェアのApache log4jの脆弱性に対する回避策 の詳細については、｛url-peak｝[KB Article ^]を参照してください。

Element 11.x、12.0、または12.2を実行している場合、またはvVol機能が有効になっているストレージクラスタがすでにElement 12.3または12.3.1にある場合は、12.5にアップグレードする必要があります。

Element 12.5には、120を超えるCVEセキュリティ脆弱性の修正も含まれています。



== 詳細については、こちらをご覧ください

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["『 NetApp Hybrid Cloud Control and Management Services Release Notes 』を参照してください"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* http://docs.netapp.com/sfe-122/index.jsp["以前のバージョン用の SolidFire および Element ソフトウェアドキュメントセンター"^]
* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI のドキュメント"^]
* link:../hardware/fw_storage_nodes.html["SolidFire ストレージノードでサポートされるストレージファームウェアのバージョン"]

