---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: クラスタは、 SolidFire ストレージシステムの中心であり、複数のノードで構成されます。SolidFire のストレージ効率化を実現するには、クラスタに少なくとも 4 つのノードが必要です。クラスタはネットワーク上では 1 つの論理グループとして認識され、ブロックストレージとしてアクセスできます。 
---
= クラスタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタは、 SolidFire ストレージシステムの中心であり、複数のノードで構成されます。SolidFire のストレージ効率化を実現するには、クラスタに少なくとも 4 つのノードが必要です。クラスタはネットワーク上では 1 つの論理グループとして認識され、ブロックストレージとしてアクセスできます。

新しいクラスタを作成すると、 1 つのノードがそのクラスタの通信の所有者として初期化され、クラスタ内の各ノードに対してネットワーク通信が確立されます。このプロセスは、新しいクラスタごとに 1 回だけ実行します。Element UI または API を使用してクラスタを作成できます。

クラスタをスケールアウトするには、ノードを追加します。新しいノードを追加するときにサービスが中断されることはなく、追加したノードのパフォーマンスと容量がクラスタで自動的に使用されます。

管理者とホストは、仮想 IP アドレスを使用してクラスタにアクセスできます。クラスタ内のいずれのノードも仮想 IP アドレスをホストできます。管理仮想 IP （ MVIP ）は 1GbE 接続でのクラスタ管理を提供し、ストレージ仮想 IP （ SVIP ）はホストからストレージへの 10GbE 接続でのアクセスを提供します。これらの仮想 IP アドレスは、 SolidFire クラスタのサイズや構成に関係なく、一貫した接続を可能にします。仮想 IP アドレスをホストするノードで障害が発生した場合、クラスタ内の別のノードが仮想 IP アドレスを引き継ぎます。


NOTE: Element バージョン 11.0 以降では、ノードの管理ネットワークに IPv4 、 IPv6 、または両方のアドレスを設定できます。この環境は、ストレージノードと管理ノードの両方に対応します。ただし、 IPv6 をサポートしない管理ノード 11.3 以降がこれに該当します。クラスタの作成時には、 IPv4 または IPv6 のどちらかのアドレスを 1 つだけ MVIP に使用でき、これと同じアドレスタイプをすべてのノードで設定する必要があります。

.クラスタに関する詳細情報
*  storage clusters
*  of thirds
*  capacity
*  efficiency
*  cluster quorum




== 信頼できるストレージクラスタです

信頼できるストレージクラスタとは、 NetApp Hybrid Cloud Control でユーザの認証に使用するストレージクラスタです。

管理ノードにストレージクラスタが 1 つしかない場合は、信頼できるクラスタになります。管理ノードに複数のストレージクラスタがある場合は、それらのクラスタのいずれかが権限のあるクラスタとして割り当てられ、そのクラスタのユーザのみが NetApp Hybrid Cloud Control にログインできます。権限のあるクラスタを確認するには、「 get/mnode/about 」 API を使用します。応答では、「 token_url 」フィールドの IP アドレスは、権限のあるストレージクラスタの管理仮想 IP アドレス（ MVIP ）です。信頼できるクラスタにないユーザとして NetApp Hybrid Cloud Control にログインしようとすると、ログインに失敗します。

NetApp Hybrid Cloud Control の多くの機能は複数のストレージクラスタを使用するように設計されていますが、認証と許可には制限があります。認証と許可に関する制限事項として、信頼できるクラスタのユーザが、他のストレージクラスタのユーザでなくても、 NetApp Hybrid Cloud Control に関連付けられている他のクラスタに対して操作を実行できることがあります。

複数のストレージクラスタの管理を開始する前に、権限のあるクラスタで定義されているユーザが同じ権限を持つ他のすべてのストレージクラスタに定義されていることを確認してください。からユーザを管理できます link:../storage/concept_system_manage_manage_cluster_administrator_users.html["Element ソフトウェアユーザインターフェイス"]。

を参照してください link:../mnode/task_mnode_manage_storage_cluster_assets.html["ストレージクラスタアセットを作成および管理する"] 管理ノードのストレージクラスタアセットの使用の詳細については、を参照してください。



== 3 分の 1 のルール

NetApp SolidFire ストレージクラスタ内でタイプの異なるストレージノードを混在させる場合、 1 つのストレージノードに格納できるストレージクラスタの総容量の 33% を超えることはできません。



== 有効利用されない容量

新しく追加したノードがクラスタの合計容量の 50% を超えると、容量のルールに準拠するためにこのノードの一部の容量が使用できなくなります（「未使用」）。これは、ストレージ容量が追加されるまで有効です。容量のルールにも違反するような大規模なノードを追加すると、それまでに孤立していたノードは孤立しなくなり、新たに追加したノードが孤立する状態になります。この問題を回避するには、容量を常にペアで追加する必要があります。ノードが孤立すると、該当するクラスタエラーがスローされます。



== ストレージ効率

NetApp SolidFire ストレージクラスタでは、重複排除、圧縮、およびシンプロビジョニングを使用して、ボリュームの格納に必要な物理ストレージ容量を削減します。

* * 圧縮 *
+
圧縮は、データブロックを圧縮グループに集約し、各データブロックを 1 つのブロックとして格納することで、ボリュームに必要な物理ストレージの量を削減する機能です。

* * 重複排除 *
+
重複排除では、重複するデータブロックを破棄することでボリュームに必要な物理ストレージの量が削減されます。

* * シンプロビジョニング *
+
シンプロビジョニングされたボリュームまたは LUN では、ストレージが事前に予約されません。代わりに、ストレージは必要に応じて動的に割り当てられます。ボリュームまたは LUN 内のデータが削除されると、空きスペースはストレージシステムに戻されます





== ストレージクラスタのクォーラム

Element ソフトウェアは、選択したノードからストレージクラスタを作成します。これにより、クラスタ構成のレプリケートされたデータベースが保持されます。クラスタの耐障害性を維持するために、クラスタアンサンブルに参加するには、少なくとも 3 つのノードが必要です。
