---
permalink: storage/concept_prereq_switch_configuration_for_solidfire_clusters.html 
sidebar: sidebar 
keywords: cluster switch configuration, best practices for switch configuration, optimal storage performance, node hardware, traffic, cluster, Element software, best practices, switches, switch requirements, storage, performance, storage performance 
summary: NetApp Element ソフトウェアシステムには、スイッチに関する要件と、ストレージパフォーマンスを最適化するためのベストプラクティスがあります。 
---
= Element ソフトウェアを実行するクラスタのスイッチ設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element ソフトウェアシステムには、スイッチに関する要件と、ストレージパフォーマンスを最適化するためのベストプラクティスがあります。

ストレージノードには、ノードのハードウェアに応じて、 10GbE または 25GbE のいずれかのイーサネットスイッチが必要です。これらは、 iSCSI ストレージサービスおよびノードのクラスタ内サービスの通信に使用されます。次のタイプのトラフィックには 1GbE スイッチを使用できます。

* クラスタとノードの管理
* クラスタ内のノード間の管理トラフィック
* クラスタノードと管理ノード仮想マシンの間のトラフィック


|===


 a| 
* ベストプラクティス：クラスタトラフィックに使用するイーサネットスイッチを設定する際には、次のベストプラクティスに従う必要があります。

* クラスタ内の非ストレージトラフィックには、高可用性と負荷分散を実現するために 1GbE スイッチのペアを配置します。
* ストレージネットワークスイッチでは、スイッチをペアにして配置し、ジャンボフレーム（ MTU サイズ =9216 バイト）を設定して利用します。これにより、インストールが正常に完了し、パケットの断片化によるストレージネットワークエラーが解消されます。


|===
Element の導入には、次のトラフィックタイプごとに 1 つ、少なくとも 2 つのネットワークセグメントが必要です。

* 管理
* ストレージ / データ


NetApp H シリーズストレージノードのモデルや計画しているケーブル構成に応じて、別々のスイッチを使用してこれらのネットワークを物理的に分離するか、または VLAN を使用して論理的に分離することができます。ただしほとんどの環境では、これらのネットワークを VLAN を使用して論理的に分離する必要があります。

ストレージノードは、導入中およびその前後に通信可能である必要があります。

ストレージノードに別々の管理ネットワークを実装する場合は、それらの管理ネットワーク間にネットワークルートが確立されていることを確認してください。これらのネットワークにはゲートウェイが割り当てられている必要があり、ゲートウェイ間にルートが必要です。ノードと管理ネットワーク間の通信を確保するために、新しい各ノードにゲートウェイが割り当てられていることを確認してください。

NetApp Element には次のものが必要です。

* NetApp H シリーズストレージノードに接続されたすべてのスイッチポートをスパニングツリーのエッジポートとして設定する必要があります。
+
** Cisco スイッチでは、スイッチモデル、ソフトウェアバージョン、およびポートタイプに応じて、次のいずれかのコマンドを使用してこの操作を実行できます。
+
*** 「 panning - tree port type edge 」を選択します
*** 「パンニングツリーポートタイプエッジトランク」
*** ' パンツリー portfast
*** ' パンツリー portfast trunk


** Mellanox スイッチでは ' panning tree port type edge コマンドを使用してこれを実行できます


* ストレージトラフィックを処理するスイッチは、ポートあたり 10GbE 以上の速度をサポートする必要があります（ポートあたり最大 25GbE がサポートされます）。
* 管理トラフィックを処理するスイッチは、ポートあたり 1GbE 以上の速度をサポートする必要があります。
* ストレージトラフィックを処理するスイッチポートにジャンボフレームを設定する必要があります。インストールを成功させるには、ホストが 9000 バイトのパケットをエンドツーエンドで送信できる必要があります。
* すべてのストレージノード間のラウンドトリップネットワークレイテンシを 2 ミリ秒以下にする必要があります。


一部のノードは、専用の管理ポートからアウトオブバンド管理機能を提供します。NetApp H300S 、 H500S 、 H700S の各ノードでは、ポート A を介した IPMI アクセスも可能ですベストプラクティスとして、環境内のすべてのノードに対してアウトオブバンド管理を設定し、リモート管理を容易にすることを推奨します。



== を参照してください。

* https://docs.netapp.com/us-en/hci/docs/hci_prereqs_network_switch.html["NetApp HCI のネットワークとスイッチの要件"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

