---
permalink: storage/concept_system_manage_cluster_terms_manage_the_terms_of_use_banner.html 
sidebar: sidebar 
keywords: element, terms of use, banner, config, edit, terms of use, disable, enable 
summary: ユーザ向けのメッセージを含むバナーを有効にしたり、編集したり、設定したりできます。 
---
= 利用条件のバナーを管理します
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザ向けのメッセージを含むバナーを有効にしたり、編集したり、設定したりできます。

<<Enable the Terms of Use banner>>
<<Edit the Terms of Use banner>>
<<Disable the Terms of Use banner>>



== 利用条件のバナーを有効にします

ユーザが Element UI にログインしたときに表示される利用条件のバナーを有効にすることができます。ユーザがバナーをクリックすると、クラスタに対して設定したメッセージを含むテキストダイアログボックスが表示されます。バナーはいつでも無効にすることができます。

利用条件機能を有効にするには、クラスタ管理者の権限が必要です。

. [*Users*>*Terms of Use] をクリックします。
. [* 利用規約 * ] フォームに、 [ 利用規約 ] ダイアログボックスに表示するテキストを入力します。
+

NOTE: 最大文字数は 4096 文字です。

. [*Enable*] をクリックします。




== 利用条件のバナーを編集します

ユーザが利用条件のログインバナーを選択したときに表示されるテキストを編集できます。

.必要なもの
* 利用条件を設定するには、クラスタ管理者の権限が必要です。
* 利用条件機能が有効になっていることを確認します。


.手順
. [*Users*>*Terms of Use] をクリックします。
. [* 利用規約 * ] ダイアログボックスで、表示するテキストを編集します。
+

NOTE: 最大文字数は 4096 文字です。

. [ 変更の保存 *] をクリックします。




== 利用条件のバナーを無効にします

利用条件のバナーを無効にすることができます。バナーを無効にすると、ユーザが Element UI を使用する際に利用条件の同意を求められなくなります。

.必要なもの
* 利用条件を設定するには、クラスタ管理者の権限が必要です。
* 利用条件が有効になっていることを確認します。


.手順
. [*Users*>*Terms of Use] をクリックします。
. [*Disable*] をクリックします。

