---
permalink: storage/concept_intro_custom_protection_domains.html 
sidebar: sidebar 
keywords: Protection Domain layout,user-defined,custom layout 
summary: カスタム保護ドメインレイアウトを定義できます。各ノードは 1 つのカスタム保護ドメインのみに関連付けられます。デフォルトでは、各ノードは同じデフォルトのカスタム保護ドメインに割り当てられます。 
---
= カスタムの保護ドメイン
:icons: font
:imagesdir: ../media/


[role="lead"]
シャーシおよびノードの特定のレイアウトに一致するカスタム保護ドメインレイアウトを定義できます。

カスタムの保護ドメインが割り当てられていない場合：

* クラスタ処理には影響はありません。
* カスタムレベルは、トレラントでも耐障害性でもありません。


クラスタにカスタムの保護ドメインを設定すると、 Element Web UI ダッシュボードに表示される 3 つのレベルで保護が可能です。

* Not protected ：ストレージクラスタ内のカスタムの保護ドメインのいずれかに障害が発生しても、ストレージクラスタは保護されません。これを修正するには、クラスタにストレージ容量を追加するか、クラスタをデータ損失から保護するようにクラスタのカスタムの保護ドメインを再設定します。
* フォールトトレランス：カスタムの保護ドメインの 1 つで障害が発生した場合にデータ損失を防ぐために、ストレージクラスタに十分な空き容量が確保されています。
* 障害への耐障害性：カスタムの保護ドメインの 1 つに障害が発生した場合に自己回復可能な十分な空き容量がストレージクラスタにある。修復プロセスの完了後、他のドメインで障害が発生してもクラスタはデータ損失から保護されます。


複数のカスタム保護ドメインが割り当てられている場合、各サブシステムは重複を個別のカスタム保護ドメインに割り当てます。これができない場合は、重複したデータが別のノードに割り当てられます。各サブシステム（ビン、スライス、プロトコルエンドポイントプロバイダ、アンサンブルなど）は、それぞれ独立して機能します。

Element UI を使用して、を実行できます link:task_data_protection_configure_custom_protection_domains.html["カスタムの保護ドメインを設定します"^]または、次の API メソッドを使用できます。

* link:../api/reference_element_api_getprotectiondomainlayout.html["GetProtectionDomainLayout の略"^] - 各ノードがどのシャーシに配置されているか、およびどのカスタム保護ドメインが表示されます。
* link:../api/reference_element_api_setprotectiondomainlayout.html["SetProtectionDomainLayout の略"^] - 各ノードにカスタム保護ドメインを割り当てることができます。




== 詳細については、こちらをご覧ください

link:../api/index.html["Element API を使用してストレージを管理します"^]
