---
permalink: storage/concept_data_manage_volumes_solidfire_quality_of_service.html 
sidebar: sidebar 
keywords: qos policies, iops 
summary: SolidFire ストレージクラスタでは、サービス品質（ QoS ）パラメータをボリューム単位で指定できます。QoS を定義する 3 つの設定可能なパラメータである Min IOPS 、 Max IOPS 、および Burst IOPS を使用して、 IOPS （ 1 秒あたりの入出力）で測定されるクラスタパフォーマンスを保証することができます。 
---
= Quality of Service の略
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire ストレージクラスタでは、サービス品質（ QoS ）パラメータをボリューム単位で指定できます。QoS を定義する 3 つの設定可能なパラメータである Min IOPS 、 Max IOPS 、および Burst IOPS を使用して、 IOPS （ 1 秒あたりの入出力）で測定されるクラスタパフォーマンスを保証することができます。


NOTE: SolidFire Active IQ には、最適な設定と QoS 設定に関するアドバイスを提供する QoS 推奨ページがあります。

IOPS パラメータは、次のように定義します。

* * 最小 IOPS *
+
ストレージクラスタがボリュームに提供する平常時の最小 IOPS 。ボリュームに設定された Min IOPS は、そのボリュームに対して最低限保証されるパフォーマンスレベルです。パフォーマンスがこのレベルを下回ることはありません。

* * 最大 IOPS *
+
ストレージクラスタがボリュームに提供する平常時の最大 IOPS 。クラスタの IOPS レベルが非常に高い場合も、 IOPS パフォーマンスはこのレベル以下に抑えられます。

* * バースト IOPS *
+
短時間のバースト時に許容される最大 IOPS 。ボリュームが Max IOPS 未満で動作している間は、バーストクレジットが蓄積されます。パフォーマンスレベルが非常に高くなって最大レベルに達した場合、ボリュームで IOPS の短時間のバーストが許容されます。

+
Element ソフトウェアでは、 IOPS 使用率が低い状態でクラスタが稼働しているときに Burst IOPS が使用されます。

+
個々のボリュームは、蓄積したバーストクレジットを使用して、一定の「バースト期間」中は Max IOPS を最大で Burst IOPS レベルまで一時的に超過することができます。ボリュームのバースト時間は最大で 60 秒です。クラスタの容量にバーストに対応できるだけの余力があることが条件になります。

+
ボリュームは、 Max IOPS 未満で動作している 1 秒ごとに、 1 秒分のバーストクレジットを蓄積します（最大 60 秒）。

+
Burst IOPS には 2 つの制限があります。

+
** ボリュームは、蓄積したバーストクレジット数と同じ秒数だけ Max IOPS を超過できます。
** ボリュームが Max IOPS の設定を超えた場合は、 Burst IOPS の設定によって制限されます。つまり、バースト時の IOPS がボリュームの Burst IOPS の設定を超えることはありません。


* * 実効最大帯域幅 *
+
最大帯域幅は、（ QoS 曲線に基づく） IOPS に IO サイズを掛けて計算されます。

+
例

+
QoS パラメータを Min IOPS = 100 、 Max IOPS = 1000 、 Burst IOPS = 1500 に設定した場合、パフォーマンスの品質は次のようになります。

+
** 各ワークロードは、クラスタで IOPS に対するワークロードの競合が発生するまでは、最大で 1000 IOPS を持続的に使用することができます。競合が発生すると、すべてのボリュームの IOPS が指定の QoS 範囲内に戻ってパフォーマンスの競合が解消されるまで、 IOPS が少しずつ引き下げられます。
** すべてのボリュームのパフォーマンスは、最大で Min IOPS の 100 まで引き下げられます。Min IOPS である 100 を下回ることはなく、ワークロードの競合が解消されれば 100 IOPS よりも高いレベルにとどまることが可能です。
** パフォーマンスは長期間にわたって 1000 IOPS を超えることも、 100 IOPS を下回ることもありません。1500 IOPS （ Burst IOPS ）のパフォーマンスは、 Max IOPS 未満で動作することでバーストクレジットを蓄積したボリュームに対して短時間の間のみ許容されます。バーストレベルが持続することはありません。



