---
permalink: storage/concept_data_manage_vvol_protocol_endpoints.html 
sidebar: sidebar 
keywords: protocol endpoint, access, cluster, storage node, iscsi supported 
summary: プロトコルエンドポイントは、ホストが NetApp Element ソフトウェアを実行しているクラスタ上のストレージに対処する際に使用するアクセスポイントです。ユーザがプロトコルエンドポイントを削除または変更することはできません。プロトコルエンドポイントはアカウントには関連付けられず、またボリュームアクセスグループに追加することはできません。 
---
= プロトコルエンドポイント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プロトコルエンドポイントは、ホストが NetApp Element ソフトウェアを実行しているクラスタ上のストレージに対処する際に使用するアクセスポイントです。ユーザがプロトコルエンドポイントを削除または変更することはできません。プロトコルエンドポイントはアカウントには関連付けられず、またボリュームアクセスグループに追加することはできません。

Element ソフトウェアを実行しているクラスタでは、クラスタ内のストレージノードごとに 1 つのプロトコルエンドポイントが自動的に作成されます。たとえば、 6 ノードのストレージクラスタでは、 6 つのプロトコルエンドポイントが作成されて各 ESXi ホストにマッピングされます。プロトコルエンドポイントは Element ソフトウェアによって動的に管理され、必要に応じて手動操作なしに作成、移動、または削除されます。プロトコルエンドポイントはマルチパスのターゲットであり、補助 LUN の I/O プロキシとして機能します。各プロトコルエンドポイントは、標準の iSCSI ターゲットと同様に、利用可能な SCSI アドレスを使用します。プロトコルエンドポイントは、 vSphere Client では単一ブロック（ 512 バイト）のストレージデバイスとして表示されますが、このストレージデバイスをストレージとしてフォーマットしたり使用したりすることはできません。

サポートされているプロトコルは iSCSI だけです。Fibre Channel プロトコルはサポートされません。
