---
permalink: storage/concept_data_manage_vvol_work_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volume, configure vvols, use UI to manage 
summary: Element UI を使用して、仮想ボリュームおよび仮想ボリュームに関連付けられたストレージコンテナ、プロトコルエンドポイント、バインド、およびホストの情報を確認し、タスクを実行できます。 
---
= 仮想ボリュームを操作します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element UI を使用して、仮想ボリュームおよび仮想ボリュームに関連付けられたストレージコンテナ、プロトコルエンドポイント、バインド、およびホストの情報を確認し、タスクを実行できます。

Virtual Volumes （ VVol ）機能は、 NetApp Element ソフトウェアストレージシステムの出荷時点では無効になっています。Element UI を使用して vSphere VVol 機能を手動で有効にするタスクを 1 回だけ実行する必要があります。

VVol 機能を有効にすると、ユーザインターフェイスに VVol 関連の監視オプションと一部の管理オプションを使用できる VVol タブが表示されます。また、 VASA Provider と呼ばれるストレージ側のソフトウェアコンポーネントは、 vSphere 向けのストレージ認識サービスとして機能します。VVOL の作成、クローニング、編集などのほとんどの vVol コマンドは、 vCenter Server または ESXi ホストで開始され、 VASA Provider から Element ソフトウェアストレージシステムの Element API に変換されます。ストレージコンテナの作成、削除、管理および仮想ボリュームの削除を実行するコマンドは、 Element UI を使用して開始できます。

Element ソフトウェアストレージシステムで仮想ボリューム機能を使用するために必要な構成の大部分は、 vSphere で作成されます。vCenter への VASA Provider の登録、 VVol データストアの作成と管理、およびポリシーに基づくストレージの管理を行うには、 VMware vSphere Virtual Volumes for SolidFire ストレージ構成ガイドを参照してください。


NOTE: Element 12.5以前では、1つのvCenterインスタンスに複数のNetApp Element VASAプロバイダを登録しないでください。2 つ目の NetApp Element VASA Provider が追加されている場合、その結果、すべての VVOL データストアにアクセスできなくなります。


NOTE: VASA Provider を vCenter に登録済みの場合は、複数の vCenter に対する VASA サポートをアップグレードパッチとして利用できます。をインストールするには、から VASA39 .tar.gz ファイルをダウンロードします https://mysupport.netapp.com/products/element_software/VASA39/index.html["ネットアップのソフトウェアダウンロード"] サイトに移動し、マニフェストの指示に従います。NetApp Element VASA プロバイダはネットアップの証明書を使用します。このパッチでは、 vCenter が証明書を変更せずに使用して、 VASA および VVOL に使用する複数の vCenter をサポートします。証明書は変更しないでください。カスタム SSL 証明書は VASA でサポートされません。



== 詳細については、こちらをご覧ください

* xref:task_data_manage_vvol_enable_virtual_volumes.adoc[仮想ボリュームを有効にします]
* xref:task_data_manage_vvol_view_virtual_volume_details.adoc[仮想ボリュームの詳細を表示します]
* xref:task_data_manage_vvol_delete_a_virtual_volume.adoc[仮想ボリュームを削除します]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[ストレージコンテナを作成します]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[ストレージコンテナを編集します]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[ストレージコンテナを削除します]
* xref:concept_data_manage_vvol_protocol_endpoints.adoc[プロトコルエンドポイント]
* xref:concept_data_manage_vvol_bindings.adoc[バインド]
* xref:reference_data_manage_vvol_host_details.adoc[ホストの詳細]

