---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: Element ソフトウェアを実行するクラスタの容量が不足してくると、クラスタエラーが生成されてストレージ管理者に警告が表示されます。クラスタフルには 3 つのレベルがあり、いずれも NetApp Element UI に表示されます。警告、エラー、重大の 3 つです。 
---
= クラスタフルレベルを把握
:icons: font
:imagesdir: ../media/


[role="lead"]
Element ソフトウェアを実行するクラスタの容量が不足してくると、クラスタエラーが生成されてストレージ管理者に警告が表示されます。クラスタフルには 3 つのレベルがあり、いずれも NetApp Element UI に表示されます。警告、エラー、重大の 3 つです。

クラスタブロックストレージフルに関する警告には、 BlockClusterFull エラーコードが使用されます。クラスタフルの重大度レベルは、 Element UI のアラートタブで確認できます。

BlockClusterFull の重大度レベルについて以下に説明します。

* * 警告 *
+
ユーザが設定可能な警告で、クラスタのブロック容量が Error レベルに近づくと表示されます。このレベルはデフォルトで Error レベルの 3% 下に設定されており、 Element UI および API を使用して調整できます。できるだけ早く容量を追加するか、または解放する必要があります。

* * エラー *
+
クラスタがこの状態の場合、ノードが失われると、 Double Helix データ保護を再構築できるだけの容量がクラスタに残っていません。クラスタがこの状態にある間は、ボリュームの新規作成、クローン、および Snapshot の処理はすべてブロックされます。これは、クラスタが安全な状態または推奨される状態ではありません。ただちに容量を追加するか、または解放する必要があります。

* * 重要 *
+
このエラーは、クラスタが 100% 消費されているときに発生します。クラスタは読み取り専用状態で、このクラスタへの新たな iSCSI 接続を確立することはできません。この段階に達した場合は、容量をただちに解放または追加する必要があります。



クラスタメタデータストレージフルに関する警告には、 MetadataClusterFull エラーコードが使用されます。クラスタメタデータのストレージフルは、 Element UI の Reporting タブの概要ページの Cluster Capacity セクションで確認できます。

MetadataClusterFull の重大度レベルについて以下に説明します。

* * 警告 *
+
ユーザが設定可能な警告で、クラスタのメタデータ容量が Error レベルに近づくと表示されます。このレベルはデフォルトで Error レベルの 3% 下に設定されており、 Element API を使用して調整できます。できるだけ早く容量を追加するか、または解放する必要があります。

* * エラー *
+
クラスタがこの状態の場合、ノードが失われると、 Double Helix データ保護を再構築できるだけの容量がクラスタに残っていません。クラスタがこの状態にある間は、ボリュームの新規作成、クローン、および Snapshot の処理はすべてブロックされます。これは、クラスタが安全な状態または推奨される状態ではありません。ただちに容量を追加するか、または解放する必要があります。

* * 重要 *
+
このエラーは、クラスタが 100% 消費されているときに発生します。クラスタは読み取り専用状態で、このクラスタへの新たな iSCSI 接続を確立することはできません。この段階に達した場合は、容量をただちに解放または追加する必要があります。




NOTE: 環境の 2 ノードクラスタの次のしきい値。

* メタデータの使用率エラーは、この値よりも 20% 低くなっています。
* ブロックフルエラーは、ブロックドライブ（未使用の容量を含む）が重大より 1 本低くなっているため、ブロックドライブ 2 本分の容量は重要度よりも低くなります。

