---
permalink: storage/concept_system_manage_drives_managing_drives.html 
sidebar: sidebar 
keywords: drives, manage, cluster, element ui, remove drives 
summary: 各ノードには 1 つ以上の物理ドライブが搭載され、クラスタのデータの一部が格納されます。クラスタにドライブが追加されると、そのドライブの容量とパフォーマンスがクラスタで使用されるようになります。Element UI を使用してドライブを管理できます。 
---
= ドライブを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各ノードには 1 つ以上の物理ドライブが搭載され、クラスタのデータの一部が格納されます。クラスタにドライブが追加されると、そのドライブの容量とパフォーマンスがクラスタで使用されるようになります。Element UI を使用してドライブを管理できます。



== ドライブの詳細

クラスタタブのドライブページには、クラスタ内のアクティブドライブのリストが表示されます。ページをフィルタするには、 Active 、 Available 、 Removing 、 Erasing 、 Failed の各タブを選択します。

クラスタを最初に初期化した時点では、アクティブドライブのリストは空です。未割り当てのドライブをクラスタに追加して、新しい SolidFire クラスタの作成後に Available タブに表示できます。

アクティブドライブのリストに表示される項目は次のとおりです。

* * ドライブ ID *
+
ドライブに割り当てられている連番。

* * ノード ID *
+
クラスタへの追加時にノードに割り当てられたノード番号。

* * ノード名 *
+
ドライブが格納されているノードの名前。

* * スロット *
+
ドライブが物理的に配置されているスロットの番号。

* * 容量 *
+
ドライブのサイズ（ GB 単位）。

* * シリアル *
+
ドライブのシリアル番号。

* * 摩耗度残量 *
+
摩耗レベルインジケータ。

+
ストレージシステムからは、各ソリッドステートドライブ（ SSD ）でデータの書き込み / 消去に利用できるおおよその残容量が報告されます。ドライブの設計上の書き込み / 消去サイクルの 5% が消費されている場合は、摩耗度残量は 95% と報告されます。ドライブの摩耗度情報は自動的には更新されません。情報を更新するには、ページを更新するか、またはページを閉じてリロードします。

* * タイプ *
+
ドライブのタイプ。block または metadata のいずれかです。





== を参照してください。

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

