---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: SolidFire ストレージシステムのクラスタ管理者アカウントを管理できます。実行できるクラスタ管理機能には、クラスタ管理者アカウントの作成、削除、編集、クラスタ管理者パスワードの変更、ユーザのシステムアクセスを管理するための LDAP の設定などがあります。 
---
= クラスタ管理者のユーザアカウントを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire ストレージシステムのクラスタ管理者アカウントの管理では、クラスタ管理者アカウントの作成、削除、編集、クラスタ管理者パスワードの変更、およびユーザのシステムアクセスを管理するための LDAP の設定を行います。



== ストレージクラスタ管理者アカウントのタイプ

NetApp Element ソフトウェアを実行するストレージクラスタには、プライマリクラスタ管理者アカウントとクラスタ管理者アカウントの 2 種類の管理者アカウントがあります。

* * プライマリクラスタ管理者アカウント *
+
この管理者アカウントは、クラスタ作成時に作成されます。このアカウントは、クラスタへの最高レベルのアクセス権を持つプライマリの管理アカウントです。このアカウントは、 Linux システムの root ユーザに相当します。この管理者アカウントのパスワードを変更できます。

* * クラスタ管理者アカウント *
+
クラスタ管理者アカウントには、クラスタ内で特定のタスクを実行するための限定的な管理アクセスを付与できます。各クラスタ管理者アカウントに割り当てられたクレデンシャルを使用して、ストレージシステム内での API や Element UI の要求が認証されます。




NOTE: ノード UI からクラスタ内のアクティブノードにアクセスするには、ローカル（ LDAP 以外）のクラスタ管理者アカウントが必要です。まだクラスタに含まれていないノードにアクセスする場合、アカウントのクレデンシャルは必要ありません。



== クラスタ管理者の詳細を表示

. クラスタ全体（ LDAP 以外）のクラスタ管理者アカウントを作成するには、次の操作を実行します。
+
.. [*Users*>*Cluster Admins] をクリックします。


. Users タブの Cluster Admins ページで、次の情報を表示できます。
+
** * ID * ：クラスタ管理者アカウントに割り当てられたシーケンシャル番号。
** * Username * ：クラスタ管理者アカウントの作成時に指定した名前。
** * アクセス * ：ユーザアカウントに割り当てられたユーザ権限。有効な値は次のとおり
+
*** 読み取り
*** レポート作成
*** ノード
*** ドライブ
*** 個のボリューム
*** アカウント
*** clusterAdmin の権限が必要です
*** 管理者
*** supportAdmin




+

NOTE: administrator アクセスタイプには、すべての権限が割り当てられています。

+
** * タイプ * ：クラスタ管理者のタイプ。有効な値は次のとおり
+
*** クラスタ
*** LDAP


** * 属性 * ： Element API を使用して作成されたクラスタ管理者アカウントに対し、作成時に設定された名前と値のペアが表示されます。
+
を参照してください link:../api/index.html["NetApp Element ソフトウェア API リファレンス"]。







== クラスタ管理者アカウントを作成

新しいクラスタ管理者アカウントを作成し、ストレージシステムの特定の領域へのアクセスを許可または制限する権限を付与できます。クラスタ管理者アカウントの権限を設定すると、割り当てていない権限については読み取り専用権限が付与されます。

LDAP クラスタ管理者アカウントを作成する場合は、作成を開始する前にクラスタで LDAP が設定されていることを確認します。

link:task_system_manage_enable_ldap_authentication.html["Element ユーザインターフェイスで LDAP 認証を有効にします"]

レポート作成、ノード、ドライブ、ボリューム、アカウント用のクラスタ管理者アカウントの権限をあとから変更することができます。 クラスタレベルのアクセスとアクセス許可を有効にすると、そのレベルの書き込みアクセスが割り当てられます。選択しなかったレベルについては、読み取り専用アクセスが付与されます。

システム管理者が作成したクラスタ管理者ユーザアカウントをあとから削除することもできます。クラスタの作成時に作成されたプライマリクラスタ管理者アカウントを削除することはできません。

. クラスタ全体（ LDAP 以外）のクラスタ管理者アカウントを作成するには、次の操作を実行します。
+
.. [*Users*>*Cluster Admins] をクリックします。
.. Create Cluster Admin をクリックします。
.. ユーザタイプとして「 * Cluster * 」を選択します。
.. アカウントのユーザ名とパスワードを入力し、確認のためにパスワードをもう一度入力します。
.. アカウントに適用するユーザ権限を選択します。
.. チェックボックスをオンにして、エンドユーザライセンス契約に同意します。
.. Create Cluster Admin をクリックします。


. LDAP ディレクトリにクラスタ管理者アカウントを作成するには、次の操作を実行します。
+
.. [*Cluster*>*LDAP*] をクリックします。
.. LDAP 認証が有効になっていることを確認します。
.. [ ユーザー認証のテスト ] をクリックし、ユーザーまたはユーザーがメンバーになっているグループのいずれかに表示される識別名をコピーして、後で貼り付けることができます。
.. [*Users*>*Cluster Admins] をクリックします。
.. Create Cluster Admin をクリックします。
.. LDAP ユーザタイプを選択します。
.. [Distinguished Name] フィールドのテキストボックスの例に従って、ユーザまたはグループの完全な識別名を入力します。または、前の手順でコピーした識別名を貼り付けます。
+
識別名がグループの一部である場合、 LDAP サーバ上でそのグループのメンバーであるユーザには、この管理者アカウントの権限が与えられます。

+
LDAP クラスタ管理者ユーザまたはグループを追加する場合、ユーザ名の一般的な形式は「 LDAP ： <Full Distinguished Name>` 」です。

.. アカウントに適用するユーザ権限を選択します。
.. チェックボックスをオンにして、エンドユーザライセンス契約に同意します。
.. Create Cluster Admin をクリックします。






== クラスタ管理者の権限を編集します

レポート作成、ノード、ドライブ、ボリューム、アカウント用のクラスタ管理者アカウントの権限を変更できます。 クラスタレベルのアクセスとアクセス許可を有効にすると、そのレベルの書き込みアクセスが割り当てられます。選択しなかったレベルについては、読み取り専用アクセスが付与されます。

. [*Users*>*Cluster Admins] をクリックします。
. 編集するクラスタ管理者の操作アイコンをクリックします。
. [ 編集（ Edit ） ] をクリックします。
. アカウントに適用するユーザ権限を選択します。
. [ 変更の保存 *] をクリックします。




== クラスタ管理者アカウントのパスワードを変更します

Element UI を使用してクラスタ管理者のパスワードを変更できます。

. [*Users*>*Cluster Admins] をクリックします。
. 編集するクラスタ管理者の操作アイコンをクリックします。
. [ 編集（ Edit ） ] をクリックします。
. Change Password フィールドに新しいパスワードを入力し、確認のためにもう一度入力します。
. [ 変更の保存 *] をクリックします。




== 詳細については、こちらをご覧ください

* link:task_system_manage_enable_ldap_authentication.html["Element ユーザインターフェイスで LDAP 認証を有効にします"]
* link:concept_system_manage_manage_ldap.html["LDAP を無効にする"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

