---
permalink: storage/concept_system_manage_nodes_node_versioning_and_compatibility.html 
sidebar: sidebar 
keywords: compatibility, node version, clusters, software version, compatible versions, major, minor, micro 
summary: ノードの互換性は、ノードにインストールされている Element ソフトウェアのバージョンに基づきます。ノードとクラスタのバージョンに互換性がない場合、 Element ソフトウェアベースのストレージクラスタは、ノードをクラスタ上の Element ソフトウェアのバージョンに自動で更新します。 
---
= ノードのバージョンと互換性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードの互換性は、ノードにインストールされている Element ソフトウェアのバージョンに基づきます。ノードとクラスタのバージョンに互換性がない場合、 Element ソフトウェアベースのストレージクラスタは、ノードをクラスタ上の Element ソフトウェアのバージョンに自動で更新します。

以下に、 Element ソフトウェアのバージョン番号を構成するソフトウェアのリリースレベルを示します。

* * メジャー *
+
ソフトウェアのリリースを示す最初の番号。あるメジャーコンポーネント番号のノードを、メジャー番号が異なるノードを含むクラスタに追加することはできません。また、メジャーバージョンが異なるノードが混在したクラスタを作成することはできません。

* * マイナー *
+
メジャーリリースに追加された既存のソフトウェア機能に対する小規模な機能追加や拡張を示す 2 番目の番号。マイナーコンポーネントはメジャーコンポーネントに対して増分され、マイナーコンポーネントの異なる Element ソフトウェアリリース間に互換性はありません。たとえば、 11.0 は 11.1 と互換性がなく、 11.1 は 11.2 と互換性がありません。

* * マイクロ *
+
「 major.minor 」の形式で表される Element ソフトウェアバージョンへの互換性のあるパッチ（差分リリース）を示す 3 番目の番号。たとえば、 11.0.1 は 11.0.2 と互換性があり、 11.0.2 は 11.0.3 と互換性があります。



互換性を確保するためには、メジャーバージョンとマイナーバージョンの番号が一致しているマイクロバージョンの番号は一致しなくても互換性があります。
