---
permalink: storage/concept_data_manage_vvol_manage_storage_containers.html 
sidebar: sidebar 
keywords: storage container, storage containers, about storage containers, cluster, vvols, create, view details, chap, edit, delete 
summary: ストレージコンテナは vSphere のデータストアに相当し、 Element ソフトウェアを実行するクラスタ上に作成されます。 
---
= ストレージコンテナを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージコンテナは vSphere のデータストアに相当し、 Element ソフトウェアを実行するクラスタ上に作成されます。

ストレージコンテナが作成され、 NetApp Element アカウントに関連付けられます。Element ストレージ上に作成されたストレージコンテナは、 vCenter および ESXi では vSphere データストアとして表示されます。ストレージコンテナには Element ストレージのスペースはいっさい割り当てられず、単に仮想ボリュームを論理的に関連付けるために使用されます。

クラスタあたり最大 4 つのストレージコンテナがサポートされます。VVol 機能を有効にするには、少なくとも 1 つのストレージコンテナが必要です。



== ストレージコンテナを作成します

Element UI でストレージコンテナを作成して、 vCenter で検出できます。VVol を使用する仮想マシンのプロビジョニングを開始するためには、少なくとも 1 つのストレージコンテナを作成する必要があります。

作業を開始する前に、クラスタの Element UI で VVol 機能を有効にします。

.手順
. 「 * VVOLs * > * Storage Containers * 」を選択します。
. Create Storage Containers * ボタンをクリックします。
. Create a New Storage Container * （新しいストレージコンテナの作成）ダイアログボックスで、ストレージコンテナ情報を入力します。
+
.. ストレージコンテナの名前を入力します。
.. CHAP のイニシエータシークレットとターゲットシークレットを設定します。
+

TIP: シークレットを自動的に生成する場合は、 CHAP 設定のフィールドを空白のままにします。

.. Create Storage Container （ストレージコンテナの作成）ボタンをクリックします。


. 新しいストレージコンテナが「ストレージコンテナ * 」サブタブのリストに表示されていることを確認します。
+

NOTE: NetApp Element アカウント ID は自動的に作成されてストレージコンテナに割り当てられるため、アカウントを手動で作成する必要はありません。





== ストレージコンテナの詳細を表示します

VVol タブのストレージコンテナページでは、クラスタ上のすべてのアクティブなストレージコンテナに関する情報を表示できます。

* * アカウント ID * ：ストレージコンテナに関連付けられた NetApp Element アカウントの ID 。
* * 名前 * ：ストレージコンテナの名前。
* * ステータス * ：ストレージコンテナのステータス。有効な値は次のとおり
+
** Active ：ストレージコンテナは使用中です。
** Locked ：ストレージコンテナはロックされています。


* * PE Type * ：プロトコルエンドポイントのタイプ（ Element ソフトウェアで使用可能なプロトコルは SCSI のみです）。
* * Storage Container ID * ：仮想ボリュームストレージコンテナの UUID 。
* * Active Virtual Volumes * ：ストレージコンテナに関連付けられたアクティブな仮想ボリュームの数。




== 個々のストレージコンテナの詳細を表示します

個々のストレージコンテナのストレージコンテナ情報を表示するには、 vVol タブのストレージコンテナページでその情報を選択します。

* * アカウント ID * ：ストレージコンテナに関連付けられた NetApp Element アカウントの ID 。
* * 名前 * ：ストレージコンテナの名前。
* * ステータス * ：ストレージコンテナのステータス。有効な値は次のとおり
+
** Active ：ストレージコンテナは使用中です。
** Locked ：ストレージコンテナはロックされています。


* * CHAP Initiator Secret * ：イニシエータの一意の CHAP シークレット。
* * CHAP Target Secret * ：ターゲットの一意の CHAP シークレット。
* * Storage Container ID * ：仮想ボリュームストレージコンテナの UUID 。
* * Protocol Endpoint Type * ：プロトコルエンドポイントのタイプを示します（使用可能なプロトコルは SCSI のみです）。




== ストレージコンテナを編集します

Element UI でストレージコンテナの CHAP 認証を変更できます。

. 「 * VVOLs * > * Storage Containers * 」を選択します。
. 編集するストレージコンテナの * Actions * アイコンをクリックします。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. CHAP Settings で、認証に使用するイニシエータシークレットとターゲットシークレットのクレデンシャルを編集します。
+

TIP: CHAP 設定のクレデンシャルを変更しない場合、クレデンシャルは変更されません。クレデンシャルのフィールドを空白にすると、新しいシークレットが自動的に生成されます。

. [ 変更の保存 *] をクリックします。




== ストレージコンテナを削除します

Element UI からストレージコンテナを削除できます。

すべての仮想マシンを VVol データストアから削除しておく必要があります。

.手順
. 「 * VVOLs * > * Storage Containers * 」を選択します。
. 削除するストレージコンテナの * Actions * アイコンをクリックします。
. 表示されたメニューで、 * 削除 * を選択します。
. 操作を確定します。
. ストレージコンテナ * サブタブでストレージコンテナのリストを更新して、ストレージコンテナが削除されたことを確認します。

