---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: 一方または両方のメタデータドライブ（またはスライスドライブ）で障害が発生した場合は、そのドライブをクラスタに戻すことでドライブをリカバリできます。このリカバリ処理は、ノードで MDSS 機能がすでに有効になっている場合に NetApp Element UI で実行できます。 
---
= 基本的な MDSS ドライブのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一方または両方のメタデータドライブ（またはスライスドライブ）で障害が発生した場合は、そのドライブをクラスタに戻すことでドライブをリカバリできます。このリカバリ処理は、ノードで MDSS 機能がすでに有効になっている場合に NetApp Element UI で実行できます。

ノード内の一方または両方のメタデータドライブで障害が発生すると、スライスサービスがシャットダウンし、両方のドライブのデータがノードの別のドライブにバックアップされます。

以下は、想定される障害のシナリオと、問題を修正するための基本的な推奨事項です。



== システムスライスドライブに障害が発生した

* このシナリオでは、スロット 2 が検証され、使用可能な状態に戻ります。
* スライスサービスをオンラインに戻す前に、システムスライスドライブにデータを再度読み込む必要があります。
* システムスライスドライブを交換し、システムスライスドライブが使用可能になったらシステムスライスドライブとスロット 2 のドライブを同時に追加します。



NOTE: スロット 2 のドライブをメタデータドライブとして単独で追加することはできません。両方のドライブを同時にノードに戻す必要があります。



== スロット 2 に障害が発生した

* このシナリオでは、システムスライスドライブが検証され、使用可能な状態に戻ります。
* スロット 2 をスペアと交換し、スロット 2 が使用可能になったらシステムスライスドライブとスロット 2 のドライブを同時に追加します。




== システムスライスドライブとスロット 2 に障害が発生した

* システムスライスドライブとスロット 2 の両方をスペアドライブと交換します。両方のドライブが使用可能になったら、システムスライスドライブとスロット 2 のドライブを同時に追加します。




== 処理の順序

* 障害が発生したハードウェアドライブをスペアドライブと交換します（両方のドライブに障害が発生した場合は、両方とも交換します）。
* ドライブにデータが再度読み込まれて available 状態になったら、ドライブをクラスタに戻します。




== 検証処理

* スロット 0 （または内部）とスロット 2 のドライブがアクティブドライブのリストでメタデータドライブとして識別されていることを確認します。
* スライスの分散がすべて完了した（イベントログに moving slices メッセージが表示されなくなって 30 分以上経過した）ことを確認します。




== を参照してください。

xref:task_troubleshoot_add_mdss_drives.adoc[MDSS ドライブを追加します]
