---
permalink: storage/concept_intro_clusters.html 
sidebar: sidebar 
keywords: clusters, about clusters, collection of nodes, nodes in a cluster, block storage, logical group, add nodes, access cluster 
summary: クラスタは、 SolidFire ストレージシステムの中心であり、複数のノードで構成されます。SolidFire のストレージ効率化を実現するには、クラスタに少なくとも 4 つのノードが必要です。クラスタはネットワーク上では 1 つの論理グループとして認識され、ブロックストレージとしてアクセスできます。 
---
= クラスタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタは、 SolidFire ストレージシステムの中心であり、複数のノードで構成されます。SolidFire のストレージ効率化を実現するには、クラスタに少なくとも 4 つのノードが必要です。クラスタはネットワーク上では 1 つの論理グループとして認識され、ブロックストレージとしてアクセスできます。

新しいクラスタを作成すると、 1 つのノードがそのクラスタの通信の所有者として初期化され、クラスタ内の各ノードに対してネットワーク通信が確立されます。このプロセスは、新しいクラスタごとに 1 回だけ実行します。クラスタは、 Element UI または API を使用して作成できます。

クラスタをスケールアウトするには、ノードを追加します。新しいノードを追加するときにサービスが中断されることはなく、追加したノードのパフォーマンスと容量がクラスタで自動的に使用されます。

管理者とホストは、仮想 IP アドレスを使用してクラスタにアクセスできます。クラスタ内のいずれのノードも仮想 IP アドレスをホストできます。管理仮想 IP （ MVIP ）は 1GbE 接続でのクラスタ管理を提供し、ストレージ仮想 IP （ SVIP ）はホストからストレージへの 10GbE 接続でのアクセスを提供します。これらの仮想 IP アドレスは、 SolidFire クラスタのサイズや構成に関係なく、一貫した接続を可能にします。仮想 IP アドレスをホストするノードで障害が発生した場合、クラスタ内の別のノードが仮想 IP アドレスを引き継ぎます。


NOTE: Element バージョン 11.0 以降では、ノードの管理ネットワークに IPv4 、 IPv6 、または両方のアドレスを設定できます。この環境は、ストレージノードと管理ノードの両方に対応します。ただし、 IPv6 をサポートしない管理ノード 11.3 以降がこれに該当します。クラスタの作成時には、 IPv4 または IPv6 のどちらかのアドレスを 1 つだけ MVIP に使用でき、これと同じアドレスタイプをすべてのノードで設定する必要があります。
