---
permalink: storage/concept_intro_solidfire_software_interfaces.html 
sidebar: sidebar 
keywords: interfaces, integration, user interface, Plug-in, vCenter, API, node UIs, command line, snapshots, shadow copies, Element software, Element, Element UI, UI, manage storage, utilities, integration utilities 
summary: NetApp Element ストレージシステムは、 SolidFire のソフトウェアインターフェイスと統合ユーティリティを使用して管理できます。 
---
= SolidFire ソフトウェアインターフェイス
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element ストレージシステムは、 SolidFire のソフトウェアインターフェイスと統合ユーティリティを使用して管理できます。

* * NetApp Element ソフトウェア・ユーザー・インターフェイス *
+
SolidFire ストレージをセットアップし、クラスタの容量とパフォーマンスを監視できるほか、マルチテナントインフラ全体のストレージアクティビティを管理できます。Element は、 SolidFire クラスタの中核をなすストレージオペレーティングシステムです。Element ソフトウェアは、クラスタ内のすべてのノードで独立して動作します。 Element では、クラスタのノードをリソースに結合し、単一のストレージシステムとして外部クライアントに提供することができます。Element ソフトウェアは、システム全体のすべてのクラスタの調整、拡張、管理を担います。ソフトウェアのインターフェイスは Element API を基盤としています。

* * NetApp Element Plug-in for vCenter Server*
+
Element ソフトウェアを実行しているストレージクラスタを設定および管理できます。このプラグインは、 VMware vSphere で Element UI の代わりとなるインターフェイスを提供します。

* * NetApp Element ソフトウェア API*
+
一連のオブジェクト、メソッド、ルーチンを使用して SolidFire ストレージを管理できます。Element API は、 HTTPS 経由の JSON-RPC プロトコルに基づいています。Element UI で API 処理を監視するには、 API ログを有効にします。これにより、システムに対して実行されているメソッドを確認できます。要求と応答の両方を有効にすると、実行したメソッドに対するシステムの応答を確認できます。

* * 管理ノード UI *
+
管理ノードには 2 つの UI が装備されています。 REST ベースのサービスを管理するための UI と、ネットワーク / クラスタ設定の管理とオペレーティングシステムのテスト / ユーティリティを実行するためのノード UI です。REST API UI からは、管理ノード上の管理サービスを制御するサービス関連 API のメニューにアクセスできます。





== その他の統合ユーティリティおよびツール

通常は NetApp Element 、 NetApp Element API 、および NetApp Element Plug-in for vCenter Server を使用してストレージを管理しますが、その他のユーティリティやツールを使用することもできます。

* https://mysupport.netapp.com/products/p/vro.html["ネットアップのダウンロード： SolidFire vRO"]
+
VMware vRealize Orchestrator ™を使用すると、 SolidFire API を使用して SolidFire ストレージシステムを簡単に管理できます。

* https://mysupport.netapp.com/products/p/elementsdk.html["ネットアップのダウンロード： Element SDK"]
+
では、次のツールを使用して SolidFire クラスタを管理できます。

+
** SolidFire コマンドライン
** SolidFire Postman API テストスイート： SolidFire API 呼び出しをテストする一連の Postman 関数を使用できます。
** SolidFire PowerShell ：プログラマは SolidFire API を使用して SolidFire ストレージシステムを管理する一連の Microsoft ® Windows ® PowerShell ® 関数を使用できます。
** SolidFire SDK Java: プログラマは SolidFire API を Java ™プログラミング言語と統合できます。
** SolidFire SDK.NET ：プログラマは SolidFire API を .NET プログラミングプラットフォームに統合できます。
** SolidFire SDK Python-: プログラマは SolidFire API を Python ™プログラミング言語と統合できます。


* https://mysupport.netapp.com/products/p/elementsra.html["ネットアップのダウンロード： SolidFire Storage Replication Adapter"]
+
VMware ® Site Recovery Manager ™（ SRM ）と統合して、レプリケートされた SolidFire ストレージクラスタ（アレイ）との通信を可能にし、サポートされているワークフローを実行します。

* https://mysupport.netapp.com/products/p/elementvss.html["ネットアップのダウンロード： SolidFire VSS Provider"]
+
VSS シャドウコピーを SolidFire の Snapshot およびクローンと統合します。


