---
permalink: storage/concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html 
sidebar: sidebar 
keywords: volume access groups, initiators, working with, chap, fc, iscsi 
summary: iSCSI イニシエータまたは Fibre Channel イニシエータを使用して、ボリュームアクセスグループ内に定義されたボリュームにアクセスできます。 
---
= ボリュームアクセスグループとイニシエータを使用する
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI イニシエータまたは Fibre Channel イニシエータを使用して、ボリュームアクセスグループ内に定義されたボリュームにアクセスできます。

アクセスグループを作成するには、 iSCSI イニシエータの IQN または Fibre Channel の WWPN をボリュームのグループにマッピングします。アクセスグループに追加した各 IQN は、 CHAP 認証なしでグループ内の各ボリュームにアクセスできます。

CHAP 認証には、次の 2 種類の方法があります。

* アカウントレベルの CHAP 認証：アカウントに CHAP 認証を割り当てることができます。
* イニシエータレベルの CHAP 認証： 1 つのアカウントを 1 つの CHAP にバインドすることなく、特定のイニシエータに一意の CHAP ターゲットとシークレットを割り当てることができます。このイニシエータレベルの CHAP 認証では、アカウントレベルのクレデンシャルが置き換えられます


必要に応じて、イニシエータ単位の CHAP を使用して、イニシエータの承認とイニシエータごとの CHAP 認証を適用できます。これらのオプションはイニシエータ単位で定義でき、アクセスグループにはオプションの異なるイニシエータを混在させることができます。

アクセスグループに追加した各 WWPN は、アクセスグループ内のボリュームへの Fibre Channel ネットワークアクセスを許可します。


NOTE: ボリュームアクセスグループには次の制限があります。

* 1 つのアクセスグループに含めることができる IQN または WWPN は最大 64 個です。
* 1 つのアクセスグループに含めることができるボリュームは最大 2 、 000 個です。
* 1 つの IQN または WWPN が属することのできるアクセスグループは 1 つだけです。
* 1 つのボリュームが最大 4 つのアクセスグループに属することができます。




== 詳細については、こちらをご覧ください

* xref:task_data_manage_vol_access_group_create_a_volume_access_group.adoc[ボリュームアクセスグループを作成します]
* xref:task_data_manage_vol_access_group_add_volumes.adoc[アクセスグループにボリュームを追加する]
* xref:task_data_manage_vol_access_group_remove_volumes.adoc[アクセスグループからボリュームを削除します]
* xref:task_data_manage_vol_access_group_create_an_initiator.adoc[イニシエータを作成します]
* xref:task_data_manage_vol_access_group_edit_an_initiator.adoc[イニシエータを編集します]
* xref:task_data_manage_vol_access_group_add_a_single_initiator.adoc[ボリュームアクセスグループに単一のイニシエータを追加します]
* xref:task_data_manage_vol_access_group_add_multiple_initiators.adoc[ボリュームアクセスグループに複数のイニシエータを追加します]
* xref:task_data_manage_vol_access_group_remove_initiators_from_an_access_group.adoc[アクセスグループからイニシエータを削除します]
* xref:task_data_manage_vol_access_group_delete.adoc[アクセスグループを削除する]
* xref:task_data_manage_vol_access_group_delete_an_initiator.adoc[イニシエータを削除します]

