---
permalink: storage/concept_intro_drives.html 
sidebar: sidebar 
keywords: drives, physical drives, cluster data, storage node, volume metadata, block drives, clusters 
summary: ストレージノードには 1 つ以上の物理ドライブが搭載され、クラスタのデータの一部が格納されます。クラスタにドライブが追加されると、そのドライブの容量とパフォーマンスがクラスタで使用されるようになります。 
---
= ドライブ
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードには 1 つ以上の物理ドライブが搭載され、クラスタのデータの一部が格納されます。クラスタにドライブが追加されると、そのドライブの容量とパフォーマンスがクラスタで使用されるようになります。

ストレージノードには、次の 2 種類のドライブが含まれます。

* * ボリュームメタデータドライブ *
+
クラスタ内の各ボリューム、クローン、または Snapshot の定義情報を圧縮して格納します。システム内のメタデータドライブの合計容量によって、ボリュームとしてプロビジョニングできるストレージの最大容量が決まります。プロビジョニング可能なストレージの最大容量は、クラスタのブロックドライブに実際に格納されるデータ量とは関係ありません。ボリュームメタデータドライブには、 Double Helix データ保護を使用してデータがクラスタ内に重複して格納されます。

+

NOTE: 一部のシステムイベントログおよびエラーメッセージでは、ボリュームメタデータドライブではなくスライスドライブと表記される場合があります。

* * ブロックドライブ *
+
サーバアプリケーションボリューム用に、重複排除済みのデータブロックを圧縮して格納します。ブロックドライブはシステムのストレージ容量の大部分を占めます。データの書き込み要求に加えて、 SolidFire クラスタにすでに格納されているデータの読み取り要求の大部分がブロックドライブで発生します。格納可能なデータの最大容量は、システム内のブロックドライブの合計容量に、圧縮、シンプロビジョニング、および重複排除の効果を加味して決まります。


