---
permalink: storage/reference_replication_volume_pairing_warnings.html 
sidebar: sidebar 
keywords: volume warnings, messages, replication, data protection 
summary: これらのメッセージは、データ保護タブのボリュームペアページでボリュームをペアリングしたあとに表示されます。これらのメッセージは、 Replicating Volumes （レプリケーションボリューム）リストビューでペアのソースとターゲットの両方に表示されます（特に指定がない限り）。 
---
= ボリュームペアリングに関する警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
これらのメッセージは、データ保護タブのボリュームペアページでボリュームをペアリングしたあとに表示されます。表示されるメッセージは、 Replicating Volumes （レプリケーションボリューム）リストビューでペアのソースとターゲットの両方に表示されます（特に指定がない限り）。

* * PausedClusterFull *
+
ターゲットクラスタがいっぱいのため、ソースレプリケーションと一括データ転送を続行できません。このメッセージは、ペアのソース側にのみ表示されます。

* * PausedExceededMaxSnapshotCount *
+
ターゲットボリュームに格納された Snapshot の数が上限に達しており、 Snapshot をこれ以上レプリケートできません。

* * PausedManual*
+
ローカルボリュームが手動で一時停止されています。レプリケーションを再開するには、一時停止を解除する必要があります。

* * PausedManualRemote *
+
リモートボリュームが手動で一時停止されています。レプリケーションを再開するには、リモートボリュームの一時停止を手動で解除する必要があります。

* * PausedMisconfigured *
+
ソースとターゲットがアクティブになるのを待っています。レプリケーションを再開するには手動での対応が必要です。

* * PausedQoS*
+
ターゲット QoS の受信 IO を維持できませんでした。レプリケーションは自動で再開されます。このメッセージは、ペアのソース側にのみ表示されます。

* * PausedSlowLink*
+
低速リンクが検出され、レプリケーションが停止しました。レプリケーションは自動で再開されます。このメッセージは、ペアのソース側にのみ表示されます。

* * PausedVolumeSizMismatch*
+
ターゲットボリュームのサイズがソースボリュームと同じではありません。

* * PausedXCopy *
+
ソースボリュームに対して scsi XCOPY コマンドを実行中です。このコマンドは、レプリケーションを再開する前に完了している必要があります。このメッセージは、ペアのソース側にのみ表示されます。

* * StoppedMisconfigured *
+
永続的な設定エラーが検出されました。リモートボリュームがパージされたかペアが解除されました。対処方法はありません。新しいペアリングを確立する必要があります。


