---
permalink: storage/reference_snapmirror_relationship_actions.html 
sidebar: sidebar 
keywords: element, ui, relationships, snapmirror, actions, configure 
summary: '関係は、データ保護タブの SnapMirror 関係ページで設定できます。ここでは、 [ アクション（ Actions ） ] アイコンのオプションについて説明します。' 
---
= SnapMirror 関係の操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
関係は、データ保護タブの SnapMirror 関係ページで設定できます。ここでは、 [ アクション（ Actions ） ] アイコンのオプションについて説明します。

* * 編集 * ：関係で使用するポリシーまたはスケジュールを編集します。
* * Delete * ： SnapMirror 関係を削除します。デスティネーションボリュームは削除されません。
* * Initialize * ：データの最初のベースライン転送を実行し、新しい関係を確立します。
* * Update * ：関係をオンデマンドで更新し、前回の更新以降に追加された新しいデータと Snapshot コピーをデスティネーションにレプリケートします。
* * 休止 * ：関係の更新を阻止します。
* * 再開 * ：休止されている関係を再開します。
* * Break * ：デスティネーションボリュームを読み書き可能にし、現在および将来のすべての転送を停止します。クライアントが元のソースボリュームを使用していないことを確認します。逆再同期処理を実行すると、元のソースボリュームは読み取り専用になります。
* * Resync * ：解除された関係を、解除前と同じ方向で再確立します。
* * 逆再同期 * ：逆方向の新しい関係を作成して初期化するために必要な手順を自動化します。この操作は、既存の関係が解除状態の場合にのみ実行できます。この処理で現在の関係が削除されることはありません。元のソースボリュームが最新の共通 Snapshot コピーにリバートされ、デスティネーションと再同期されます。前回成功した SnapMirror 更新以降に、元のソースボリュームに対して行われた変更は失われます。現在のデスティネーションボリュームに対して行われた変更や新しく書き込まれたデータがすべて、元のソースボリュームに送信されます。
* * 中止 * ：実行中の転送をキャンセルします。中止された関係に対して SnapMirror 更新が実行されると、前回の転送が、中止前に作成された最後の再開チェックポイントから続行されます。

