---
permalink: storage/reference_per_node_network_settings_details.html 
sidebar: sidebar 
keywords: network settings, per-node UI, storage node, ui 
summary: ストレージノードのネットワーク設定を変更して、新しいネットワーク属性を指定できます。 
---
= ネットワーク設定の詳細はノード UI から確認できます
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードのネットワーク設定を変更して、新しいネットワーク属性を指定できます。

ノードにログインすると、ストレージノードのネットワーク設定が * Network Settings * ページに表示されます (https://<node[] IP> ： 442/HCC / ノード / ネットワーク設定）。「 * Bond1G * （管理）」または「 * Bond10G * （ストレージ）」のいずれかの設定を選択できます。ストレージノードの状態が Available 、 Pending 、または Active の場合に変更可能な設定は次のとおりです。


NOTE: SolidFire エンタープライズ SDS クラスタを実行している場合、ノード UI のほとんどのネットワーク設定をノード導入後に変更することはできません。

* * メソッド *
+
インターフェイスの設定に使用する方法。有効な方法：

+
** loopback ： IPv4 ループバックインターフェイスを定義する場合に使用します。
** manual ：デフォルトの設定がないインターフェイスを定義する場合に使用します。
** dhcp ： DHCP 経由で IP アドレスを取得する場合に使用します。
** static ： IPv4 アドレスが静的に割り当てられたイーサネットインターフェイスを定義する場合に使用します。


* * リンク速度 *
+
仮想 NIC によってネゴシエートされた速度。

* * IPv4 アドレス *
+
eth0 ネットワークの IPv4 アドレス。

* * IPv4 サブネットマスク *
+
IPv4 ネットワークのアドレス分割。

* * IPv4 ゲートウェイアドレス *
+
ローカルネットワークの外部にパケットを送信するためのルータのネットワークアドレス。

* * IPv6 アドレス *
+
eth0 ネットワークの IPv6 アドレス。

* * IPv6 ゲートウェイアドレス *
+
ローカルネットワークの外部にパケットを送信するためのルータのネットワークアドレス。

* * MTU *
+
ネットワークプロトコルで送信可能な最大パケットサイズ。1500 以上にする必要があります。2 つ目のストレージ NIC を追加する場合は、値を 9000 にする必要があります。

* * DNS サーバ *
+
クラスタ通信に使用するネットワークインターフェイス。

* * 検索ドメイン *
+
システムで使用可能な追加の MAC アドレスを検索します。

* * ボンディング・モード *
+
には、次のいずれかのモードを指定できます。

+
** ActivePassive （デフォルト）
** ALB
** LACP


* * ステータス *
+
有効な値は次のとおり

+
** UpAndRunning のサービスです
** 下へ
** 上へ


* * 仮想ネットワークタグ *
+
仮想ネットワークの作成時に割り当てられたタグ。

* * ルート *
+
ルートが使用するように設定されている、関連付けられたインターフェイスを介した特定のホストまたはネットワークへのスタティックルート。


