---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: 'システムからは複数のタイプのイベントが報告されます。各イベントは、システムが完了した処理を表します。イベントには、日常的に発生するイベント、正常なイベント、または管理者による対応が必要なイベントがあります。[ イベントログ ] ページの [ イベントタイプ ] 列には、イベントが発生したシステムの部分が示されます。' 
---
= イベントタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムからは複数のタイプのイベントが報告されます。各イベントは、システムが完了した処理を表します。イベントには、日常的に発生するイベント、正常なイベント、または管理者による対応が必要なイベントがあります。[ イベントログ ] ページの [ イベントタイプ ] 列には、イベントが発生したシステムの部分が示されます。


NOTE: 読み取り専用の API コマンドはイベントログに記録されません。

イベントログに表示されるイベントのタイプは次のとおりです。

* * apiEvent *
+
ユーザが API または Web UI から開始した、設定を変更するイベント。

* *binAssignmentsEvent*
+
データビンの割り当てに関連するイベント。ビンは基本的にデータを保持するコンテナであり、クラスタ全体にマッピングされます。

* *binSyncEvent*
+
ブロックサービス間でのデータの再割り当てに関連するシステムイベント。

* * bsCheckEvent *
+
ブロックサービスチェックに関連するシステムイベント。

* * bsKillEvent *
+
ブロックサービスの終了に関連するシステムイベント。

* * bulkOpEvent *
+
バックアップ、リストア、 Snapshot 、クローンなど、ボリューム全体で実行される処理に関連するイベント。

* * cloneEvent *
+
ボリュームクローニングに関連するイベント。

* * clusterMasterEvent *
+
クラスタの初期化時、またはノードの追加や削除など、クラスタの構成の変更時に表示されるイベント。

* [[cssum_event]]* cSumEvent*
+
エンドツーエンドのチェックサム検証中にチェックサム不一致が検出された場合に関連するイベント。

+
チェックサムの不一致を検出したサービスは自動的に停止され、このイベントの生成後に再開されません。

* * DataEvent *
+
データの読み取りと書き込みに関連するイベント。

* * dbEvent *
+
クラスタ内のアンサンブルノードによって管理されているグローバルデータベースに関連するイベント。

* * driveEvent *
+
ドライブの処理に関連するイベント。

* * encryptionAtRestEvent*
+
クラスタでの暗号化プロセスに関連するイベント。

* * ensembleEvent*
+
アンサンブル内のノード数の増減に関連するイベント。

* * fibreChannelEvent *
+
ノードの設定と接続に関連するイベント。

* * gcEvent *
+
ブロックドライブ上のストレージを再利用するために 60 分ごとに実行されるプロセスに関連するイベント。このプロセスはガベージコレクションとも呼ばれます。

* * ieEvent *
+
内部システムエラー。

* * installEvent *
+
ソフトウェアの自動インストールイベント。保留状態のノードにソフトウェアが自動的にインストールされています。

* *iSCSIEvent*
+
システムでの iSCSI の問題に関連するイベント。

* * limitEvent*
+
アカウントまたはクラスタ内で許可されているボリュームまたは仮想ボリュームの最大数に近づいていることを示すイベント。

* * メンテナンスモードイベント *
+
ノードの無効化など、ノードのメンテナンスモードに関連するイベント。

* [[network_event]]* networkEvent *
+
各物理Network Interface Card（NIC；ネットワークインターフェイスカード）インターフェイスのネットワークエラーレポートに関連するイベント。

+
これらのイベントは、10分間のモニタリングインターバル中に、インターフェイスのエラーカウントがデフォルトのしきい値1000を超えるとトリガーされます。これらのイベントは、受信ミス、巡回冗長検査（CRC）エラー、長さエラー、オーバーランエラー、フレームエラーなどのネットワークエラーに適用されます。

* * platformHardwareEvent *
+
ハードウェアデバイスで検出された問題に関連するイベント。

* * remoteClusterEvent *
+
リモートクラスタペアリングに関連するイベント。

* * schedulerEvent *
+
スケジュールされた Snapshot に関連するイベント。

* * serviceEvent *
+
システムサービスのステータスに関連するイベント。

* * siceEvent *
+
メタデータドライブやボリュームの削除など、スライスサーバに関連するイベント。

+
スライスの再割り当てイベントには、ボリュームが割り当てられているサービスに関する情報を含む 3 種類の再割り当てイベントがあります。

+
** 反転：プライマリサービスを新しいプライマリサービスに変更します
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 移動：セカンダリサービスを新しいセカンダリサービスに変更します
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** pruning ：一連のサービスからボリュームを削除する
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* * snmpTrapEvent *
+
SNMP トラップに関連するイベント。

* * statEvent *
+
システム統計に関連するイベント。

* * tsEvent *
+
システム転送サービスに関連するイベント。

* * unexpectedException *
+
予期しないシステム例外に関連するイベント。

* * ureEvent*
+
ストレージデバイスからの読み取り中に発生した回復不能な読み取りエラーに関連するイベント。

* * vasaProviderEvent *
+
vSphere APIs for Storage Awareness （ VASA ） Provider に関連するイベント。


