---
permalink: storage/reference_monitor_volume_performance_details.html 
sidebar: sidebar 
keywords: volume performance 
summary: ボリュームのパフォーマンス統計は、 Element UI の Reporting タブの Volume Performance ページで確認できます。 
---
= ボリュームのパフォーマンスの詳細
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームのパフォーマンス統計は、 Element UI の Reporting タブの Volume Performance ページで確認できます。

表示される詳細情報は次のとおりです。

* *ID*
+
システムによって生成されたボリュームの ID 。

* * 名前 *
+
ボリュームの作成時に指定した名前。

* * アカウント *
+
ボリュームに割り当てられているアカウントの名前。

* * アクセスグループ *
+
ボリュームアクセスグループまたはボリュームが属するグループの名前。

* * ボリューム使用率 *
+
クライアントによるボリュームの使用率を示すパーセンテージ。

+
有効な値は次のとおり

+
** 0 ：クライアントはボリュームを使用していません
** 100 ：クライアントは最大値まで使用しています
** >100 ：クライアントはバースト値を使用しています


* * 合計 IOPS *
+
ボリュームに対して実行中の IOPS （読み取りおよび書き込み）の総数。

* * 読み取り IOPS *
+
ボリュームに対して実行中の読み取り IOPS の総数。

* * 書き込み IOPS *
+
ボリュームに対して実行中の書き込み IOPS の総数。

* * 合計スループット *
+
ボリュームに対して実行中のスループット（読み取りおよび書き込み）の総量。

* * 読み取りスループット *
+
ボリュームに対して実行中の読み取りスループットの総量。

* * 書き込みスループット *
+
ボリュームに対して実行中の書き込みスループットの総量。

* * 合計レイテンシ *
+
ボリュームに対する読み取り処理と書き込み処理が完了するまでの平均時間（マイクロ秒）。

* * 読み取り遅延 *
+
過去 500 ミリ秒の、ボリュームへの読み取り処理を完了するまでの平均時間（マイクロ秒）。

* * 書き込みレイテンシー *
+
過去 500 ミリ秒の、ボリュームへの書き込み処理を完了するまでの平均時間（マイクロ秒）。

* * キュー深度 *
+
ボリュームに対する未処理の読み取り処理と書き込み処理の数。

* * 平均 IO サイズ *
+
直近 500 ミリ秒の、ボリュームへの最新の I/O の平均サイズ（バイト）。


