---
permalink: storage/reference_per_node_cluster_settings_details.html 
sidebar: sidebar 
keywords: nodes, changing cluster settings, per-node UI 
summary: クラスタの設定およびノードのホスト名の変更後、ストレージノードのクラスタ設定を確認することができます。 
---
= ノード UI から取得したクラスタ設定の詳細
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタの設定およびノードのホスト名の変更後、ストレージノードのクラスタ設定を確認することができます。

ノード UI の「 * Cluster Settings * 」ページで、ストレージノードのクラスタ設定を次の表に示します (https://<node[] IP> ： 442/HCC / ノード / クラスタ設定）。


NOTE: SolidFire エンタープライズ SDS クラスタを実行している場合、ノード UI のほとんどのネットワーク設定をノード導入後に変更することはできません。

* * 役割 *
+
クラスタにおけるノードのロール。有効な値は次のとおり

+
** Storage ：ストレージノードまたは Fibre Channel ノード。
** Management ：管理ノード。


* * ホスト名 *
+
ノードの名前。

* * クラスタ *
+
クラスタの名前。

* * クラスタメンバーシップ *
+
ノードの状態。有効な値は次のとおり

+
** Available ：ノードにはクラスタ名が関連付けられておらず、まだクラスタに含まれていません。
** Pending ：設定済みで、指定されたクラスタに追加できるノードです。このノードにアクセスするための認証は必要ありません。
** PendingActive ：互換性のあるソフトウェアをノードにインストールしています。完了すると、ノードは Active 状態に移行します。
** Active ：クラスタに参加しているノードです。このノードを変更するには、認証が必要です。


* * バージョン *
+
ノードで実行されている Element ソフトウェアのバージョン。

* * アンサンブル *
+
データベースアンサンブルに参加しているノード。

* * ノード ID *
+
クラスタへの追加時にノードに割り当てられた ID 。

* * クラスタインターフェイス *
+
クラスタ通信に使用するネットワークインターフェイス。

* * 管理インターフェイス *
+
管理ネットワークインターフェイス。デフォルトは Bond1G ですが、 Bond10G も使用できます。

* * ストレージ・インターフェイス *
+
Bond10G を使用するストレージネットワークインターフェイス。

* * 暗号化対応 *
+
ノードでドライブ暗号化がサポートされているかどうか。


