---
permalink: storage/reference_data_manage_volumes_volume_details.html 
sidebar: sidebar 
keywords: volume, size of volume 
summary: 管理タブのボリュームページには、名前、アカウント、ボリュームに関連付けられているアクセスグループ、ボリュームのサイズなどのアクティブなボリュームに関する情報が表示されます。 
---
= ボリュームの詳細
:icons: font
:imagesdir: ../media/


[role="lead"]
管理タブのボリュームページには、名前、アカウント、ボリュームに関連付けられているアクセスグループ、ボリュームのサイズなどのアクティブなボリュームに関する情報が表示されます。

* *ID*
+
システムによって生成されたボリュームの ID 。

* * 名前 *
+
ボリュームの作成時に指定した名前。

* * アカウント *
+
ボリュームに割り当てられているアカウントの名前。

* * アクセスグループ *
+
ボリュームアクセスグループまたはボリュームが属するグループの名前。

* * アクセス *
+
ボリュームの作成時に割り当てられたアクセスのタイプ。有効な値は次のとおり

+
** Read/Write ：すべての読み取りと書き込みが許可されます。
** Read Only ：すべての読み取りアクティビティが許可されます。書き込みは許可されません。
** Locked ：管理者アクセスのみが許可されます。
** ReplicationTarget ：レプリケートされたボリュームペアのターゲットボリュームとして指定されています。


* * 使用済み *
+
ボリューム内の使用済みスペースの割合。

* * サイズ *
+
ボリュームの合計サイズ（ GB ）。

* * スナップショット *
+
ボリュームに対して作成された Snapshot の数。

* * QoS ポリシー *
+
ユーザが定義した QoS ポリシーの名前とリンク。

* * 最小 IOPS *
+
ボリュームに対して保証されている最小 IOPS 。

* * 最大 IOPS *
+
ボリュームに対して許可されている最大 IOPS 。

* * バースト IOPS *
+
ボリュームに対して短期間で許可されている最大 IOPS 。デフォルト値は 15 、 000 です。

* * 属性 *
+
API メソッドを使用してキーと値のペアとしてボリュームに割り当てられている属性。

* * 512e *
+
ボリュームで 512e が有効になっているかどうか。有効な値は次のとおり

+
** はい。
** いいえ


* * 上に作成されました
+
ボリュームが作成された日時。


