---
permalink: storage/task_replication_pair_cluster_using_pairing_key.html 
sidebar: sidebar 
keywords: remote replication, pairing key, pairing clusters 
summary: ローカルクラスタにはクラスタ管理者としてアクセスできるが、リモートクラスタにはアクセスできない場合は、ペアリングキーを使用してクラスタをペアリングします。ローカルクラスタで生成したペアリングキーをリモートサイトのクラスタ管理者に安全な方法で送信して接続を確立し、リアルタイムレプリケーション用にクラスタをペアリングします。 
---
= ペアリングキーを使用してクラスタをペアリングします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルクラスタにはクラスタ管理者としてアクセスできるが、リモートクラスタにはアクセスできない場合は、ペアリングキーを使用してクラスタをペアリングします。ローカルクラスタで生成したペアリングキーをリモートサイトのクラスタ管理者に安全な方法で送信して接続を確立し、リアルタイムレプリケーション用にクラスタをペアリングします。

. ローカルクラスタで、 * Data Protection * > * Cluster Pairs * を選択します。
. * クラスタのペアリング * をクリックします。
. Start Pairing * をクリックし、 * No * をクリックして、リモートクラスタにアクセスできないことを示します。
. [* キーの生成 * ] をクリックします。
+

NOTE: この操作により、ペアリング用のテキストキーが生成され、ローカルクラスタにクラスタペアが未設定の状態で作成されます。手順を完了しない場合は、クラスタペアを手動で削除する必要があります。

. クラスタペアリングキーをクリップボードにコピーします。
. このペアリングキーをリモートクラスタサイトのクラスタ管理者に渡します。
+

NOTE: クラスタペアリングキーには、リモートレプリケーション用にボリューム接続を許可するための MVIP のバージョン、ユーザ名、パスワード、およびデータベース情報が含まれています。このキーの取り扱いには十分に注意し、ユーザ名やパスワードが誤って外部に漏れたり不正に使用されたりしないように適切に管理してください。

+

IMPORTANT: ペアリングキーの文字はいっさい変更しないでください。キーが変更されると無効になります。

. リモートクラスタで、 * データ保護 * > * クラスタ・ペア * を選択します。
. * クラスタのペアリング * をクリックします。
. 完全ペアリング * をクリックし、ペアリングキー * フィールドにペアリングキーを入力します（貼り付けを推奨します）。
. [ 完全ペアリング ] をクリックします。




== 詳細については、こちらをご覧ください

* xref:task_replication_pair_cluster_using_mvip.adoc[MVIP を使用してクラスタをペアリング]
* https://www.youtube.com/watch?v=1ljHAd1byC8&feature=youtu.be["Pairing Clusters using a Cluster Pairing Key （ビデオ）"]

