---
permalink: storage/task-element-replication-initialize-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, initialize, replication, relationship 
summary: すべての関係タイプでは、初期化の際にベースライン転送が実行されます。ベースライン転送では、ソースボリュームのSnapshotコピーが作成され、そのコピーおよびコピーが参照するすべてのデータブロックがデスティネーションボリュームに転送されます。 
---
= レプリケーション関係を初期化する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての関係タイプで初期化を実行すると、_baseline transfer_：が実行され、ソースボリュームのSnapshotコピーが作成されて、そのコピーおよびコピーが参照するすべてのデータブロックがデスティネーションボリュームに転送されます。

.作業を開始する前に
* レプリケートするボリュームを含む Element ノードから ONTAP にアクセスできるようにしておく必要があります。
* Element ボリュームの SnapMirror レプリケーションを有効にしておく必要があります。
* ポリシータイプ「m mirror-vault」を使用する場合は、レプリケートするElement SnapshotコピーのSnapMirrorラベルを設定しておく必要があります。
+
[NOTE]
====
このタスクは、またはでのみ実行できますlink:concept_snapmirror_labels.html["ElementソフトウェアWeb UI"]link:../api/concept_element_api_snapshots_overview.html["API メソッド"]。

====


.このタスクについて
Elementのソースパスをの形式で指定する必要があり `<hostip:>/lun/<name>`ます。「LUN」は実際の文字列「LUN」、 `_name_` はElementボリュームの名前です。

初期化には時間がかかる場合があります。ベースライン転送はオフピークの時間帯に実行することを推奨します。

[NOTE]
====
ONTAP ソースから Element デスティネーションへの関係の初期化に何らかの理由で失敗した場合は、問題（無効な LUN 名など）を修正したあとも初期化が失敗します。回避策は次のとおりです。

. 関係を削除します。
. Element デスティネーションボリュームを削除します。
. 新しい Element デスティネーションボリュームを作成
. ONTAP ソースから Element デスティネーションボリュームへの新しい関係を作成して初期化します。


====
.ステップ
. レプリケーション関係を初期化します。
+
`snapmirror initialize -source-path <hostip:>/lun/<name> -destination-path <SVM:volume|cluster://SVM/volume>`

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、IPアドレス10.0.0.11のソースボリュームとの `svm_backup`デスティネーションボリューム `volA_dst`の間の関係を初期化し `0005`ます。

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

