---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: SolidFire システムは、ボリュームを使用してストレージをプロビジョニングします。ボリュームは、 iSCSI または Fibre Channel クライアントがネットワーク経由でアクセスするブロックデバイスです。 
---
= ボリュームを管理します
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire システムは、ボリュームを使用してストレージをプロビジョニングします。ボリュームは、 iSCSI または Fibre Channel クライアントがネットワーク経由でアクセスするブロックデバイスです。

管理タブのボリュームページでは、ノードのボリュームを作成、変更、クローニング、および削除できます。



== ボリュームを作成します

ボリュームを作成して、指定したアカウントに関連付けることができます。すべてのボリュームをアカウントに関連付ける必要があります。この関連付けにより、アカウントは、 iSCSI イニシエータ経由で CHAP クレデンシャルを使用してボリュームにアクセスできます。

作成中に、ボリュームの QoS 設定を指定できます。

. [* Management] > [* Volumes] を選択します。
. [ ボリュームの作成 ] をクリックします。
. [ 新しいボリュームの作成 * ] ダイアログボックスで、 * ボリューム名 * を入力します。
. ボリュームの合計サイズを入力します。
+

NOTE: デフォルトで選択されているボリュームサイズの単位は GB です。GB または GiB 単位のサイズを使用してボリュームを作成できます。

+
** 1GB=1 、 000 、 000 、 000 バイト
** 1GiB=1 、 073 、 741 、 824 バイトです


. ボリュームの * ブロックサイズ * を選択します。
. 「 * Account * 」ドロップダウン・リストをクリックし、ボリュームにアクセスできるアカウントを選択します。
+
アカウントが存在しない場合は、 [ アカウントの作成 ] リンクをクリックし、新しいアカウント名を入力して、 [ * 作成 ] をクリックします。アカウントが作成され、新しいボリュームに関連付けられます。

+

NOTE: アカウント数が 50 個を超える場合、リストは表示されません。名前の先頭部分を入力すると、オートコンプリート機能によって、候補が表示されます。

. サービス品質 * を設定するには、次のいずれかを実行します。
+
.. 「 * Policy 」で、既存の QoS ポリシーがある場合は選択できます。
.. カスタム設定 * で、 IOPS の最小値、最大値、バースト値をカスタマイズするか、デフォルトの QoS 値を使用します。
+
最大 IOPS またはバースト IOPS の値が 20 、 000 IOPS を超える場合、単一のボリュームでこのレベルの IOPS を実現するには、キュー深度を深くするか、複数のセッションが必要になる場合があります。



. [ ボリュームの作成 ] をクリックします。




== ボリュームの詳細を表示します

. [* Management] > [* Volumes] を選択します。
. 詳細を確認します。
+
** *ID* ：システムによって生成されたボリュームの ID 。
** * 名前 * ：ボリュームの作成時に指定した名前。
** * Account * ：ボリュームに割り当てられているアカウントの名前。
** * アクセスグループ * ：ボリュームが属するボリュームアクセスグループの名前。
** * アクセス * ：ボリュームの作成時に割り当てられたアクセスのタイプ。有効な値は次のとおり
+
*** Read/Write ：すべての読み取りと書き込みが許可されます。
*** Read Only ：すべての読み取りアクティビティが許可されます。書き込みは許可されません。
*** Locked ：管理者アクセスのみが許可されます。
*** ReplicationTarget ：レプリケートされたボリュームペアのターゲットボリュームとして指定されています。


** * used * ：ボリューム内の使用済みスペースの割合。
** * サイズ * ：ボリュームの合計サイズ（ GB ）。
** * Snapshots * ：ボリュームに対して作成された Snapshot の数。
** * QoS Policy * ：ユーザ定義の QoS ポリシーの名前とリンク。
** * Min IOPS * ：ボリュームに対して保証されている最小 IOPS 。
** * Max IOPS * ：ボリュームで許可されている最大 IOPS 。
** * Burst IOPS * ：ボリュームに対して短期間で許可されている最大 IOPS 。デフォルト値は 15 、 000 です。
** * Attributes * ： API メソッドを使用してキーと値のペアとしてボリュームに割り当てられている属性。
** * 512e * ：ボリュームで 512e が有効になっているかどうか。有効な値は次のとおり
+
*** はい。
*** いいえ


** * Created On * ：ボリュームが作成された日時。






== 個々のボリュームの詳細を表示します

個々のボリュームのパフォーマンス統計を表示できます。

. * Reporting * > * Volume Performance * を選択します。
. ボリュームリストで、ボリュームの操作アイコンをクリックします。
. [ * 詳細の表示 * ] をクリックします。
+
ボリュームの一般的な情報がページの下部に表示されます。

. ボリュームの詳細情報を表示するには、 * 詳細を表示 * をクリックします。
+
ボリュームの詳細情報とパフォーマンスグラフが表示されます。





== アクティブボリュームを編集します

QoS 値、ボリュームのサイズ、バイト値の算出単位など、ボリュームの属性を変更できます。レプリケーションで使用するため、またはボリュームへのアクセスを制限するために、アカウントアクセスを変更することもできます。

次の状況下でクラスタに十分なスペースがある場合は、ボリュームのサイズを変更できます。

* 正常な動作状態。
* ボリュームのエラーまたは障害が報告されている。
* ボリュームをクローニングしています。
* ボリュームの再同期中。


.手順
. [* Management] > [* Volumes] を選択します。
. [ * アクティブ * ] ウィンドウで、編集するボリュームの [ アクション ] アイコンをクリックします。
. [ 編集（ Edit ） ] をクリックします。
. * オプション： * ボリュームの合計サイズを変更します。
+
** ボリュームのサイズは、増やすことはできますが、減らすことはできません。1 回の処理でサイズ変更できるのは、 1 つのボリュームのみです。ガベージコレクションやソフトウェアのアップグレードを実行しても、サイズ変更処理は中断されません。
** レプリケーション用にボリュームサイズを調整する場合は、最初にレプリケーションターゲットとして割り当てられているボリュームのサイズを拡張する必要があります。次に、ソースボリュームのサイズを変更します。ターゲットボリュームのサイズは、ソースボリュームと同じかそれ以上のサイズにすることはできますが、ソースボリュームより小さくすることはできません。


+
デフォルトで選択されているボリュームサイズの単位は GB です。GB または GiB 単位のサイズを使用してボリュームを作成できます。

+
** 1GB=1 、 000 、 000 、 000 バイト
** 1GiB=1 、 073 、 741 、 824 バイトです


. * オプション： * 次のいずれかのアカウントアクセスレベルを選択します。
+
** 読み取り専用です
** 読み取り / 書き込み
** ロック済み
** レプリケーションターゲット


. * オプション： * ボリュームへのアクセスを許可するアカウントを選択します。
+
アカウントが存在しない場合は、 [ アカウントの作成 ] リンクをクリックし、新しいアカウント名を入力して、 [ * 作成 ] をクリックします。アカウントが作成され、ボリュームに関連付けられます。

+

NOTE: アカウント数が 50 個を超える場合、リストは表示されません。名前の先頭部分を入力すると、オートコンプリート機能によって、候補が表示されます。

. * オプション： * サービス品質 * での選択を変更するには、次のいずれかを実行します。
+
.. 「 * Policy 」で、既存の QoS ポリシーがある場合は選択できます。
.. カスタム設定 * で、 IOPS の最小値、最大値、バースト値をカスタマイズするか、デフォルトの QoS 値を使用します。
+

NOTE: ボリュームで QoS ポリシーを使用している場合は、カスタム QoS を設定して、ボリュームとの QoS ポリシーの所属を削除できます。カスタム QoS は、ボリュームの QoS 設定に対して QoS ポリシーの値を上書きして調整します。

+

TIP: IOPS の値は、 10 または 100 単位で増減する必要があります。入力値には有効な整数を指定する必要があります。

+

TIP: ボリュームのバースト値はできるだけ高くします。バースト値を非常に高く設定することで、たまに発生する大規模ブロックのシーケンシャルワークロードを迅速に処理できる一方で、平常時の IOPS は引き続き抑制することができます。



. [ 変更の保存 *] をクリックします。




== ボリュームを削除します

Element ストレージクラスタから 1 つ以上のボリュームを削除できます。

削除されたボリュームはすぐにパージされるわけではなく、約 8 時間は使用可能な状態のままです。この間にリストアしたボリュームはオンラインに戻り、 iSCSI 接続が再度確立されます。

Snapshot の作成に使用されたボリュームを削除すると、関連付けられている Snapshot は非アクティブになります。削除したソースボリュームがパージされると、関連する非アクティブな Snapshot もシステムから削除されます。


IMPORTANT: 管理サービスに関連付けられた永続ボリュームが作成され、インストールまたはアップグレード時に新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、ボリュームや関連付けられているアカウントを変更または削除しないでください。

.手順
. [* Management] > [* Volumes] を選択します。
. 単一のボリュームを削除するには、次の手順を実行します。
+
.. 削除するボリュームの操作アイコンをクリックします。
.. 表示されたメニューで、 * 削除 * をクリックします。
.. 操作を確定します。


+
ボリュームは、 [* Volumes （ボリューム） ] ページの [* Deleted （削除済み） ] 領域に移動します。

. 複数のボリュームを削除するには、次の手順を実行します。
+
.. ボリュームのリストで、削除するボリュームの横のボックスをオンにします。
.. [ 一括操作 * ] をクリックします。
.. 表示されたメニューで、 * 削除 * をクリックします。
.. 操作を確定します。
+
ボリュームが * Volumes （ボリューム） * ページの * Deleted （削除済み） * 領域に移動します。







== 削除したボリュームをリストアします

システムでは、削除したボリュームのうち、パージされていないボリュームをリストアできます。削除したボリュームは約 8 時間後に自動的にパージされます。パージ済みのボリュームはリストアできません。

. [* Management] > [* Volumes] を選択します。
. 削除されたボリュームのリストを表示するには、 * Deleted * タブをクリックします。
. リストアするボリュームの操作アイコンをクリックします。
. 表示されたメニューで、 * リストア * をクリックします。
. 操作を確定します。
+
ボリュームが * Active * ボリュームリストに配置され、ボリュームへの iSCSI 接続がリストアされます。





== ボリュームをパージする

パージしたボリュームは、システムから完全に削除されます。ボリューム内のデータはすべて失われます。

削除したボリュームは、 8 時間後に自動的にパージされます。ただし、スケジュールされている時刻より前にボリュームをパージすることもできます。

. [* Management] > [* Volumes] を選択します。
. [ 削除済み（ * Deleted ） ] ボタンをクリックします。
. 次の手順を実行して、単一のボリュームまたは複数のボリュームをパージします。
+
[cols="25,75"]
|===
| オプション | 手順 


 a| 
単一のボリュームをパージする
 a| 
.. パージするボリュームのアクションアイコンをクリックします。
.. [Purge] をクリックします。
.. 操作を確定します。




 a| 
複数のボリュームをパージする
 a| 
.. パージするボリュームを選択します。
.. [ 一括操作 * ] をクリックします。
.. 表示されたメニューで、「 * パージ * 」を選択します。
.. 操作を確定します。


|===




== ボリュームのクローンを作成します

単一のボリュームまたは複数のボリュームのクローンを作成して、データのポイントインタイムコピーを作成できます。ボリュームをクローニングすると、ボリュームの Snapshot が作成され、次にその Snapshot が参照しているデータのコピーが作成されます。これは非同期のプロセスであり、クローニングするボリュームのサイズおよび現在のクラスタの負荷によって所要時間が異なります。

クラスタでは、ボリュームあたり一度に実行できるクローン要求は最大 2 つ、アクティブなボリュームのクローン処理は最大 8 件までサポートされます。これらの制限を超える要求はキューに登録され、あとで処理されます。


NOTE: オペレーティングシステムによって、クローニングされたボリュームの処理方法が異なります。VMware ESXi は、クローンボリュームをボリュームコピーまたは Snapshot ボリュームとして扱います。新しいデータストアの作成に使用できるデバイスがボリュームになります。クローンボリュームのマウントと Snapshot LUN の処理の詳細については、 VMware のドキュメントを参照してください https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["VMFS データストアのコピーをマウントしています"] および。


IMPORTANT: 小さいサイズにクローニングすることによってクローンボリュームのサイズを切り詰める場合は、小さいボリュームに収まるように事前にパーティションを準備してください。

.手順
. [* Management] > [* Volumes] を選択します。
. 単一のボリュームをクローニングするには、次の手順を実行します。
+
.. アクティブ * ページのボリュームのリストで、クローニングするボリュームのアクションアイコンをクリックします。
.. 表示されたメニューで、 * Clone * をクリックします。
.. Clone Volume * （ * クローンボリューム）ウィンドウで、新規にクローンされたボリュームのボリューム名を入力します。
.. 体積サイズ * スピンボックスとリストを使用して、体積のサイズと測定値を選択します。
+

NOTE: デフォルトで選択されているボリュームサイズの単位は GB です。GB または GiB 単位のサイズを使用してボリュームを作成できます。

+
*** 1GB=1 、 000 、 000 、 000 バイト
*** 1GiB=1 、 073 、 741 、 824 バイトです


.. 新しいクローンボリュームのアクセスのタイプを選択します。
.. 新しいクローンボリュームに関連付けるアカウントを * Account * リストから選択します。
+

NOTE: この手順の実行中にアカウントを作成するには、 [ アカウントの作成 ] リンクをクリックし、アカウント名を入力して、 [ * 作成 ] をクリックします。アカウントを作成すると、自動的にアカウントが *Account* リストに追加されます。



. 複数のボリュームをクローニングするには、次の手順を実行します。
+
.. アクティブ * ページのボリュームリストで、クローニングするボリュームの横のボックスをオンにします。
.. [ 一括操作 * ] をクリックします。
.. 表示されたメニューで、 * Clone * を選択します。
.. [* Clone Multiple Volumes] ダイアログ・ボックスで '[* New Volume Name Prefix*] フィールドにクローン・ボリュームのプレフィックスを入力します
.. クローンボリュームに関連付けるアカウントを * Account * リストから選択します。
.. クローンボリュームのアクセスのタイプを選択します。


. [ クローニングの開始 ] をクリックします。
+

NOTE: クローンのボリュームサイズを拡張すると、末尾に空きスペースが追加された新しいボリュームが作成されます。ボリュームの使用方法によっては、新しい空きスペースを使用するために、空きスペースでパーティションの拡張または新しいパーティションの作成が必要になる場合があります。





== を参照してください。

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

