---
permalink: storage/task_replication_pair_volumes_using_a_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, replication 
summary: リモートクラスタのクラスタ管理者のクレデンシャルがない場合は、ペアリングキーを使用してボリュームをリモートクラスタの別のボリュームとペアリングできます。 
---
= ペアリングキーを使用してボリュームをペアリングします
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートクラスタのクラスタ管理者のクレデンシャルがない場合は、ペアリングキーを使用してボリュームをリモートクラスタの別のボリュームとペアリングできます。

.必要なもの
* 該当するボリュームを含むクラスタがペアリングされていることを確認します。
* ペアリングに使用するボリュームがリモートクラスタにあることを確認します。
+

NOTE: ペアリングプロセスの完了後に、レプリケーションのソースとターゲットを割り当てることができます。ボリュームペアのどちらのボリュームをレプリケーションのソースまたはターゲットにしてもかまいません。データが格納されておらず、かつサイズ、ボリュームのブロックサイズ設定（ 512e または 4k ）、 QoS 設定などの特性がソースボリュームとまったく同じターゲットボリュームを作成してください。レプリケーションターゲットとして既存のボリュームを割り当てると、そのボリュームのデータは上書きされます。ターゲットボリュームのサイズは、ソースボリュームと同じかそれ以上のサイズにすることはできますが、ソースボリュームより小さくすることはできません。



.手順
. [* Management] > [* Volumes] を選択します。
. ペアリングするボリュームの * Actions * アイコンをクリックします。
. [ * Pair * ] をクリックします。
. * ペアボリューム * （ Pair Volume * ）ダイアログボックスで、 * ペアリング開始 * （ Start Pairing * ）を選択します。
. リモートクラスタにアクセスできない場合は、「 * i do not * 」を選択します。
. リストから * レプリケーションモード * を選択します。
+
** * Real-time （ Asynchronous ） * ：書き込みはソースクラスタでコミットされたあとにクライアントに通知されます。
** * Real-time （ Synchronous ） * ：書き込みはソースクラスタとターゲットクラスタの両方でコミットされたあとにクライアントに通知されます。
** * Snapshot のみ * ：ソースクラスタで作成された Snapshot のみがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。


. [* キーの生成 * ] をクリックします。
+

NOTE: この操作により、ペアリング用のテキストキーが生成され、ローカルクラスタにボリュームペアが未設定の状態で作成されます。手順を完了しない場合は、ボリュームペアを手動で削除する必要があります。

. ペアリングキーをクリップボードにコピーします。
. このペアリングキーをリモートクラスタサイトのクラスタ管理者に渡します。
+

NOTE: ボリュームペアリングキーの取り扱いには十分に注意し、誤って外部に漏れたり不正に使用されたりしないように適切に管理してください。

+

IMPORTANT: ペアリングキーの文字はいっさい変更しないでください。キーが変更されると無効になります。

. リモートクラスタの Element UI で、 * Management * > * Volumes * を選択します。
. ペアリングするボリュームの操作アイコンをクリックします。
. [ * Pair * ] をクリックします。
. * ペアボリューム * （ Pair Volume * ）ダイアログボックスで、 * 完全ペアリング * （ Complete Pairing * ）を選択します。
. もう一方のクラスタのペアリングキーを * ペアリングキー * ボックスに貼り付けます。
. [ 完全ペアリング ] をクリックします。
+
ペアリング操作を確定すると、 2 つのクラスタでペアリング対象のボリュームを接続するプロセスが開始されます。ペアリング処理中に、 * Volume Pairs * ウィンドウの * Volume Status * 列にメッセージが表示されます。ソースとターゲットが割り当てられるまで、ボリュームペアには「 PausedMisconfigured 」と表示されます。

+
ペアリングが完了したら、ボリュームの表を更新して、ペアリングされているボリュームの * Actions * リストから * Pair * オプションを削除することを推奨します。テーブルを更新しない場合は、 * Pair * オプションは選択可能なままになります。もう一度「 * Pair * 」オプションを選択すると、新しいタブが開き、ボリュームがすでにペアリングされているため、「 Element UI 」ページの「 * Pair Volume * 」ウィンドウに「 SartVolumePairing Failed: xVolumeAlreadyPaired 」というエラーメッセージが表示されます。





== 詳細については、こちらをご覧ください

* xref:reference_replication_volume_pairing_messages.adoc[ボリュームペアリングに関するメッセージ]
* xref:reference_replication_volume_pairing_warnings.adoc[ボリュームペアリングに関する警告]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアリングされたボリュームにレプリケーションのソースとターゲットを割り当てます]

