---
permalink: storage/task_data_protection_clone_multiple_volumes.html 
sidebar: sidebar 
keywords: multiple volumes, clone, create 
summary: 複数のボリュームのクローンを一度に作成して、ボリュームグループ上のデータのポイントインタイムコピーを作成できます。 
---
= 複数のボリュームのクローンを作成
:icons: font
:imagesdir: ../media/


[role="lead"]
複数のボリュームのクローンを一度に作成して、ボリュームグループ上のデータのポイントインタイムコピーを作成できます。

ボリュームをクローニングすると、そのボリュームの Snapshot が作成され、 Snapshot 内のデータから新しいボリュームが作成されます。新しいボリュームクローンは、マウントして書き込むことができます。複数のボリュームのクローニングは非同期のプロセスであり、クローニングするボリュームのサイズと数によって所要時間が異なります。

クローニング処理が完了するまでの時間は、ボリュームサイズおよびクラスタの現在の負荷によって異なります。

.手順
. [* 管理 *>* ボリューム *] をクリックします。
. [ アクティブ *] タブをクリックします。
. チェックボックスを使用して複数のボリュームを選択し、ボリュームグループを作成します。
. [ 一括操作 * ] をクリックします。
. 表示されたメニューで、 * Clone * をクリックします。
. [* Clone Multiple Volumes] ダイアログ・ボックスで ' 新しいボリューム名の接頭辞 * を入力します
+
このプレフィックスは、グループ内のすべてのボリュームに適用されます。

. * オプション： * クローンを割り当てる別のアカウントを選択します。
+
アカウントを選択しない場合、新しいボリュームは現在のボリュームアカウントに割り当てられます。

. * オプション：クローン内のボリュームに適用する別のアクセス方法を選択します。
+
アクセス方法を選択しない場合は、現在のボリュームアクセス方法が使用されます。

. [ クローニングの開始 ] をクリックします。

