---
permalink: storage/task_replication_pair_volumes.html 
sidebar: sidebar 
keywords: volume pairings, replication, cluster, cluster pair 
summary: クラスタペアのクラスタ間の接続を確立したら、一方のクラスタのボリュームをもう一方のクラスタのボリュームとペアリングできます。ボリュームペアリング関係を確立するときは、どちらのボリュームをレプリケーションターゲットにするかを指定する必要があります。 
---
= ボリュームをペアリング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタペアのクラスタ間の接続を確立したら、一方のクラスタのボリュームをもう一方のクラスタのボリュームとペアリングできます。ボリュームペアリング関係を確立するときは、どちらのボリュームをレプリケーションターゲットにするかを指定する必要があります。

接続されたクラスタペアの別々のストレージクラスタに格納されている 2 つのボリュームをリアルタイムレプリケーション用にペアリングできます。2 つのクラスタをペアリングしたあと、一方のクラスタのアクティブなボリュームをもう一方のクラスタに継続的にレプリケートするように設定することで継続的なデータ保護（ CDP ）を実現できます。どちらかのボリュームをレプリケーションのソースまたはターゲットとして割り当てることもできます。

ボリュームは常に 1 対 1 でペアリングします。別のクラスタのあるボリュームとペアリングしたボリュームをさらに他のボリュームとペアリングすることはできません。

.必要なもの
* クラスタペアのクラスタ間の接続を確立しておきます。
* ペアリングするクラスタの一方または両方に対するクラスタ管理者権限が必要です。


.手順
. xref:task_replication_create_a_target_volume_with_read_write_access.adoc[読み取りまたは書き込みアクセスが可能なターゲットボリュームを作成します]
. xref:task_replication_pair_volumes_using_volume_id_or_pairing_key.adoc[ボリューム ID またはペアリングキーを使用してボリュームをペアリングします]
. xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアリングされたボリュームにレプリケーションのソースとターゲットを割り当てます]

