---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: リモートクラスタのクラスタ管理者のクレデンシャルがあれば、ボリュームをリモートクラスタの別のボリュームとペアリングできます。 
---
= ボリューム ID を使用してボリュームをペアリング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームをペアにする両方のクラスターに対するクラスター管理者アクセス権を持っている場合は、ボリュームをリモート クラスター上の別のボリュームとペアにすることができます。このメソッドは、リモート クラスター上のボリュームのボリューム ID を使用して接続を開始します。

.必要なもの
* 該当するボリュームを含むクラスタがペアリングされていることを確認します。
* リモートクラスタに新しいボリュームを作成しておきます。
+

NOTE: ペアリングプロセスの完了後に、レプリケーションのソースとターゲットを割り当てることができます。ボリュームペアのどちらのボリュームをレプリケーションのソースまたはターゲットにしてもかまいません。データが格納されておらず、かつサイズ、ボリュームのブロックサイズ設定（ 512e または 4k ）、 QoS 設定などの特性がソースボリュームとまったく同じターゲットボリュームを作成してください。レプリケーションターゲットとして既存のボリュームを割り当てると、そのボリュームのデータは上書きされます。ターゲットボリュームのサイズは、ソースボリュームと同じかそれ以上のサイズにすることはできますが、ソースボリュームより小さくすることはできません。

* ターゲットのボリューム ID を確認します。


.手順
. [* Management] > [* Volumes] を選択します。
. ペアリングするボリュームの * Actions * アイコンをクリックします。
. [ * Pair * ] をクリックします。
. * ペアボリューム * （ Pair Volume * ）ダイアログボックスで、 * ペアリング開始 * （ Start Pairing * ）を選択します。
. リモートクラスタへのアクセス権を持っていることを示す場合は、「 * i do * 」を選択します。
. リストから * レプリケーションモード * を選択します。
+
** * Real-time （ Asynchronous ） * ：書き込みはソースクラスタでコミットされたあとにクライアントに通知されます。
** * Real-time （ Synchronous ） * ：書き込みはソースクラスタとターゲットクラスタの両方でコミットされたあとにクライアントに通知されます。
** * Snapshot のみ * ：ソースクラスタで作成された Snapshot のみがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。


. リストからリモートクラスタを選択します。
. リモートボリュームの ID を選択します。
. [ ペアリングの開始 ] をクリックします。
+
Web ブラウザのタブが開き、リモートクラスタの Element UI に接続します。クラスタ管理者のクレデンシャルを使用してリモートクラスタにログオンするよう要求される場合があります。

. リモートクラスタの Element UI で、「 * 完全ペアリング * 」を選択します。
. 「 * ボリュームペアリングの確認」で詳細を確認します。
. [ 完全ペアリング ] をクリックします。
+
ペアリング操作を確定すると、 2 つのクラスタでペアリング対象のボリュームを接続するプロセスが開始されます。ペアリング処理中に、 * Volume Pairs * ウィンドウの * Volume Status * 列にメッセージが表示されます。ソースとターゲットが割り当てられるまで、ボリュームペアには「 PausedMisconfigured 」と表示されます。

+
ペアリングが完了したら、ボリュームの表を更新して、ペアリングされているボリュームの * Actions * リストから * Pair * オプションを削除することを推奨します。テーブルを更新しない場合は、 * Pair * オプションは選択可能なままになります。もう一度「 * Pair * 」オプションを選択すると、新しいタブが開き、ボリュームがすでにペアリングされているため、「 Element UI 」ページの「 * Pair Volume * 」ウィンドウに「 SartVolumePairing Failed: xVolumeAlreadyPaired 」というエラーメッセージが表示されます。





== 詳細については、こちらをご覧ください

* xref:reference_replication_volume_pairing_messages.adoc[ボリュームペアリングに関するメッセージ]
* xref:reference_replication_volume_pairing_warnings.adoc[ボリュームペアリングに関する警告]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアリングされたボリュームにレプリケーションのソースとターゲットを割り当てます]

