---
permalink: storage/task_snapmirror_perform_failover_from_element_cluster.html 
sidebar: sidebar 
keywords: element, ui, failover, cluster, perform a failover, snapmirror 
summary: Element クラスタからフェイルオーバーを実行して、デスティネーションボリュームを読み書き可能にし、デスティネーション側のホストがアクセスできるようにすることができます。Element クラスタからフェイルオーバーを実行する前に、 SnapMirror 関係を解除する必要があります。 
---
= Element クラスタからフェイルオーバーを実行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element クラスタからフェイルオーバーを実行して、デスティネーションボリュームを読み書き可能にし、デスティネーション側のホストがアクセスできるようにすることができます。Element クラスタからフェイルオーバーを実行する前に、 SnapMirror 関係を解除する必要があります。

NetApp Element UI を使用してフェイルオーバーを実行します。Element UI 問題を使用できない場合は、 ONTAP System Manager または ONTAP CLI を使用して、関係を解除するコマンドを実行することもできます。

.必要なもの
* SnapMirror 関係が存在し、デスティネーションボリュームに有効な Snapshot が 1 つ以上あることが必要です。
* プライマリサイトでの計画外停止または計画的停止のために、デスティネーションボリュームへのフェイルオーバーが必要な状況にあります。


.手順
. Element UI で、 * Data Protection * > * SnapMirror Relationships * をクリックします。
. フェイルオーバーするソースボリュームとの関係を探します。
. [ * アクション * （ * Actions * ） ] アイコンをクリックする。
. [ * Break * ] をクリックします。
. 操作を確定します。
+
デスティネーションクラスタのボリュームで読み取り / 書き込みアクセスが可能になり、アプリケーションホストにマウントして本番環境のワークロードを再開できるようになります。この操作によって、 SnapMirror レプリケーションがすべて停止します。関係の状態は「 Broken-off 」になります。


