---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: カスタムの保護ドメインを設定すると、クラスタの耐障害性を高めることができます。 
---
= カスタムの保護ドメインを設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードが 3 つ以上含まれる Element クラスタでは、ノードごとにカスタムの保護ドメインを設定できます。カスタムの保護ドメインを設定する場合、クラスタ内のすべてのノードを 1 つのドメインに割り当てる必要があります。


TIP: 保護ドメインを割り当てると、ノード間のデータ同期が開始され、データの同期が完了するまで一部のクラスタ処理を使用できなくなります。クラスタにカスタムの保護ドメインを設定したあとで、新しいストレージノードを追加するときは、そのノードに保護ドメインを割り当ててデータの同期を完了するまで、新しいノードにドライブを追加することはできません。にアクセスします link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["保護ドメインのドキュメント"] 保護ドメインの詳細については、を参照してください。


NOTE: カスタム保護ドメインスキームをクラスタに使用するには、各シャーシ内のすべてのストレージノードを同じカスタム保護ドメインに割り当てる必要があります。そのためには、必要な数のカスタム保護ドメインを作成する必要があります（カスタム保護ドメインスキームの最小数は 3 ドメインです）。ベストプラクティスとして、ドメインごとに同数のノードを設定し、特定のドメインに割り当てられた各ノードのタイプが同じであることを確認することを推奨します。

.手順
. [* クラスタ *>* ノード *] をクリックします。
. ［ 保護ドメインの設定 ］ をクリックします。
+
[ カスタム保護ドメインの設定 *] ウィンドウには、現在構成されている保護ドメイン ( 存在する場合 ) および個々のノードに対する保護ドメインの割り当てが表示されます。

. 新しいカスタム保護ドメインの名前を入力し、 * 作成 * をクリックします。
+
作成する必要があるすべての新しい保護ドメインについて、この手順を繰り返します。

. [ ノードの割り当て * ] リストの各ノードについて、 [ 保護ドメイン * ] 列のドロップダウンをクリックし、そのノードに割り当てる保護ドメインを選択します。
+

CAUTION: 変更を適用する前に、ノードとシャーシのレイアウト、設定したカスタムの保護ドメインスキーム、およびデータ保護に対するスキームの影響を理解しておく必要があります。Protection Domain スキームを適用して、すぐに変更を加える必要がある場合は、設定が適用された後に行われるデータ同期のために、変更が必要になるまでしばらく時間がかかることがあります。

. ［ 保護ドメインの設定 ］ をクリックします。


クラスタのサイズによっては、ドメイン間のデータ同期に時間がかかることがあります。データの同期が完了すると、カスタムの保護ドメインの割り当てを * Cluster * > * Nodes * ページで確認できます。 Element Web UI ダッシュボードの * Custom Protection Domain Health * ペインには、クラスタの保護ステータスが表示されます。

カスタムの Protection Domain 構成を適用した後に表示されるエラーには、次のようなものがあります。

|===


| エラー | 説明 | 解決策： 


| SetProtectionDomainLayout に失敗しました : ProtectionDomainLayout は、 NodeID {9} を使用できなくなります。デフォルト名とデフォルト以外の名前の両方を一緒に使用することはできません。 | ノードに保護ドメインが割り当てられていません。 | ノードに保護ドメインを割り当てます。 


| SetProtectionDomainLayout に失敗しました : 保護ドメインタイプ 'custom' スプリット保護ドメインタイプ 'chassis' 。 | マルチノードシャーシのノードには、シャーシ内の他のノードとは異なる保護ドメインが割り当てられます。 | シャーシ内のすべてのノードに同じ保護ドメインが割り当てられていることを確認します。 
|===


== 詳細については、こちらをご覧ください

link:concept_intro_custom_protection_domains.html["カスタムの保護ドメイン"^]

