---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: NetApp Element UIを使用して、元のソースボリュームを再同期し、フェイルバックを実行できます。このセクションでは、元のソースボリュームが失われ、元のクラスタはそのまま維持されている環境シナリオを示します。新しいクラスタにリストアする方法については、ネットアップサポートサイトのドキュメントを参照してください。 
---
= ソースボリュームが存在しない場合にフェイルバックを実行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element UIを使用して、元のソースボリュームを再同期し、フェイルバックを実行できます。このセクションでは、元のソースボリュームが失われ、元のクラスタはそのまま維持されている環境シナリオを示します。新しいクラスタにリストアする方法については、ネットアップサポートサイトのドキュメントを参照してください。

.必要なもの
* Element ボリュームと ONTAP ボリュームの間で、レプリケーション関係の状態が「 Broken-off 」になっている必要があります。
* Element ボリュームが失われてリカバリ不可能であることが必要です。
* 元のボリューム名が「 NOT FOUND 」と表示される必要があります。


.手順
. Element UI で、フェイルオーバーを実行するために解除する関係を探します。
+
* ベストプラクティス： * 関係が「 Broken-off 」の SnapMirror ポリシーおよびスケジュールの詳細をメモしてください。この情報は、関係を再作成する際に必要となります。

. [ アクション * （ Actions * ） ] アイコンをクリックし、 [ 逆再同期（ Reverse Resync ） ] をクリックする。
. 操作を確定します。
+

NOTE: 逆再同期（ Reverse Resync ）処理では、元のソースボリュームとデスティネーションボリュームの役割が逆転した新しい関係が作成されます（元の関係は残されるので、 2 つの関係が存在することになります）。元のボリュームがすでに存在しないため、元のソースボリュームと同じ名前とサイズの新しいボリュームが Element に作成されます。新しいボリュームには、 sm-recovery というデフォルトの QoS ポリシーが割り当てられて、 sm-recovery というデフォルトのアカウントに関連付けられます。削除された元のソースボリュームを置き換えるために SnapMirror で作成されるすべてのボリュームについては、アカウントと QoS ポリシーを手動で編集する必要があります。

+
逆再同期処理の一環として、最新の Snapshot のデータが新しいボリュームに転送されます。デスティネーション側のアクティブボリュームには引き続きアクセスしてデータを書き込むことができますが、あとで元のプライマリ関係を復元する前に、アクティブボリュームとすべてのホストとの接続を切断し、 SnapMirror 更新を実行する必要があります。逆再同期が完了し、デスティネーション側のボリュームにアクティブなセッションが接続されておらず、かつ元のプライマリボリュームに最新のデータがある状態になったら、次の手順に進んでフェイルバックを完了し、元のプライマリボリュームを再びアクティブ化します。

. 逆再同期（ Reverse Resync ）処理中に作成された逆の関係の * アクション * （ * Actions * ）アイコンをクリックし、 * ブレーク * （ * Break * ）をクリックします。
. ソースボリュームが存在しない元の関係の * アクション * アイコンをクリックし、 * 削除 * をクリックします。
. 手順 4 で解除した逆の関係の * アクション * アイコンをクリックし、 * 逆再同期 * をクリックします。
. これにより、ソースとデスティネーションが逆転し、ソースボリュームとデスティネーションボリュームが元の関係と同じである関係が作成されます。
. [ * アクション * （ Actions * ） ] アイコンと [ * 編集 * （ Edit * ） ] をクリックして、この関係を元の QoS ポリシーとメモしたスケジュール設定で更新します。
. これで、手順 6 で逆再同期した逆の関係を削除できるようになります。




== 詳細については、こちらをご覧ください

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror フェイルバックのシナリオ]
