---
permalink: storage/task_data_protection_clone_multiple_volumes_from_a_group_snapshot.html 
sidebar: sidebar 
keywords: multiple volumes, group snapshot, clone, create, data protection 
summary: ボリュームのグループをポイントインタイムのグループ Snapshot からクローニングできます。この処理を実行するにはボリュームのグループ Snapshot が必要です。このグループ Snapshot を基にボリュームが作成されます。作成したボリュームは、システム内の他のボリュームと同様に使用できます。 
---
= グループ Snapshot から複数のボリュームのクローニング
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームのグループをポイントインタイムのグループ Snapshot からクローニングできます。この処理を実行するにはボリュームのグループ Snapshot が必要です。このグループ Snapshot を基にボリュームが作成されます。作成したボリュームは、システム内の他のボリュームと同様に使用できます。

クローニング処理が完了するまでの時間は、ボリュームサイズおよびクラスタの現在の負荷によって異なります。

. [ * データ保護 *>* グループスナップショット * ] をクリックします。
. ボリュームのクローンに使用するグループ Snapshot の操作アイコンをクリックします。
. 表示されたメニューで、 * Clone Volumes from Group Snapshot * （グループ Snapshot からのボリュームのクローン）を選択します。
. [ グループ Snapshot からのボリュームのクローン * ] ダイアログ・ボックスで ' 新しいボリューム名接頭辞 * を入力します
+
このプレフィックスは、グループ Snapshot から作成されるすべてのボリュームに適用されます。

. * オプション： * クローンを割り当てる別のアカウントを選択します。
+
アカウントを選択しない場合、新しいボリュームは現在のボリュームアカウントに割り当てられます。

. * オプション：クローン内のボリュームに適用する別のアクセス方法を選択します。
+
アクセス方法を選択しない場合は、現在のボリュームアクセス方法が使用されます。

. [ クローニングの開始 ] をクリックします。

