---
permalink: storage/task_system_manage_nodes_view_individual_node_details.html 
sidebar: sidebar 
keywords: nodes, view, details, vlan, mip, cip, sip, virtual id 
summary: 個々のノードの詳細を確認できます。サービスタグやドライブの詳細のほか、利用率やドライブの統計のグラフも参照できます。クラスタタブのノードページには、各ノードのソフトウェアバージョンを表示できるバージョン列があります。 
---
= ノードの詳細を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
個々のノードの詳細を確認できます。サービスタグやドライブの詳細のほか、利用率やドライブの統計のグラフも参照できます。クラスタタブのノードページには、各ノードのソフトウェアバージョンを表示できるバージョン列があります。

.手順
. [* クラスタ *>* ノード *] をクリックします。
. 特定のノードの詳細を表示するには、ノードの * Actions * アイコンをクリックします。
. [ * 詳細の表示 * ] をクリックします。
. ノードの詳細を確認します。
+
** * Node ID * ：システムによって生成されたノードの ID 。
** * Node Name * ：ノードのホスト名。
** * Node Role * ：クラスタ内でのノードのロール。有効な値は次のとおり
+
*** Cluster Master ：クラスタ全体の管理タスクを実行し、 MVIP と SVIP を含むノード。
*** Ensemble Node ：クラスタに参加するノード。クラスタのサイズに応じて、 3 つまたは 5 つのアンサンブルノードがあります。
*** Fibre Channel ：クラスタ内のノード。


** * Node Type * ：ノードのモデルタイプ。
** * Active Drives * ：ノード内のアクティブドライブの数。
** * Node Utilization *：nodeHeatに基づくノード利用率。表示される値は、recentPrimaryTotalHeatにパーセンテージで表示されます。Element 12.8以降で使用できます。
** * Management IP * ： 1GbE または 10GbE ネットワークの管理タスク用にノードに割り当てられた管理 IP （ MIP ）アドレス。
** * Cluster IP * ：ノードに割り当てられたクラスタ IP （ CIP ）アドレス。同じクラスタ内のノード間の通信に使用されます。
** * Storage IP * ：ノードに割り当てられたストレージ IP （ SIP ）アドレス。 iSCSI ネットワークの検出およびすべてのデータネットワークトラフィックに使用されます。
** * 管理 VLAN ID * ：管理ローカルエリアネットワークの仮想 ID 。
** * ストレージ VLAN ID * ：ストレージローカルエリアネットワークの仮想 ID 。
** * Version * ：各ノードで実行されているソフトウェアのバージョン。
** * レプリケーションポート * ：リモートレプリケーションにノードで使用されるポート。
** * Service Tag * ：ノードに割り当てられた一意のサービスタグ番号。
** * Custom Protection Domain *：ノードに割り当てられたカスタムの保護ドメイン。



