---
permalink: storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html 
sidebar: sidebar 
keywords: volume pairings, paired volumes, replication source, assign 
summary: ボリュームをペアリングしたら、ソースボリュームとそのレプリケーションターゲットボリュームを割り当てる必要があります。ボリュームペアのどちらのボリュームをレプリケーションのソースまたはターゲットにしてもかまいません。この手順を使用して、ソースボリュームが使用できなくなったときに、ソースボリュームに送信されたデータをリモートターゲットボリュームにリダイレクトすることもできます。 
---
= ペアリングされたボリュームにレプリケーションのソースとターゲットを割り当てます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームをペアリングしたら、ソースボリュームとそのレプリケーションターゲットボリュームを割り当てる必要があります。ボリュームペアのどちらのボリュームをレプリケーションのソースまたはターゲットにしてもかまいません。この手順を使用して、ソースボリュームが使用できなくなったときに、ソースボリュームに送信されたデータをリモートターゲットボリュームにリダイレクトすることもできます。

.必要なもの
ソースボリュームとターゲットボリュームを含むクラスタへのアクセス権が必要です。

.手順
. ソースボリュームを準備します。
+
.. ソースとして割り当てるボリュームを含むクラスタから、 * Management * > * Volumes * を選択します。
.. ソースとして割り当てるボリュームの * アクション * アイコンをクリックし、 * 編集 * をクリックします。
.. [*Access] ドロップダウン・リストで、 [*Read/Write *] を選択します。
+

IMPORTANT: ソースとターゲットの割り当てを逆にしている場合、原因新しいレプリケーションターゲットが割り当てられるまでボリュームペアには PausedMisconfigured というメッセージが表示されます

+
アクセスを変更すると、ボリュームレプリケーションが一時停止し、データの転送が中止されます。両方のサイトでこれらの変更を調整したことを確認してください。

.. [ 変更の保存 *] をクリックします。


. ターゲットボリュームを準備します。
+
.. ターゲットとして割り当てるボリュームを含むクラスタから、 * Management * > * Volumes * を選択します。
.. ターゲットとして割り当てるボリュームのアクションアイコンをクリックし、 * 編集 * をクリックします。
.. [*Access*] ドロップダウン・リストで '[*Replication Target*] を選択します
+

IMPORTANT: レプリケーションターゲットとして既存のボリュームを割り当てると、そのボリュームのデータは上書きされます。新しいターゲットボリュームは、データが格納されておらず、かつサイズ、 512e 、 QoS などの特性がソースボリュームとまったく同じであることが必要です。ターゲットボリュームのサイズは、ソースボリュームと同じかそれ以上のサイズにすることはできますが、ソースボリュームより小さくすることはできません。

.. [ 変更の保存 *] をクリックします。






== 詳細については、こちらをご覧ください

* xref:task_replication_pair_volumes_using_a_volume_id.adoc[ボリューム ID を使用してボリュームをペアリング]
* xref:task_replication_pair_volumes_using_a_pairing_key.adoc[ペアリングキーを使用してボリュームをペアリングします]

