---
permalink: storage/task_monitor_system_alerts.html 
sidebar: sidebar 
keywords: system alerts, view, cluster faults, system errors 
summary: システムで発生したクラスタの障害やエラーに関する情報をアラートで確認できます。アラートには、情報、警告、エラーがあり、クラスタの稼働状況を表すインジケータとして利用できます。ほとんどのエラーは自動的に解決します。 
---
= システムアラートを表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムで発生したクラスタの障害やエラーに関する情報をアラートで確認できます。アラートには、情報、警告、エラーがあり、クラスタの稼働状況を表すインジケータとして利用できます。ほとんどのエラーは自動的に解決します。

ListClusterFaults API メソッドを使用すると、アラートの監視を自動化できます。これにより、発生したすべてのアラートに関する通知を受け取ることができます。

. Element UI で、 * Reporting * > * Alerts * を選択します。
+
ページ上のアラートは 30 秒ごとに更新されます。

+
すべてのイベントについて、次の情報が表示されます。

+
|===


| 項目 | 説明 


 a| 
ID
 a| 
クラスタアラートに関連付けられた一意の ID 。



 a| 
重大度
 a| 
アラートの重要度。有効な値は次のとおり

** warning ：近々対応が必要になる可能性があるが、マイナー問題です。システムのアップグレードは引き続き可能です。
** error ：原因のパフォーマンスが低下したり高可用性（ HA ）が失われたりする可能性のある障害です。通常、エラーがサービスに影響することはありません。
** critical ：サービスに影響する深刻な障害です。システムは API 要求またはクライアント I/O 要求を処理できません。この状態で運用を続けると、データが失われる可能性があります。
** bestPractice ：推奨されるシステム構成のベストプラクティスが使用されていません。




 a| 
を入力します
 a| 
エラーの影響を受けるコンポーネント。node 、 drive 、 cluster 、 service 、 volume のいずれかです。



 a| 
ノード
 a| 
この障害に関連するノードのノード ID 。エラーのタイプが node と drive の場合に表示され、それ以外の場合は - （ダッシュ）が表示されます。



 a| 
ドライブ ID
 a| 
この障害に関連するドライブのドライブ ID 。エラーのタイプが drive の場合に表示され、それ以外の場合は - （ダッシュ）が表示されます。



 a| 
エラーコード
 a| 
エラーの原因を示すコード。



 a| 
詳細
 a| 
エラーの概要とその他の詳細情報。



 a| 
日付
 a| 
障害がログに記録された日時。

|===
. 個々のアラートの ［ * 詳細を表示 * ］ をクリックすると、そのアラートに関する情報が表示されます。
. ページ上のすべてのアラートの詳細を表示するには、 Details 列をクリックします。
+
アラートが解決されると、解決日を含むアラートに関するすべての情報が解決済み領域に移動されます。





== 詳細については、こちらをご覧ください

* xref:reference_monitor_cluster_fault_codes.adoc[クラスタ障害コード]
* link:../api/index.html["Element API を使用してストレージを管理します"]

