---
permalink: storage/task_data_protection_edit_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, edit, modify 
summary: 既存の Snapshot スケジュールを変更できます。変更後、次回のスケジュール実行時に更新された属性が使用されます。元のスケジュールで作成された Snapshot はストレージシステムに保持されます。 
---
= Snapshot スケジュールを編集します
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の Snapshot スケジュールを変更できます。変更後、次回のスケジュール実行時に更新された属性が使用されます。元のスケジュールで作成された Snapshot はストレージシステムに保持されます。

.手順
. [ * データ保護 *>* スケジュール * ] をクリックします。
. 変更するスケジュールの * Actions * アイコンをクリックします。
. 表示されたメニューで、 * 編集 * をクリックします。
. 「 * Volume IDs CSV * 」フィールドで、 Snapshot 処理に現在含まれている単一のボリューム ID またはカンマで区切ったボリューム ID のリストを変更します。
. スケジュールを一時停止または再開するには、次のオプションを選択します。
+
** アクティブなスケジュールを一時停止するには、 * Manually Pause Schedule * （スケジュールを手動で一時停止）リストから * Yes * を選択します。
** 一時停止したスケジュールを再開するには、 * Manually Pause Schedule * （スケジュールを手動で一時停止）リストから * No * を選択します。


. 必要に応じて、 ［ * 新しいスケジュール名 * ］ フィールドにスケジュールの別の名前を入力します。
. 別の曜日または月に実行するようにスケジュールを変更するには、「 * スケジュールタイプ * 」を選択し、表示されるオプションからスケジュールを変更します。
. * オプション： * Recurring Schedule * を選択し、 Snapshot スケジュールを無期限に繰り返します。
. * オプション： * New Snapshot Name * フィールドに、新しい Snapshot の名前を入力または変更します。
+
このフィールドを空白のままにすると、 Snapshot の作成日時が名前として使用されます。

. * オプション： * ペアリング時に Snapshot をレプリケーションに含める * チェックボックスをオンにして、親ボリュームがペアリングされている場合に Snapshot をレプリケーションにキャプチャします。
. 保持設定を変更するには、次のオプションから選択します。
+
** 「 * Forever * 」をクリックして、 Snapshot をシステム上に無期限に保持します。
** [ * 保存期間の設定 * ] をクリックし、日付スピンボックスを使用して、システムがスナップショットを保持する期間を選択します。


. [ 変更の保存 *] をクリックします。

