---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: ネットワーク設定を変更してネットワーク構成に適用したら、変更内容をテストできます。テストを実行することで、ストレージノードが安定していて問題なくオンラインに移行できることを確認できます。 
---
= ノード UI を使用してシステムテストを実行します
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワーク設定を変更してネットワーク構成に適用したら、変更内容をテストできます。テストを実行することで、ストレージノードが安定していて問題なくオンラインに移行できることを確認できます。

ストレージノードのノード UI にログインしておきます。

. [ システムテスト ] をクリックします。
. 実行するテストの横にある * テストの実行 * をクリックするか、 * すべてのテストを実行 * を選択します。
+

NOTE: すべてのテスト処理には時間がかかるため、ネットアップサポートの指示があった場合にのみ実行してください。

+
** * 接続されたアンサンブル * をテストします
+
データベースアンサンブルへの接続をテストして検証します。デフォルトでは、ノードが関連付けられたクラスタのアンサンブルを使用します。また、接続をテストする別のアンサンブルを指定することもできます。

** * テスト接続 Mvip *
+
指定した管理仮想 IP （ MVIP ）アドレスに対して ping を実行してから、 MVIP への簡単な API 呼び出しを実行して接続を検証します。デフォルトでは、ノードが関連付けられているクラスタの MVIP がテストに使用されます。

** * テスト接続 Svip *
+
ネットワークアダプタで設定されている Maximum Transmission Unit （ MTU ；最大転送単位）サイズと同じ Internet Control Message Protocol （ ICMP ）パケットを使用して、指定したストレージ仮想 IP （ SVIP ）アドレスに対して ping を実行します。その後、 iSCSI イニシエータとして SVIP に接続します。デフォルトでは、ノードが関連付けられているクラスタの SVIP がテストに使用されます。

** * ハードウェア構成のテスト *
+
すべてのハードウェア構成をテストして、ファームウェアのバージョンが正しいこと、すべてのドライブが適切に実装されて実行されていることを確認します。これは工場出荷時のテストと同じです。

+

NOTE: このテストは大量のリソースを消費するため、ネットアップサポートから要求された場合にのみ実行してください。

** * ローカル接続のテスト *
+
各ノードでクラスタ IP （ CIP ）に対して ping を実行して、クラスタの他のすべてのノードへの接続をテストします。このテストは、ノードがアクティブなクラスタに属している場合にのみ表示されます。

** * テストクラスタの検索 *
+
ノードがクラスタ構成で指定されたクラスタを特定できることを検証します。

** * ネットワーク構成のテスト *
+
設定したネットワーク設定がシステムで使用されているネットワーク設定と一致することを確認します。このテストは、ノードがクラスタにアクティブに参加しているときにハードウェア障害を検出するためのものではありません。

** * ping テスト *
+
指定した一連のホストに対して ping を実行し、単純な接続テストを行います。ホストを指定しない場合は、クラスタのすべての登録済みノードのリストが動的に作成され、 ping が実行されます。

** * リモート接続のテスト *
+
各ノードでクラスタ IP （ CIP ）に対して ping を実行して、リモートペアクラスタのすべてのノードへの接続をテストします。このテストは、ノードがアクティブなクラスタに属している場合にのみ表示されます。




