---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: ノードへのリモート IPMI アクセスが可能になった時点で、デフォルトの Intelligent Platform Management Interface （ IPMI ）管理者パスワードを変更できます。この処理は、インストールの更新があった場合などに実行します。 
---
= ノードのデフォルトの IPMI パスワードを変更します
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードへのリモート IPMI アクセスが可能になった時点で、デフォルトの Intelligent Platform Management Interface （ IPMI ）管理者パスワードを変更できます。この処理は、インストールの更新があった場合などに実行します。

ノードに対する IPM アクセスの設定の詳細については、を参照してください link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["各ノードに IPMI を設定します"^]。

これらのノードの IPM パスワードを変更できます。

* H410S ノード
* H610S ノード




== H410S ノードのデフォルトの IPMI パスワードを変更します

IPMI ネットワークポートを設定したらすぐに、各ストレージノードで IPMI 管理者アカウントのデフォルトパスワードを変更する必要があります。

各ストレージノードに IPMI の IP アドレスを設定しておく必要があります。

.手順
. IPMI ネットワークにアクセス可能なコンピュータで Web ブラウザを開き、ノードの IPMI IP アドレスにアクセスします。
. ログイン・プロンプトにユーザ名 ADMIN とパスワード ADMIN を入力します
. ログインしたら、 * Configuration * タブをクリックします。
. [* ユーザー * ] をクリックします。
. 「 Admin 」ユーザを選択し、「 * Modify User * 」をクリックします。
. [ パスワードの変更 *] チェックボックスをオンにします。
. [ パスワード *] フィールドと [ パスワードの確認 *] フィールドに新しいパスワードを入力します。
. [* 変更 *] をクリックし、 [OK] をクリックします。
. デフォルトの IPMI パスワードを使用するすべての他の H410S ノードについて、この手順を繰り返します。




== H610S ノードのデフォルトの IPMI パスワードを変更します

IPMI ネットワークポートを設定したらすぐに、各ストレージノードで IPMI 管理者アカウントのデフォルトパスワードを変更する必要があります。

各ストレージノードに IPMI の IP アドレスを設定しておく必要があります。

.手順
. IPMI ネットワークにアクセス可能なコンピュータで Web ブラウザを開き、ノードの IPMI IP アドレスにアクセスします。
. ログインプロンプトにユーザ名「 root 」とパスワード「 calvin 」を入力します。
. ログインしたら、ページ左上のメニューナビゲーションアイコンをクリックしてサイドバードロワーを開きます。
. [* 設定 * ] をクリックします。
. [ ユーザー管理 ] をクリックします。
. リストから * Administrator * ユーザーを選択します。
. [ パスワードの変更 *] チェックボックスをオンにします。
. [ パスワード *] フィールドと [ パスワードの確認 *] フィールドに、新しい強力なパスワードを入力します。
. ページの下部にある「 * 保存」をクリックします。
. デフォルトの IPMI パスワードを使用するすべての H610S ノードについて、この手順を繰り返します。




== 詳細については、こちらをご覧ください

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

