---
permalink: storage/task_data_manage_vol_access_group_add_a_single_initiator.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add single initiator, create initiator 
summary: 既存のボリュームアクセスグループにイニシエータを追加できます。 
---
= ボリュームアクセスグループに単一のイニシエータを追加します
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のボリュームアクセスグループにイニシエータを追加できます。

ボリュームアクセスグループに追加されたイニシエータは、そのボリュームアクセスグループ内のすべてのボリュームにアクセスできます。


TIP: 各ボリュームのイニシエータを特定するには、アクションアイコンをクリックし、アクティブボリュームリストからボリュームの詳細を表示 * を選択します。

イニシエータベースの CHAP を使用する場合は、ボリュームアクセスグループ内の 1 つのイニシエータに CHAP クレデンシャルを追加することでセキュリティを強化できます。これにより、すでに存在するボリュームアクセスグループにこのオプションを適用できます。

.手順
. [* 管理 *>* アクセスグループ *] をクリックします。
. 編集するアクセスグループの * アクション * アイコンをクリックします。
. [ 編集（ Edit ） ] をクリックします。
. Fibre Channel イニシエータをボリュームアクセスグループに追加するには、次の手順を実行します。
+
.. Add Initiators （イニシエータの追加）で、 Unbound Fibre Channel Initiators （バインド解除されたファイバチャネルイニシエータ * ）リストから既存のファイバチャネルイニシエータを選択
.. [Add FC Initiator*] をクリックします。
+

NOTE: この手順でイニシエータを作成するには、 [ イニシエータの作成 ] リンクをクリックし、イニシエータ名を入力して、 [* 作成 ] をクリックします。イニシエータを作成すると、イニシエータは自動的に「 * Initiators * 」リストに追加されます。

+
形式の例を次に示します。



+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
. iSCSI イニシエータをボリュームアクセスグループに追加するには、イニシエータの追加で、 * イニシエータ * リストから既存のイニシエータを選択します。
+

NOTE: この手順でイニシエータを作成するには、 [ イニシエータの作成 ] リンクをクリックし、イニシエータ名を入力して、 [* 作成 ] をクリックします。イニシエータを作成すると、イニシエータは自動的に「 * Initiators * 」リストに追加されます。

+
イニシエータ IQN の有効な形式は、 iqn.yyyy-mm です。 y と m は数字で、続けて任意の文字列を指定します。使用できる文字は、数字、小文字のアルファベット、ピリオド、コロン（：）、ダッシュ（ - ）です。

+
形式の例を次に示します。

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+

TIP: 各ボリュームのイニシエータ IQN は、操作アイコンをクリックし、ボリュームの詳細を表示 * を選択すると、 * Management * > * Volumes * Active Volumes ページに表示されます。

. [ 変更の保存 *] をクリックします。

