---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: SolidFire ストレージシステムでは、テナントはアカウントを使用して、クライアントがノード上のボリュームに接続できるようにすることができます。アカウントには、そのアカウントに割り当てられているボリュームへのアクセスに必要な CHAP 認証が含まれています。ボリュームは、作成時に特定のアカウントに割り当てられます。 
---
= CHAPを使用してアカウントを操作します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire ストレージシステムでは、テナントはアカウントを使用してクライアントがクラスタ上のボリュームに接続できるようにすることができます。アカウントには、割り当てられているボリュームへのアクセスに必要なChallenge Handshake Authentication Protocol（CHAP；チャレンジハンドシェイク認証プロトコル）認証が含まれています。ボリュームは、作成時に特定のアカウントに割り当てられます。

アカウントには最大 2 、 000 個のボリュームを関連付けることができますが、 1 つのボリュームが属することのできるアカウントは 1 つだけです。



== CHAPアルゴリズム

Element 12.7以降では、FIPS準拠のセキュアなCHAPアルゴリズムSHA1、SHA-256、およびSHA3-256がサポートされています。ホストiSCSIイニシエータは、Element iSCSIターゲットとのiSCSIセッションを作成するときに、使用するCHAPアルゴリズムのリストを要求します。ElementのiSCSIターゲットは、ホストのiSCSIイニシエータが要求したリストから、最初にサポートするアルゴリズムを選択します。ElementのiSCSIターゲットが最もセキュアなアルゴリズムを選択することを確認するには、ホストのiSCSIイニシエータを設定して、最もセキュアなアルゴリズム（SHA-256など）から最もセキュアでないアルゴリズムのリストを送信する必要があります。たとえば、次のようになります。 SHA1またはMD5。ホストのiSCSIイニシエータからSHAアルゴリズムが要求されない場合は、ホストから提示されたアルゴリズムのリストにMD5が含まれていれば、Element iSCSIターゲットによってMD5が選択されます。セキュアなアルゴリズムのサポートを有効にするために、ホストのiSCSIイニシエータ設定の更新が必要になる場合があります。

Element 12.7以降のアップグレードで、ホストのiSCSIイニシエータ設定を更新してSHAアルゴリズムを含むセッション要求を送信している場合は、ストレージノードのリブート時に新しいセキュアアルゴリズムがアクティブ化され、最もセキュアなプロトコルを使用して新規または再接続されたiSCSIセッションが確立されます。アップグレード時に、既存のすべてのiSCSIセッションがMD5からSHAに移行します。SHAを要求するためにホストiSCSIイニシエータの設定を更新しない場合、既存のiSCSIセッションでは引き続きMD5が使用されます。ホストのiSCSIイニシエータCHAPアルゴリズムをあとで更新したあと、iSCSIセッションは、iSCSIセッションの再接続になるメンテナンス作業に基づいて、時間の経過とともにMD5からSHAに徐々に移行する必要があります。

たとえば、Red Hat Enterprise Linux（RHEL）8.3のデフォルトのホストiSCSIイニシエータでは、「node.session.auth.chap_algs = SHA3-256、SHA256、SHA1、MD5」の設定がコメントアウトされており、iSCSIイニシエータではMD5が使用されています。ホストでこの設定のコメントを解除し、iSCSIイニシエータを再起動すると、そのホストからのiSCSIセッションがSHA-256を使用し始めるようになります。

必要に応じて、を使用できます https://docs.netapp.com/us-en/element-software/api/reference_element_api_listiscsisessions.html["ListISCSISessions"] 各セッションで使用されているCHAPアルゴリズムを確認するためのAPIメソッド。



== アカウントを作成します

アカウントを作成して、ボリュームへのアクセスを許可することができます。

システム内のアカウント名はそれぞれ一意である必要があります。

. [* 管理 *>] > [* アカウント ] を選択します。
. ［ * アカウントの作成 * ］ をクリックします。
. * ユーザー名 * を入力します。
. [* CHAP 設定 * （ * CHAP Settings * ） ] セクションで、次の情報を入力します。
+

NOTE: パスワードを自動生成する場合は、クレデンシャルフィールドを空白のままにします。

+
** * イニシエータシークレット * - CHAP ノードセッション認証用
** * Target Secret * ： CHAP ノードセッション認証用


. ［ * アカウントの作成 * ］ をクリックします。




== アカウントの詳細を表示します

個々のアカウントのパフォーマンスアクティビティをグラフ形式で表示できます。

グラフには、アカウントの I/O とスループットの情報が表示されます。Average と Peak のアクティビティレベルが、 10 秒間隔で表示されます。これらの統計には、アカウントに割り当てられているすべてのボリュームのアクティビティが含まれます。

. [* 管理 *>] > [* アカウント ] を選択します。
. アカウントの [ アクション ] アイコンをクリックします。
. [ * 詳細の表示 * ] をクリックします。


以下に詳細を示します。

* * ステータス * ：アカウントのステータス。有効な値は次のとおり
+
** active ：アクティブアカウント。
** locked ：ロック済みアカウント。
** removed ：削除およびパージされたアカウント。


* * Active Volumes * ：アカウントに割り当てられているアクティブなボリュームの数。
* * Compression * ：アカウントに割り当てられているボリュームの圧縮による削減率。
* * 重複排除機能 * ：アカウントに割り当てられているボリュームの重複排除による削減率。
* * シンプロビジョニング * ：アカウントに割り当てられたボリュームのシンプロビジョニングによる削減率。
* * 全体的な削減率 * ：アカウントに割り当てられているボリュームの全体的な削減率。




== アカウントを編集します

アカウントを編集して、ステータス、 CHAP シークレット、またはアカウント名を変更できます。

アカウントの CHAP 設定を変更したり、アクセスグループからイニシエータやボリュームを削除したりすると、原因イニシエータがボリュームにアクセスできなくなることがあります。ボリュームへのアクセスが突然失われないようにするには、アカウントまたはアクセスグループの変更の影響を受ける iSCSI セッションを必ずログアウトし、イニシエータやクラスタの設定に対する変更が完了したあとにイニシエータからボリュームに再接続できることを確認してください。


IMPORTANT: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード時に作成された新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、関連付けられているアカウントを変更または削除しないでください。

. [* 管理 *>] > [* アカウント ] を選択します。
. アカウントの [ アクション ] アイコンをクリックします。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. * オプション： * ユーザー名 * を編集します。
. * オプション： * Status * ドロップダウンリストをクリックして、別のステータスを選択します。
+

IMPORTANT: ステータスを * locked * に変更すると、アカウントへのすべての iSCSI 接続が切断され、アカウントにアクセスできなくなります。アカウントに関連付けられているボリュームは維持されますが、 iSCSI で検出できなくなります。

. * オプション： * CHAP Settings * で、 * Initiator Secret * および * Target Secret * クレデンシャルを編集し、ノードセッション認証に使用します。
+

NOTE: CHAP 設定 * のクレデンシャルを変更しない場合、クレデンシャルは変更されません。クレデンシャルのフィールドを空白にすると、システムによって新しいパスワードが生成されます。

. [ 変更の保存 *] をクリックします。




== アカウントを削除します

不要になったアカウントを削除できます。

アカウントを削除する前に、そのアカウントに関連付けられているボリュームを削除およびパージします。


IMPORTANT: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード時に作成された新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、関連付けられているアカウントを変更または削除しないでください。

. [* 管理 *>] > [* アカウント ] を選択します。
. 削除するアカウントの [ アクション ] アイコンをクリックします。
. 表示されたメニューで、 * 削除 * を選択します。
. 操作を確定します。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

