---
permalink: storage/task_data_manage_vol_access_group_create_an_initiator.html 
sidebar: sidebar 
keywords: initiator, create, fc, iscsi, aliases, chap 
summary: iSCSI イニシエータまたは Fibre Channel イニシエータを作成し、オプションでエイリアスを割り当てることができます。 
---
= イニシエータを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI イニシエータまたは Fibre Channel イニシエータを作成し、オプションでエイリアスを割り当てることができます。

API 呼び出しを使用して、イニシエータベースの CHAP 属性を割り当てることもできます。イニシエータごとに CHAP アカウント名と資格情報を追加するには 'CreateInitiator API 呼び出しを使用して 'CHAP アクセスと属性を削除および追加する必要がありますイニシエータアクセスは、「 CreateInitiators 」および「 ModyInitiators 」 API 呼び出しで 1 つ以上の virtualNetworkID を指定することで、 1 つ以上の VLAN に制限できます。仮想ネットワークを指定しない場合、イニシエータはすべてのネットワークにアクセスできます。

詳細については、API リファレンス情報を参照してください。 link:../api/concept_element_api_about_the_api.html["Element API を使用してストレージを管理します"]

.手順
. [* 管理 *>* イニシエータ *] をクリックします。
. [ イニシエータの作成 ] をクリックします。
. 次の手順を実行して、 1 つまたは複数のイニシエータを作成します。
+
[cols="25,75"]
|===
| オプション | 手順 


 a| 
単一のイニシエータを作成する
 a| 
.. [* 単一イニシエータの作成 * ] をクリックします。
.. IQN または WWPN * フィールドにイニシエータの IQN または WWPN を入力します。
.. [* エイリアス ] フィールドにイニシエータのフレンドリ名を入力します。
.. [ イニシエータの作成 ] をクリックします。




 a| 
複数のイニシエータを作成する
 a| 
.. イニシエータの一括作成 * をクリックします。
.. IQN または WWPN のリストをテキストボックスに入力します。
.. [Add Initiators] をクリックします。
.. 表示されたリストからイニシエータを選択し、 [* Alias* ] 列の対応する [Add] アイコンをクリックして、イニシエータのエイリアスを追加します。
.. チェックマークをクリックして新しいエイリアスを確認します。
.. イニシエータの作成 * をクリックします。


|===

