---
permalink: storage/task_data_protection_back_up_volume_to_solidfire.html 
sidebar: sidebar 
keywords: volume backup, solidfire storage cluster 
summary: Element ソフトウェアを実行しているストレージクラスタでは、あるクラスタ上にあるボリュームをリモートのクラスタにバックアップできます。 
---
= ボリュームを SolidFire ストレージクラスタにバックアップします
:icons: font
:imagesdir: ../media/


[role="lead"]
Element ソフトウェアを実行しているストレージクラスタでは、あるクラスタ上にあるボリュームをリモートのクラスタにバックアップできます。

ソースクラスタとターゲットクラスタがペアリングされていることを確認します。

を参照してください link:task_replication_pair_clusters.html["レプリケーション用にクラスタをペアリング"]。

クラスタ間でバックアップまたはリストアを実行する際には、システムによってクラスタ間の認証に使用するキーが生成されます。ソースクラスタはこのボリュームの一括書き込みキーを使用してデスティネーションクラスタに対して認証し、デスティネーションボリュームへの書き込みがセキュリティで保護されます。バックアップまたはリストアのプロセスでは、処理を開始する前に、デスティネーションボリュームからボリュームの一括書き込みキーを生成する必要があります。

. デスティネーションクラスタで、 * Management * > * Volumes * と入力します。
. デスティネーションボリュームの操作アイコンをクリックします。
. 表示されたメニューで、 * リストア元 * をクリックします。
. 統合リストア * （ Integrated Restore * ）ダイアログボックスの * リストア元 * （ * Restore From * ）で * SolidFire * を選択します。
. [ データフォーマット *] でオプションを選択します。
+
** * Native * ： SolidFire ストレージシステムのみが読み取り可能な圧縮形式。
** * Uncompressed * ：他のシステムと互換性がある非圧縮形式。


. [* キーの生成 * ] をクリックします。
. キーを * Bulk Volume Write Key * ボックスからクリップボードにコピーします。
. ソースクラスタで、 * Management * > * Volumes * に移動します。
. バックアップするボリュームの [Actions] アイコンをクリックします。
. 表示されたメニューで、 * Backup to * をクリックします。
. [ * バックアップ先 * ] の下の [ 統合バックアップ * ] ダイアログボックスで、 [ * SolidFire * ] を選択します。
. [ * データ形式 * （ * Data Format * ） ] フィールドで前に選択したオプションと同じオプションを選択します。
. デスティネーションボリュームのクラスタの管理仮想 IP アドレスを * リモートクラスタ MVIP * フィールドに入力します。
. リモートクラスタのユーザ名を「 * リモートクラスタのユーザ名 * 」フィールドに入力します。
. リモートクラスタのパスワードを「 * リモートクラスタのパスワード * 」フィールドに入力します。
. 「 * Bulk Volume Write Key * 」フィールドに、前の手順でデスティネーションクラスタ上に生成したキーを貼り付けます。
. [ 読み取り開始 ] をクリックします。

