---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: SolidFire ストレージシステムでは、クライアントはユーザアカウントを使用してノード上のボリュームに接続します。ボリュームには、作成時に特定のユーザアカウントが割り当てられます。 
---
= ユーザアカウントを操作する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire ストレージシステムでは、クライアントはユーザアカウントを使用してノード上のボリュームに接続します。ボリュームには、作成時に特定のユーザアカウントが割り当てられます。

アカウントには、そのアカウントに割り当てられているボリュームへのアクセスに必要な CHAP 認証が含まれています。

アカウントには最大 2 、 000 個のボリュームを関連付けることができますが、 1 つのボリュームが属することのできるアカウントは 1 つだけです。



== アカウントを作成します

アカウントを作成して、ボリュームへのアクセスを許可することができます。

システム内のアカウント名はそれぞれ一意である必要があります。

. [* 管理 *>] > [* アカウント ] を選択します。
. ［ * アカウントの作成 * ］ をクリックします。
. * ユーザー名 * を入力します。
. [* CHAP 設定 * （ * CHAP Settings * ） ] セクションで、次の情報を入力します。
+

NOTE: パスワードを自動生成する場合は、クレデンシャルフィールドを空白のままにします。

+
** * イニシエータシークレット * - CHAP ノードセッション認証用
** * Target Secret * ： CHAP ノードセッション認証用


. ［ * アカウントの作成 * ］ をクリックします。




== アカウントの詳細を表示します

個々のアカウントのパフォーマンスアクティビティをグラフ形式で表示できます。

グラフには、アカウントの I/O とスループットの情報が表示されます。Average と Peak のアクティビティレベルが、 10 秒間隔で表示されます。これらの統計には、アカウントに割り当てられているすべてのボリュームのアクティビティが含まれます。

. [* 管理 *>] > [* アカウント ] を選択します。
. アカウントの [ アクション ] アイコンをクリックします。
. [ * 詳細の表示 * ] をクリックします。


以下に詳細を示します。

* * ステータス * ：アカウントのステータス。有効な値は次のとおり
+
** active ：アクティブアカウント。
** locked ：ロック済みアカウント。
** removed ：削除およびパージされたアカウント。


* * Active Volumes * ：アカウントに割り当てられているアクティブなボリュームの数。
* * Compression * ：アカウントに割り当てられているボリュームの圧縮による削減率。
* * 重複排除機能 * ：アカウントに割り当てられているボリュームの重複排除による削減率。
* * シンプロビジョニング * ：アカウントに割り当てられたボリュームのシンプロビジョニングによる削減率。
* * 全体的な削減率 * ：アカウントに割り当てられているボリュームの全体的な削減率。




== アカウントを編集します

アカウントを編集して、ステータス、 CHAP シークレット、またはアカウント名を変更できます。

アカウントの CHAP 設定を変更したり、アクセスグループからイニシエータやボリュームを削除したりすると、原因イニシエータがボリュームにアクセスできなくなることがあります。ボリュームへのアクセスが突然失われないようにするには、アカウントまたはアクセスグループの変更の影響を受ける iSCSI セッションを必ずログアウトし、イニシエータやクラスタの設定に対する変更が完了したあとにイニシエータからボリュームに再接続できることを確認してください。


IMPORTANT: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード時に作成された新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、関連付けられているアカウントを変更または削除しないでください。

. [* 管理 *>] > [* アカウント ] を選択します。
. アカウントの [ アクション ] アイコンをクリックします。
. 表示されたメニューで、「 * 編集 * 」を選択します。
. * オプション： * ユーザー名 * を編集します。
. * オプション： * Status * ドロップダウンリストをクリックして、別のステータスを選択します。
+

IMPORTANT: ステータスを * locked * に変更すると、アカウントへのすべての iSCSI 接続が切断され、アカウントにアクセスできなくなります。アカウントに関連付けられているボリュームは維持されますが、 iSCSI で検出できなくなります。

. * オプション： * CHAP Settings * で、 * Initiator Secret * および * Target Secret * クレデンシャルを編集し、ノードセッション認証に使用します。
+

NOTE: CHAP 設定 * のクレデンシャルを変更しない場合、クレデンシャルは変更されません。クレデンシャルのフィールドを空白にすると、システムによって新しいパスワードが生成されます。

. [ 変更の保存 *] をクリックします。




== アカウントを削除します

不要になったアカウントを削除できます。

アカウントを削除する前に、そのアカウントに関連付けられているボリュームを削除およびパージします。


IMPORTANT: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード時に作成された新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、関連付けられているアカウントを変更または削除しないでください。

. [* 管理 *>] > [* アカウント ] を選択します。
. 削除するアカウントの [ アクション ] アイコンをクリックします。
. 表示されたメニューで、 * 削除 * を選択します。
. 操作を確定します。




== 詳細については、こちらをご覧ください

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

