---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: 既存のボリュームアクセスグループに複数のイニシエータを追加すると、そのグループ内のボリュームに CHAP 認証の有無にかかわらずアクセスできるようになります。 
---
= ボリュームアクセスグループに複数のイニシエータを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のボリュームアクセスグループに複数のイニシエータを追加すると、そのグループ内のボリュームに CHAP 認証の有無にかかわらずアクセスできるようになります。

ボリュームアクセスグループに追加されたイニシエータは、そのボリュームアクセスグループ内のすべてのボリュームにアクセスできます。


TIP: 各ボリュームのイニシエータを特定するには、アクションアイコンをクリックし、アクティブボリュームリストにあるそのボリュームの詳細を表示 * をクリックします。

既存のボリュームアクセスグループに複数のイニシエータを追加すると、そのグループ内のボリュームにアクセスし、グループ内の各イニシエータに一意の CHAP クレデンシャルを割り当てることができます。これにより、すでに存在するボリュームアクセスグループにこのオプションを適用できます。

イニシエータベースの CHAP 属性を割り当てるには、 API 呼び出しを使用します。イニシエータごとに CHAP アカウント名とクレデンシャルを追加するには、 ModifyInitiator API 呼び出しを使用して、 CHAP アクセスと属性を削除および追加する必要があります。

詳細については、link:../api/concept_element_api_about_the_api.html["Element API を使用してストレージを管理します"] 。

.手順
. [* 管理 *>* イニシエータ *] をクリックします。
. アクセスグループに追加するイニシエータを選択します。
. [ 一括アクション * （ * Bulk Actions * ） ] ボタンをクリックします。
. [ * ボリュームアクセスグループに追加 * ] をクリックします。
. Add to Volume Access Group （ボリュームアクセスグループへの追加）ダイアログボックスで、 * Volume Access Group （ * ボリュームアクセスグループ）リストからアクセスグループを選択します。
. [ 追加（ Add ） ] をクリックします。

