---
permalink: storage/task-element-replication-make-destination-volume-writeable.html 
sidebar: sidebar 
keywords: ontap, cli, make, destination, volume, write 
summary: デスティネーションボリュームからクライアントにデータを提供するには、デスティネーションボリュームを書き込み可能にする必要があります。snapmirror quiesce コマンドを使用してデスティネーションへのスケジュールされた転送を停止し、 snapmirror abort コマンドを使用して実行中の転送を停止します。 snapmirror break コマンドを使用すると、デスティネーションを書き込み可能にできます。 
---
= デスティネーションボリュームを書き込み可能にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
災害によって SnapMirror DR 関係のプライマリサイトが機能しなくなった場合は、システム停止を最小限に抑えてデスティネーションボリュームからデータを提供できます。プライマリサイトでサービスが復旧したら、ソースボリュームを再アクティブ化できます。

デスティネーションボリュームからクライアントにデータを提供するには、デスティネーションボリュームを書き込み可能にする必要があります。コマンドを使用すると、デスティネーションへのスケジュールされた転送を停止したり、 `snapmirror abort`コマンドを使用して実行中の転送を停止したり、 `snapmirror break`コマンドを使用してデスティネーションを書き込み可能にしたりでき `snapmirror quiesce`ます。

.このタスクについて
Elementのソースパスをの形式で指定する必要があり `<hostip:>/lun/<name>`ます。「LUN」は実際の文字列「LUN」、 `name` はElementボリュームの名前です。

.手順
. デスティネーションへのスケジュールされた転送を停止します。
+
`snapmirror quiesce -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、IPアドレス10.0.0.11のソースボリュームとの `svm_backup`デスティネーションボリューム `volA_dst`の間のスケジュールされた転送を停止します `0005`。

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. デスティネーションへの実行中の転送を停止します。
+
`snapmirror abort -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、IPアドレス10.0.0.11のソースボリュームとの `svm_backup`デスティネーションボリューム `volA_dst`の間の実行中の転送を停止します `0005`。

+
[listing]
----
cluster_dst::> snapmirror abort -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. SnapMirror DR関係を解除します。
+
`snapmirror break -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、IPアドレス10.0.0.11のソースボリュームとの `svm_backup`デスティネーションボリュームと `volA_dst`のデスティネーションボリュームと `volA_dst`の `svm_backup`関係を解除します `0005`。

+
[listing]
----
cluster_dst::> snapmirror break -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

