---
permalink: storage/task_data_protection_restore_volume_from_backup_on_solidfire.html 
sidebar: sidebar 
keywords: volume restore, solidfire storage cluster 
summary: SolidFire ストレージクラスタ上のバックアップからボリュームをリストアできます。 
---
= SolidFire ストレージクラスタ上のバックアップからボリュームをリストアします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire ストレージクラスタ上のバックアップからボリュームをリストアできます。

クラスタ間でバックアップまたはリストアを実行する際には、システムによってクラスタ間の認証に使用するキーが生成されます。ソースクラスタはこのボリュームの一括書き込みキーを使用してデスティネーションクラスタに対して認証し、デスティネーションボリュームへの書き込みがセキュリティで保護されます。バックアップまたはリストアのプロセスでは、処理を開始する前に、デスティネーションボリュームからボリュームの一括書き込みキーを生成する必要があります。

. デスティネーションクラスタで、 * Management * > * Volumes * をクリックします。
. リストアするボリュームの操作アイコンをクリックします。
. 表示されたメニューで、 * リストア元 * をクリックします。
. 統合リストア * （ Integrated Restore * ）ダイアログボックスの * リストア元 * （ * Restore From * ）で * SolidFire * を選択します。
. バックアップに一致するオプションを * Data Format * ：
+
** * Native * ： SolidFire ストレージシステムのみが読み取り可能な圧縮形式。
** * Uncompressed * ：他のシステムと互換性がある非圧縮形式。


. [* キーの生成 * ] をクリックします。
. * 一括ボリューム書き込みキー * 情報をクリップボードにコピーします。
. ソースクラスタで、 * Management * > * Volumes * をクリックします。
. リストアに使用するボリュームの操作アイコンをクリックします。
. 表示されたメニューで、 * Backup to * をクリックします。
. 統合バックアップ * （ Integrated Backup * ）ダイアログボックスで、 * バックアップ先 * （ * Backup to * ）で * SolidFire * を選択します。
. バックアップに一致するオプションを * Data Format * で選択します。
. デスティネーションボリュームのクラスタの管理仮想 IP アドレスを * リモートクラスタ MVIP * フィールドに入力します。
. リモートクラスタのユーザ名を「 * リモートクラスタのユーザ名 * 」フィールドに入力します。
. リモートクラスタのパスワードを「 * リモートクラスタのパスワード * 」フィールドに入力します。
. クリップボードから * Bulk Volume Write Key * フィールドにキーを貼り付けます。
. [ 読み取り開始 ] をクリックします。

