---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: ストレージの追加が必要になったとき、またはクラスタ作成後に、クラスタにノードを追加できます。ノードは、初回の電源投入時に初期設定を行う必要があります。設定が完了したノードは保留状態のノードのリストに表示され、クラスタに追加できます。 
---
= クラスタにノードを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージの追加が必要になったとき、またはクラスタ作成後に、クラスタにノードを追加できます。ノードは、初回の電源投入時に初期設定を行う必要があります。設定が完了したノードは保留状態のノードのリストに表示され、クラスタに追加できます。

クラスタ内の各ノードは、互換性のあるソフトウェアバージョンを実行している必要があります。クラスタにノードを追加すると、必要に応じて新しいノードに NetApp Element ソフトウェアのクラスタバージョンがインストールされます。

既存のクラスタには、大小さまざまな容量のノードを追加できます。クラスタの容量を拡張するには、大容量のノードを追加します。小容量のノードで構成されるクラスタに大容量のノードを追加するときは、ペアにして追加する必要があります。これにより、一方の大容量ノードで障害が発生しても、 Double Helix でデータを移動する十分なスペースが確保されます。大容量ノードクラスタのパフォーマンスを向上させるには、小容量ノードを追加します。


NOTE: 新しく追加したノードがクラスタの合計容量の 50% を超えると、容量のルールに準拠するためにこのノードの一部の容量が使用できなくなります（「未使用」）。これは、ストレージが追加されるまで有効です。容量のルールにも違反するような大規模なノードを追加すると、それまでに孤立していたノードは孤立しなくなり、新たに追加したノードが孤立する状態になります。この問題を回避するには、容量を常にペアで追加する必要があります。ノードが孤立状態になると、 strandedCapacity クラスタエラーがスローされます。

https://www.youtube.com/embed/2smVHWkikXY?rel=0["ネットアップのビデオ： Scale on Your Terms ： Expanding a SolidFire Cluster"]

ノードは、 SolidFire エンタープライズ SDS （ SolidFire ESDS ）クラスタまたは NetApp HCI アプライアンスに追加できます。

SolidFire ESDS ノードは、「 S FC 」のようにノードタイププレフィックス「 `S FC100. 」で示されます。

.手順
. [* Cluster*>* Nodes] を選択します。
. 保留中のノードのリストを表示するには、 * Pending * をクリックします。
+
ノード（ SolidFire ESDS または SolidFire ESDS 以外の両方のノード）を追加するプロセスが完了すると、それらのノードがアクティブノードリストに表示されます。それまでは、保留中のノードが [ 保留中のアクティブ ] リストに表示されます。

+
SolidFire ESDS ノード以外のノードをクラスタに追加すると、 SolidFire によって保留状態のノードにクラスタの Element ソフトウェアバージョンがインストールされます。この処理には数分かかることがあります。

. 次のいずれかを実行します。
+
** 個々のノードを追加するには、追加するノードの * Actions * アイコンをクリックします。
** 複数のノードを追加するには、追加するノードのチェックボックスをオンにし、 * Bulk Actions * を実行します。* 注：追加するノードの Element ソフトウェアのバージョンがクラスタで実行されているバージョンと異なる場合は、クラスタマスターで実行されている Element ソフトウェアのバージョンに非同期的に更新されます。更新されたノードは、自動的にクラスタに追加されます。この非同期プロセスの実行中、ノードの状態は pendingActive になります。


. [ 追加（ Add ） ] をクリックします。
+
ノードがアクティブノードのリストに表示されます。





== 詳細については、こちらをご覧ください

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[ノードのバージョンと互換性]
