---
permalink: storage/task_replication_pair_clusters.html 
sidebar: sidebar 
keywords: pair clusters, replication, connect clusters, data protection 
summary: リアルタイムレプリケーション機能を使用するには、最初に 2 つのクラスタをペアリングする必要があります。2 つのクラスタをペアリングして接続したあと、一方のクラスタのアクティブなボリュームをもう一方のクラスタに継続的にレプリケートするように設定することで継続的なデータ保護を実現できます \ （ CDP ）。 
---
= レプリケーション用にクラスタをペアリング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リアルタイムレプリケーション機能を使用するには、最初に 2 つのクラスタをペアリングする必要があります。2 つのクラスタをペアリングして接続したあと、一方のクラスタのアクティブなボリュームをもう一方のクラスタに継続的にレプリケートするように設定することで継続的なデータ保護（ CDP ）を実現できます。

.必要なもの
* ペアリングするクラスタの一方または両方に対するクラスタ管理者権限が必要です。
* すべてのノード MIP とノード SIP を相互にルーティングする必要があります。
* クラスタ間のラウンドトリップレイテンシが 2 、 000 ミリ秒未満である必要があります。
* 両方のストレージクラスタに、一意のクラスタ名、 MVIP 、 SVIP 、およびすべてのノード IP アドレスが必要です。
* クラスタの Element ソフトウェアのバージョンの違いが 1 メジャーバージョン以内である必要があります。それよりも離れている場合、データレプリケーションを実行するには一方のクラスタをアップグレードする必要があります。



NOTE: クラスタをペアリングするには、管理ネットワーク上のノードどうしが完全に接続されている必要がレプリケーションを実行するには、ストレージクラスタネットワーク上の個々のノードが接続されている必要があります。

ボリュームのレプリケーション用に、 1 つのクラスタを最大 4 つの他のクラスタとペアリングすることができます。同じクラスタグループに含まれるクラスタどうしをペアリングすることもできます。



== MVIP またはペアリングキーを使用してクラスタをペアリング

両方のクラスタにクラスタ管理者としてアクセスできる場合は、ターゲットクラスタの MVIP を使用してソースとターゲットのクラスタをペアリングできます。クラスタペアの一方のクラスタにしかクラスタ管理者としてアクセスできない場合は、ターゲットクラスタでペアリングキーを使用してクラスタをペアリングします。

. 次のいずれかの方法を選択してクラスタをペアリングします。
+
** link:task_replication_pair_cluster_using_mvip.html["MVIP を使用してクラスタをペアリング"]: 両方のクラスターにクラスター管理者のアクセス権がある場合は、この方法を使用します。この方法では、リモート クラスターの MVIP を使用して 2 つのクラスターをペアリングします。
** link:task_replication_pair_cluster_using_pairing_key.html["ペアリングキーを使用してクラスタをペアリングします"]: クラスター管理者がアクセスできるクラスターが 1 つだけの場合は、この方法を使用します。このメソッドは、ターゲット クラスターでクラスターのペアリングを完了するために使用できるペアリング キーを生成します。






== 詳細については、こちらをご覧ください

xref:reference_prereq_network_port_requirements.adoc[ネットワークポートの要件]
