---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 安全なアクセスを確保するために、ボリュームのグループにイニシエータをマッピングしてボリュームアクセスグループを作成できます。その後、アカウントの CHAP イニシエータシークレットとターゲットシークレットを使用して、グループ内のボリュームへのアクセスを許可できます。 
---
= ボリュームアクセスグループを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安全なアクセスを確保するために、ボリュームのグループにイニシエータをマッピングしてボリュームアクセスグループを作成できます。その後、アカウントの CHAP イニシエータシークレットとターゲットシークレットを使用して、グループ内のボリュームへのアクセスを許可できます。

イニシエータベースの CHAP を使用する場合は、ボリュームアクセスグループ内の 1 つのイニシエータに CHAP クレデンシャルを追加することでセキュリティを強化できます。これにより、すでに存在するボリュームアクセスグループにこのオプションを適用できます。

.手順
. [* 管理 *>* アクセスグループ *] をクリックします。
. [ アクセスグループの作成 *] をクリックします。
. ボリュームアクセスグループの名前を * Name * フィールドに入力します。
. 次のいずれかの方法でボリュームアクセスグループにイニシエータを追加します。
+
[cols="25,75"]
|===
| オプション | 説明 


 a| 
Fibre Channel イニシエータを追加しています
 a| 
.. Add Initiators （イニシエータの追加）で、 Unbound Fibre Channel Initiators （未バインドのファイバチャネルイニシエータ）リストから既存のファイバチャネルイニシエータを
.. [Add FC Initiator*] をクリックします。
+

NOTE: この手順でイニシエータを作成するには、 [ イニシエータの作成 ] リンクをクリックし、イニシエータ名を入力して、 [* 作成 ] をクリックします。イニシエータを作成すると、イニシエータがイニシエータリストに自動的に追加されます。



形式の例を次に示します。

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
iSCSI イニシエータの追加
 a| 
イニシエータの追加で、イニシエータリストから既存のイニシエータを選択します。* 注： * イニシエータの作成 * リンクをクリックし、イニシエータ名を入力して、 * 作成 * をクリックすると、この手順の実行中にイニシエータを作成できます。イニシエータを作成すると、イニシエータがイニシエータリストに自動的に追加されます。

形式の例を次に示します。

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: 各ボリュームのイニシエータ IQN を確認するには、 * Management * > * Volumes * > * Active * リストで、そのボリュームの Actions メニューから * View Details * を選択します。

イニシエータを変更するときは、 requiredCHAP 属性を True に切り替えて、ターゲットイニシエータシークレットを設定できます詳細については、 ModifyInitiator API メソッドに関する API 情報を参照してください。

link:../api/index.html["Element API を使用してストレージを管理します"]

|===
. * オプション： * 必要に応じてイニシエータを追加します。
. Add Volumes （ボリュームの追加）で、 * Volumes （ボリューム） * リストからボリュームを選択します。
+
ボリュームが * Attached Volumes * リストに表示されます。

. * オプション： * 必要に応じてボリュームを追加します。
. [ アクセスグループの作成 *] をクリックします。




== 詳細については、こちらをご覧ください

xref:task_data_manage_vol_access_group_add_volumes.adoc[アクセスグループにボリュームを追加する]
