---
permalink: storage/task_replication_plan_cluster_and_volume_pairing.html 
sidebar: sidebar 
keywords: cluster, volume pairing, plan for, real-time replication 
summary: リアルタイムでリモートレプリケーションを行うには、 Element ソフトウェアを実行する 2 つのストレージクラスタをペアリングし、各クラスタのボリュームをペアリングしてから、レプリケーションを検証する必要があります。レプリケーションが完了したら、ボリューム関係を削除します。 
---
= リアルタイムレプリケーションのためのクラスタとボリュームのペアリングを計画します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リアルタイムでリモートレプリケーションを行うには、 Element ソフトウェアを実行する 2 つのストレージクラスタをペアリングし、各クラスタのボリュームをペアリングしてから、レプリケーションを検証する必要があります。レプリケーションが完了したら、ボリューム関係を削除します。

.必要なもの
* ペアリングするクラスタの一方または両方に対するクラスタ管理者権限が必要です。
* 管理ネットワークとストレージネットワークの両方のノード IP アドレスが、ペアリングするクラスタ間で相互にルーティングされている必要があります。
* すべてのペアノードで MTU が同じでなければならず、クラスタ間でエンドツーエンドでサポートされている必要があります。
* 両方のストレージクラスタに、一意のクラスタ名、 MVIP 、 SVIP 、およびすべてのノード IP アドレスが必要です。
* クラスタの Element ソフトウェアのバージョンの違いが 1 メジャーバージョン以内である必要があります。それよりも離れている場合、データレプリケーションを実行するには一方のクラスタをアップグレードする必要があります。



NOTE: データのレプリケーションにおける WAN アクセラレータアプライアンスの使用は、ネットアップで認定されていません。データをレプリケートする 2 つのクラスタ間にこのアプライアンスを配置すると、圧縮および重複排除の妨げとなる場合があります。WAN アクセラレータアプライアンスを本番環境に導入する前に、影響を十分に検証してください。



== 詳細については、こちらをご覧ください

* xref:task_replication_pair_clusters.adoc[レプリケーション用にクラスタをペアリング]
* xref:task_replication_pair_volumes.adoc[ボリュームをペアリング]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアリングされたボリュームにレプリケーションのソースとターゲットを割り当てます]

