---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: ストレージノードのノード UI を使用して、サポートバンドルの作成または削除、ドライブの設定のリセット、ネットワークサービスまたはクラスタサービスの再起動を実行できます。 
---
= ノード UI を使用してシステムユーティリティを実行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードのノード UI を使用して、サポートバンドルの作成または削除、ドライブの設定のリセット、ネットワークサービスまたはクラスタサービスの再起動を実行できます。

ストレージノードのノード UI にログインしておきます。

. [ システムユーティリティ ] をクリックします。
. 実行するシステムユーティリティのボタンをクリックします。
+
** * 制御電力 *
+
ノードをリブート、電源再投入、またはシャットダウンします。

+

IMPORTANT: この処理を実行すると、ネットワーク接続が一時的に失われます。

+
次のパラメータを指定します。

+
*** 処置：オプションには、再起動と停止（電源オフ）が含まれます。
*** Wakeup Delay ：ノードがオンラインに戻るまでの時間。


** * ノードログを収集 *
+
ノードの /tmp/bundles ディレクトリにサポートバンドルを作成します。

+
次のパラメータを指定します。

+
*** Bundle Name ：作成された各サポートバンドルの一意の名前。名前を指定しない場合、「 supportbundle 」とノード名がファイル名として使用されます。
*** Extra Args ：このパラメータが sf_make_support_bundle スクリプトに渡されます。このパラメータは、ネットアップサポートから指示された場合にのみ使用します。
*** Timeout Sec ：個々の ping 応答を待機する秒数を指定します。


** * ノードログの削除 *
+
Create Cluster Support Bundle * または CreateSupportBundle API メソッドを使用して作成されたノードの現在のサポートバンドルを削除します。

** * ドライブのリセット *
+
ドライブを初期化し、ドライブに現在格納されているすべてのデータを削除します。既存のノードまたはアップグレードしたノードでドライブを再利用できます。

+
次のパラメータを指定します。

+
*** drives ：リセットするデバイス名（ドライブ ID ではない）のリスト。


** * ネットワーク構成のリセット *
+
個々のノードのネットワーク設定の問題を解決し、個々のノードのネットワーク設定を工場出荷時のデフォルト設定にリセットするのに役立ちます。

** * ノードのリセット *
+
ノードを工場出荷時の設定にリセットします。すべてのデータが削除されますが、ノードのネットワーク設定はこの処理の実行中も保持されます。ノードは、クラスタに割り当てられておらず、使用可能な状態の場合にのみリセットできます。

+

IMPORTANT: このオプションを使用すると、すべてのデータ、パッケージ（ソフトウェアアップグレード）、設定、およびログファイルがノードから削除されます。

** * ネットワークを再起動 *
+
ノードのすべてのネットワークサービスを再起動します。

+

IMPORTANT: この処理を実行すると、原因によってネットワーク接続が一時的に失われる可能性が

** * サービスを再起動 *
+
ノードで Element ソフトウェアサービスを再起動します。

+

IMPORTANT: この処理を実行すると、原因の一時的なノードサービスが中断されるこの処理は、ネットアップサポートから指示があった場合にのみ実行してください。

+
次のパラメータを指定します。

+
*** service ：再起動するサービス名。
*** アクション：サービスに対して実行するアクション。オプションには、開始、停止、再起動があります。





