---
permalink: storage/task_snapmirror_perform_failback_when_source_volume_exists.html 
sidebar: sidebar 
keywords: failback, perform, source volume, snapmirror, ui 
summary: NetAppElement UI を使用して、元のソースボリュームを再同期し、フェイルバックを実行できます。元のソースボリュームがまだ存在している手順環境のシナリオです。 
---
= ソースボリュームが存在する場合は、フェイルバックを実行します
:icons: font
:imagesdir: ../media/


[role="lead"]
NetAppElement UI を使用して、元のソースボリュームを再同期し、フェイルバックを実行できます。元のソースボリュームがまだ存在している手順環境のシナリオです。

. Element UI で、フェイルオーバーを実行するために解除する関係を探します。
. アクションアイコンをクリックし、 * 逆再同期 * をクリックします。
. 操作を確定します。
+

NOTE: 逆再同期（ Reverse Resync ）処理では、元のソースボリュームとデスティネーションボリュームの役割が逆転した新しい関係が作成されます（元の関係は残されるので、 2 つの関係が存在することになります）。逆再同期処理の一環として、元のデスティネーションボリュームの新しいデータが元のソースボリュームに転送されます。デスティネーション側のアクティブボリュームには引き続きアクセスしてデータを書き込むことができますが、元のプライマリ側にリダイレクトする前に、ソースボリュームとすべてのホストとの接続を切断し、 SnapMirror 更新を実行する必要があります。

. 作成した反転関係の [ アクション（ Actions ） ] アイコンをクリックし、 [ * 更新（ Update ） ] をクリックする。
+
これで逆再同期が完了しました。デスティネーション側のボリュームにアクティブなセッションが接続されておらず、元のプライマリボリュームに最新のデータが格納されていることを確認しました。 フェイルバックを完了し、元のプライマリボリュームを再アクティブ化するには、次の手順を実行します。

. 反転関係の [ アクション（ Actions ） ] アイコンをクリックし、 [ * 分割（ Break ） ] をクリックする。
. 元の関係の [Actions] アイコンをクリックし、 [* Resync] をクリックします。
+

NOTE: これで、元のプライマリボリュームをマウントして、元のプライマリボリュームで本番環境のワークロードを再開できるようになります。この関係に設定されているポリシーとスケジュールに基づいて、元の SnapMirror レプリケーションが再開されます。

. 元の関係のステータスが「拘束されていない」であることを確認したら、反転関係のアクションアイコンをクリックし、 * 削除 * をクリックします。




== 詳細については、こちらをご覧ください

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror フェイルバックのシナリオ]
