---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: 個々のノードをクラスタに追加する前に、ノードを設定する必要があります。ノードをラックユニットに設置してケーブル接続し、電源をオンにしたら、ノード UI またはノードのターミナルユーザインターフェイスを使用してノードのネットワーク設定を構成できます。 
---
= ストレージノードを設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
個々のノードをクラスタに追加する前に、ノードを設定する必要があります。ノードをラックユニットに設置してケーブル接続し、電源をオンにしたら、ノード UI またはノードのターミナルユーザインターフェイス（ TUI ）を使用してノードのネットワーク設定を設定できます。処理を続行する前に、ノードに必要なネットワーク設定情報があることを確認しておきます。

ストレージノードを設定する方法は 2 つあります。

* <<ノード UI を使用してストレージノードを設定します,ノード UI>>：ノード UI を使用します  ノードのネットワーク設定を構成します。
* <<TUI を使用してストレージノードを設定します,TUI>>：ノードのターミナルユーザインターフェイス（ TUI ）を使用してノードを設定します。


DHCP によって割り当てられた IP アドレスを使用するノードをクラスタに追加することはできません。DHCP IP アドレスは、ノード UI 、 TUI 、または API でノードの初期設定を行う際に使用します。この初期設定では、クラスタにノードを追加するための静的 IP アドレス情報を追加できます。

初期設定が完了したら、ノードの管理 IP アドレスを使用してノードにアクセスできます。その後、ノード設定を変更したり、クラスタにノードを追加したり、ノードを使用してクラスタを作成したりできます。また、 Element ソフトウェア API メソッドを使用して新しいノードを設定することもできます。


NOTE: Element バージョン 11.0 以降では、ノードの管理ネットワークに IPv4 、 IPv6 、または両方のアドレスを設定できます。この環境は、ストレージノードと管理ノードの両方に対応します。ただし、 IPv6 をサポートしない管理ノード 11.3 以降がこれに該当します。クラスタの作成時には、 IPv4 または IPv6 のどちらかのアドレスを 1 つだけ MVIP に使用でき、これと同じアドレスタイプをすべてのノードで設定する必要があります。



== ノード UI を使用してストレージノードを設定します

ノードはノードユーザインターフェイスを使用して設定できます。

.このタスクについて
* IPv4 アドレスまたは IPv6 アドレスを使用するようにノードを設定できます。
* ノードにアクセスするには、 TUI に表示される DHCP アドレスが必要です。DHCP アドレスを使用して、ノードをクラスタに追加することはできません。
+

IMPORTANT: 管理（ Bond1G ）インターフェイスとストレージ（ Bond10G ）インターフェイスは、別々のサブネットに設定する必要があります。Bond1G インターフェイスと Bond10G インターフェイスが同じサブネットに設定されている場合、ストレージトラフィックが Bond1G インターフェイス経由で送信されると、原因ルーティングの問題が発生します。管理トラフィックとストレージトラフィックに同じサブネットを使用する必要がある場合は、 Bond10G インターフェイスを使用するように管理トラフィックを手動で設定してください。ノード UI の * Cluster Settings * ページを使用して、ノードごとに設定を行うことができます。



.手順
. ブラウザウィンドウで、ノードの DHCP IP アドレスを入力します。
+
ノードにアクセスするには ' 拡張子の [ ： 442] を追加する必要がありますたとえば ' https://172.25.103.6:442[]。

+
「 * ネットワーク設定 * 」タブが開き、「 * Bond1G * 」セクションが表示されます。

. 1G 管理ネットワークの設定を入力します。
. [ 変更の適用 *] をクリックします。
. Bond10G * をクリックし、 10G ストレージのネットワーク設定を表示します。
. 10G ストレージのネットワーク設定を入力します。
. [ 変更の適用 *] をクリックします。
. [ クラスタ設定 ] をクリックします。
. 10G ネットワークのホスト名を入力します。
. クラスタ名を入力します。
+

IMPORTANT: クラスタを作成する前に、すべてのノードの構成にこの名前を追加する必要があります。クラスタ内のすべてのノードのクラスタ名が同じである必要があります。クラスタ名では大文字と小文字が区別されます。

. [ 変更の適用 *] をクリックします。




== TUI を使用してストレージノードを設定します

ターミナルユーザインターフェイス（ TUI ）を使用して、新しいノードの初期設定を実行できます。

Bond1G （管理）インターフェイスと Bond10G （ストレージ）インターフェイスは、別々のサブネットに設定する必要があります。同じサブネットに Bond1G インターフェイスと Bond10G インターフェイスを設定すると、ストレージトラフィックが Bond1G インターフェイス経由で送信される場合にルーティングの問題が発生します。管理トラフィックとストレージトラフィックに同じサブネットを使用する必要がある場合は、 Bond10G インターフェイスを使用するように管理トラフィックを手動で設定してください。これは、 Element UI の * Cluster * > * Nodes * ページを使用して、ノードごとに実行できます。

.手順
. キーボードとモニタをノードに接続し、ノードの電源をオンにします。
+
TUI の NetApp Storage Main メニューが tty1 ターミナルに表示されます。

+

NOTE: ノードが設定サーバにアクセスできない場合は、 TUI にエラーメッセージが表示されます。このエラーを解決するには、設定サーバの接続またはネットワーク接続を確認してください。

. * Network * > * Network Config * を選択します。
+

TIP: メニュー内を移動するには、上矢印キーまたは下矢印キーを押します。別のボタンまたはボタンからフィールドに移動するには、 *Tab* を押します。フィールド間を移動するには、上矢印キーまたは下矢印キーを使用します。

. ノードの 1G および 10G ネットワークを設定するには、「 * Bond1G （ Management ） * 」または「 * Bond10G （ Storage ） * 」を選択します。
. Bond モードと Status フィールドで、 * Tab * を押して Help ボタンを選択し、使用可能なオプションを特定します。
+
クラスタ内のすべてのノードのクラスタ名が同じである必要があります。クラスタ名では大文字と小文字が区別されます。使用可能な IP アドレスがあるネットワークで DHCP サーバを実行している場合は、 1GbE アドレスが Address フィールドに表示されます。

. *Tab* を押して *OK* ボタンを選択し、変更を保存します。
+
ノードが保留状態になり、既存のクラスタまたは新しいクラスタに追加できます。





== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

