---
permalink: setup/task_setup_create_a_storage_cluster.html 
sidebar: sidebar 
keywords:  
summary: 個々のノードの設定がすべて完了したら、ストレージクラスタを作成できます。クラスタを作成すると、クラスタ管理者のユーザアカウントが自動的に作成されます。クラスタ管理者は、すべてのクラスタ属性を管理する権限を持ち、他のクラスタ管理者アカウントを作成できます。 
---
= ストレージクラスタを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
個々のノードの設定がすべて完了したら、ストレージクラスタを作成できます。クラスタを作成すると、クラスタ管理者のユーザアカウントが自動的に作成されます。クラスタ管理者は、すべてのクラスタ属性を管理する権限を持ち、他のクラスタ管理者アカウントを作成できます。

.必要なもの
* 管理ノードをインストールしておきます。
* 個々のノードの設定をすべて完了しておきます。


各ノードには、設定時に 1G または 10G の管理 IP （ MIP ）アドレスが複数割り当てられています。Create a New Cluster ページを開くには、設定時に作成したノード IP アドレスのいずれかを使用する必要があります。使用する IP アドレスは、クラスタ管理用に選択したネットワークによって異なります。


IMPORTANT: クラスタ全体で有効にする場合 link:../concepts/concept_solidfire_concepts_security.html#encryption-at-rest-software["ソフトウェアによる保存データの暗号化"]を使用してクラスタを作成する必要があります link:../api/reference_element_api_createcluster.html["クラスタを作成"] 代わりに API メソッドを使用して、 enableSoftwareEncryptionAtRest パラメータを「 true 」に変更します。保存データのソフトウェア暗号化を有効にしたあとは、クラスタで無効にすることはできません。SolidFire ESDS クラスタでは、保存データのソフトウェア暗号化がデフォルトで有効になっています。保存データのハードウェアベースの暗号化は、の場合もあります link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["有効と無効を切り替えます"] クラスタの作成後：

[NOTE]
====
新しいクラスタを作成するときは、次の点を考慮してください。

* 共有シャーシにあるストレージノードを使用する場合は、保護ドメイン機能を使用したシャーシレベルの障害からの保護を設計することを検討してください。
* 共有シャーシが使用されていない場合は、カスタム保護ドメインレイアウトを定義できます。


====
.手順
. ブラウザ・ウィンドウに「 \https://MIP:443` 」と入力します。 MIP は管理ノードの IP アドレスです。
. Create a New Cluster （新しいクラスタの作成）で、次の情報を入力します。
+
** Management VIP ：ネットワーク管理タスク用の、 1GbE または 10GbE ネットワーク上のルーティング可能な仮想 IP 。
+

NOTE: 新しいクラスタは IPv4 または IPv6 のアドレスを使用して作成できます。

** iSCSI （ storage ） VIP ：ストレージおよび iSCSI 検出用の 10GbE ネットワーク上の仮想 IP 。
+

NOTE: クラスタを作成したあとに MVIP 、 SVIP 、またはクラスタ名を変更することはできません。

** User name ：クラスタへの認証されたアクセスに使用するプライマリクラスタ管理者ユーザ名。あとで参照できるように、ユーザ名を保存しておく必要があります。
+

NOTE: ユーザ名とパスワードには、大文字と小文字のアルファベット、特殊文字、および数字を使用できます。

** Password ：クラスタへの認証されたアクセスに使用するパスワード。あとで参照できるようにパスワードを保存しておく必要があります。双方向のデータ保護がデフォルトで有効になります。この設定は変更できません。


. エンドユーザライセンス契約を読み、「同意する」を選択します。
. * オプション * ：ノードリストで、クラスタに含めないノードのチェックボックスが選択されていないことを確認します。
. Create Cluster （クラスタの作成） * を選択します。
+
クラスタ内のノードの数によっては、クラスタの作成に数分かかることがあります。適切に設定したネットワークで、 5 ノードの小規模なクラスタを作成する場合の所要時間は 1 分未満です。クラスタが作成されると、 Create a New Cluster ウィンドウがクラスタの MVIP URL アドレスにリダイレクトされ、 Element UI が表示されます。





== を参照してください。

* link:../api/index.html["Element API を使用してストレージを管理する"]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

