---
permalink: setup/task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.html 
sidebar: sidebar 
keywords:  
summary: 個々の Fibre Channel ノードの設定が完了したら、新しいクラスタを作成できます。クラスタを作成すると、クラスタ管理者のユーザアカウントが自動的に作成されます。クラスタ管理者は、すべてのクラスタ属性を管理する権限を持ち、他のクラスタ管理者アカウントを作成できます。 
---
= Fibre Channel ノードを含む新しいクラスタを作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
個々の Fibre Channel ノードの設定が完了したら、新しいクラスタを作成できます。クラスタを作成すると、クラスタ管理者のユーザアカウントが自動的に作成されます。クラスタ管理者は、すべてのクラスタ属性を管理する権限を持ち、他のクラスタ管理者アカウントを作成できます。

各ノードには、設定時に 1G または 10G の管理 IP （ MIP ）アドレスが複数割り当てられています。Create a New Cluster ページを開くには、設定時に作成したノード IP アドレスのいずれかを使用する必要があります。使用する IP アドレスは、クラスタ管理用に選択したネットワークによって異なります。

個々の Fibre Channel ノードの設定を完了しておきます。

.手順
. ブラウザウィンドウで、ノードの MIP アドレスを入力します。
. Create a New Cluster （新しいクラスタの作成）で、次の情報を入力します。
+
** Management VIP ：ネットワーク管理タスク用の、 1GbE または 10GbE ネットワーク上のルーティング可能な仮想 IP 。
** iSCSI （ storage ） VIP ：ストレージおよび iSCSI 検出用の 10GbE ネットワーク上の仮想 IP 。
+

NOTE: クラスタを作成したあとに SVIP を変更することはできません。

** User name ：クラスタへの認証されたアクセスに使用するプライマリクラスタ管理者ユーザ名。あとで参照できるように、ユーザ名を保存しておく必要があります。
+

NOTE: ユーザ名には、大文字と小文字のアルファベット、特殊文字、および数字を使用できます。

** Password ：クラスタへの認証されたアクセスに使用するパスワード。あとで参照できるように、ユーザ名を保存しておく必要があります。双方向のデータ保護がデフォルトで有効になります。この設定は変更できません。


. エンドユーザライセンス契約を読み、 [* I Agree* （同意する） ] をクリックします。
. * オプション * ：ノードリストで、クラスタに含めないノードのチェックボックスが選択されていないことを確認します。
. [ クラスタの作成 ] をクリックします。
+
クラスタ内のノードの数によっては、クラスタの作成に数分かかることがあります。適切に設定したネットワークで、 5 ノードの小規模なクラスタを作成する場合の所要時間は 1 分未満です。クラスタの作成が完了すると、 Create a New Cluster ウィンドウがクラスタの MVIP URL アドレスにリダイレクトされ、 Web UI が表示されます。





== 詳細については、こちらをご覧ください

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire and Element Resources ページにアクセスします"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

