---
permalink: esds/reference_esds_use_maintenance_mode.html 
sidebar: sidebar 
keywords: element, solidfire esds, maintenance, maintenance mode 
summary: ソフトウェアのアップグレードやホストの修復などのメンテナンスのためにストレージノードをオフラインにする必要がある場合は、そのノードのメンテナンスモードを有効にすることで、ストレージクラスタの残りの部分への I/O の影響を最小限に抑えることができます。 
---
= SolidFire ESDS クラスタではメンテナンスモードを使用します
:icons: font
:imagesdir: ../media/


[role="lead"]
ソフトウェアのアップグレードやホストの修復などのメンテナンスのためにストレージノードをオフラインにする必要がある場合は、そのノードのメンテナンスモードを有効にすることで、ストレージクラスタの残りの部分への I/O の影響を最小限に抑えることができます。


TIP: ノードの保守モードの現在のステータスを確認する場合は、を使用します link:../api/reference_element_api_listactivenodes.html["「 ListActiveNodes 」"^] API メソッド。node オブジェクトには、ノードの保守モードの現在のステータスを示す「 maintenanceMode 」パラメータが含まれています。


NOTE: メンテナンスモードを有効にしたらすぐにメンテナンスを実行してください。ノードを必要以上に保守モードのままにしないでください。

ストレージノードを保守モードに移行できるのは、ノードが正常で（クラスタエラーがブロックされていない）、かつストレージクラスタが単一ノード障害に対応している場合のみです。正常なトレラントノードに対してメンテナンスモードをイネーブルにすると、ノードはすぐには移行されません。ノードは、次の条件が満たされるまで監視されます。

* ノードでホストされているすべてのボリュームがフェイルオーバーされ、そのノードがどのボリュームのプライマリとしてもホストしていない状態になります。
* 一時スタンバイノードは、対象のすべてのボリュームに割り当てられます フェイルオーバーしました


これらの条件を満たすと、ノードは保守モードに移行します。5 分以内に上記の条件が満たされないと、ノードは保守モードになりません。

ストレージノードのメンテナンスモードを無効にすると、次の条件が満たされるまでノードが監視されます。

* すべてのデータがノードに完全にレプリケートされます
* ブロックしているクラスタのすべての障害が解決されます
* ホストされているボリュームに対する一時的なスタンバイノードの割り当て ノードが非アクティブ化されました


これらの条件を満たしている場合、ノードはメンテナンスモードから移行されます。1 時間以内に上記の条件を満たしていないと、ノードのメンテナンスモードからの移行が失敗します。



== メンテナンスモードの使用中に発生する可能性があるシナリオ

* ノードがメンテナンスモードで、まだリブートされていない場合やメンテナンスが発生していない場合、またはメンテナンスが発生してバックアップも正常に実行されているがメンテナンスモードが無効になっていない場合は、 もう一方のノードが停止すると、最初のノードのメンテナンスモードが自動的に無効になります。
* いずれかのノードがメンテナンスモードになっているときに、別のノードが同時に停止すると、システムが停止します。保守モードになっているノードがオンラインに戻るまで待つ必要があります。
* アンサンブルのメンバーであるノードを長期間メンテナンスモードにすると、他のノードを追加できる場合、そのノードはアンサンブルから自動的に削除されます。




== メンテナンスモードを有効にします

メンテナンス・モードは 'EnableMaintenanceMode'API メソッドを使用して有効にできますこのメソッドの入力パラメータは次のとおりです。

[cols="5*"]
|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
forceWithUnresolvedFaults
 a| 
クラスタ障害がブロックされている場合でも、このノードに対して強制的にメンテナンスモードを有効にします。
 a| 
ブール値
 a| 
いいえ
 a| 
いいえ



 a| 
「 nodes 」
 a| 
保守モードにするノード ID のリスト。一度に 1 つのノードのみがサポートされます。
 a| 
整数の配列
 a| 
なし
 a| 
はい。



 a| 
「 perMinutePrimarySwapLimit 」
 a| 
1 分間にスワップするプライマリスライスの数。指定しない場合、すべてのプライマリスライスが一度にスワップされます。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
タイムアウト
 a| 
メンテナンスモードが自動的に無効になるまで有効にしておく期間を指定します。時間文字列（ HH ： MM ： ss など）でフォーマットされます。指定しない場合、保守モードは明示的に無効にするまで有効なままになります。
 a| 
文字列
 a| 
なし
 a| 
いいえ

|===
このメソッドの戻り値は次のとおりです。

[cols="3*"]
|===
| 名前 | 説明 | を入力します 


 a| 
「 asyncHandle 」
 a| 
「 GetAsyncResult 」メソッドを使用してこの asyncHandle を取得し、メンテナンスモードの移行が完了したかどうかを判断できます。
 a| 
整数



 a| 
「 currentMode 」
 a| 
ノードの現在の保守モードの状態。有効な値は次のとおり

* 無効：メンテナンスは要求されていません。
* FailedToRecover ：ノードのメンテナンスモードからのリカバリに失敗しました。
* RecoveringFromMaintenance ：ノードはメンテナンスモードからリカバリ中です。
* 準備メンテナンス：ノードのメンテナンスを実施するための準備作業を実施します。
* ReadyForMaintenance ：ノードのメンテナンスを実行できる状態です。

 a| 
MaintenanceMode ( 文字列 )



 a| 
「質問モード」
 a| 
ノードに対して要求されたメンテナンスモードの状態。有効な値は次のとおり

* 無効：メンテナンスは要求されていません。
* FailedToRecover ：ノードのメンテナンスモードからのリカバリに失敗しました。
* RecoveringFromMaintenance ：ノードはメンテナンスモードからリカバリ中です。
* 準備メンテナンス：ノードのメンテナンスを実施するための準備作業を実施します。
* ReadyForMaintenance ：ノードのメンテナンスを実行できる状態です。

 a| 
MaintenanceMode ( 文字列 )

|===


== メンテナンスモードを無効にします

メンテナンスモードを無効にするには、「 D isableMaintenanceMode 」 API メソッドを使用します。このメソッドの入力パラメータは次のとおりです。

[cols="5*"]
|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
「 nodes 」
 a| 
メンテナンスモードから解除するストレージノード ID のリスト。
 a| 
整数の配列
 a| 
なし
 a| 
はい。

|===
このメソッドの戻り値は次のとおりです。

[cols="3*"]
|===
| 名前 | 説明 | を入力します 


 a| 
「 asyncHandle 」
 a| 
「 GetAsyncResult 」メソッドを使用してこの asyncHandle を取得し、メンテナンスモードの移行が完了したかどうかを判断できます。
 a| 
整数



 a| 
「 currentMode 」
 a| 
ノードの現在の保守モードの状態。有効な値は次のとおり

* 無効：メンテナンスは要求されていません。
* FailedToRecover ：ノードのメンテナンスモードからのリカバリに失敗しました。
* Unexpected ：ノードがオフラインであることが検出されましたが、無効モードでした。
* RecoveringFromMaintenance ：ノードはメンテナンスモードからリカバリ中です。
* 準備メンテナンス：ノードのメンテナンスを実施するための準備作業を実施します。
* ReadyForMaintenance ：ノードのメンテナンスを実行できる状態です。

 a| 
MaintenanceMode ( 文字列 )



 a| 
「質問モード」
 a| 
ノードに対して要求されたメンテナンスモードの状態。有効な値は次のとおり

* 無効：メンテナンスは要求されていません。
* FailedToRecover ：ノードのメンテナンスモードからのリカバリに失敗しました。
* Unexpected ：ノードがオフラインであることが検出されましたが、無効モードでした。
* RecoveringFromMaintenance ：ノードはメンテナンスモードからリカバリ中です。
* 準備メンテナンス：ノードのメンテナンスを実施するための準備作業を実施します。
* ReadyForMaintenance ：ノードのメンテナンスを実行できる状態です。

 a| 
MaintenanceMode ( 文字列 )

|===


== 詳細については、こちらをご覧ください

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire のリソースページ"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["以前のバージョンの NetApp SolidFire 製品および Element 製品に関するドキュメント"^]

