---
permalink: esds/reference_esds_sf_sds_config_file.html 
sidebar: sidebar 
keywords: element, solidfire esds, hardware components, configuration file 
summary: すべてのノードには sf_sds_config.yaml ファイルがあります。このファイルには、 SolidFire ESDS サービスで使用するように指定するハードウェアのリストが含まれています。ドライブを交換したら、ドライブを交換したノードのこのファイルに交換用ドライブの情報を追加する必要があります。このファイルは /opt/sf/sf/ に保存されます。このファイルには、ノード内のドライブに関するすべての情報が含まれます。新しいドライブを追加するたびに、このファイルに新しいドライブの詳細を入力する必要があります。 
---
= sf_sds_config.yaml ファイルの内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのノードには 'sf_sds_config.yaml ファイルがありますこのファイルには ' SolidFire ESDS サービスで使用するように指定するハードウェアのリストが含まれていますドライブを交換したら、このファイルにドライブを交換するノードの交換用ドライブ情報を追加する必要があります。このファイルは '/opt/sf/` に保存されますこのファイルには、ノード内のドライブに関するすべての情報が含まれます。新しいドライブを追加するたびに、このファイルに新しいドライブの詳細を入力する必要があります。

ファイルの * 必須 * の内容は次のとおりです。

[cols="4*"]
|===
| キーを押します | デフォルト | を入力します | 説明 


 a| 
schemaVersion
 a| 
"2.0"
 a| 
文字列
 a| 
ファイルのスキーマバージョン番号。



 a| 
ネットワーク
 a| 
該当なし
 a| 
リスト
 a| 
指定できる値は、 ManagementInterface 、 storageInterface です



 a| 
管理インターフェイス
 a| 
"team0"
 a| 
文字列
 a| 
管理トラフィックとクラスタ管理トラフィックに使用する、事前に設定された冗長なホスト OS ネットワークインターフェイスの名前。



 a| 
ストレージインターフェイス
 a| 
" チーム 1"
 a| 
文字列
 a| 
ストレージネットワークトラフィック（ iSCSI トラフィック）に使用する、事前に設定された冗長なホスト OS ネットワークインターフェイスの名前。



 a| 
データドライブ
 a| 
該当なし
 a| 
リスト
 a| 
SolidFire ESDS で使用されている物理ストレージデバイスへのホスト OS パスのリスト。これをブロックデバイスまたは NVMe デバイスへの完全なパスとして指定できます。完全なパスの例として、 /dev/disk/by-id/wwn-xxxx-xxxx - 例、 /dev/disk/by-uuid/nvme-xxxxx-xxx-example 、 /dev/sda1 がサポートされています



 a| 
キャッシュデバイス
 a| 
該当なし
 a| 
リスト
 a| 
SolidFire ESDS によってキャッシュデバイスとして使用されている物理デバイスへのホスト OS パス。リストエントリとして指定する必要があります。サポートされる完全なパスの例を次に示します。 /dev/disk/by-id/nvme-nvme.8086-XXXXXXXXX -XXXXXX-example

|===


== 詳細については、こちらをご覧ください

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire のリソースページ"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["以前のバージョンの NetApp SolidFire 製品および Element 製品に関するドキュメント"^]

