---
permalink: esds/task_esds_uninstall.html 
sidebar: sidebar 
keywords: solidfire esds, uninstalling solidfire esds, ansible role 
summary: ノード上の SolidFire ESDS を削除することで、 SolidFire ESDS をインストールしたノードを「リセット」できます。ノードで SolidFire ESDS を復元するには、すべてのインストール手順を実行する必要があります。 
---
= ノードで SolidFire ESDS をアンインストールします
:icons: font
:imagesdir: ../media/


[role="lead"]
ノード上の SolidFire ESDS を削除することにより、 SolidFire ESDS をインストールしたノードを * リセット * できます。ノードで SolidFire ESDS を復元するには、すべてのインストール手順を実行する必要があります。


NOTE: を使用できます link:https://github.com/NetApp-Automation/nar_solidfire_sds_uninstall["「 nar_solidfire_sds_uninstall 」"^] 処理を実行するためにネットアップが提供する Ansible のロール。ノードから SolidFire ESDS を手動で削除する場合は、次の手順を参照してください。

.手順
. Element UI またはを使用してクラスタからドライブを削除します https://docs.netapp.com/us-en/element-software/docs/api/reference_element_api_removedrives.html["「 RemoveDrives 」を参照してください"^] API メソッド。
+
その結果、ノードのドライブからクラスタ内の他のドライブへデータが移行されます。このプロセスにかかる時間は、移行が必要なデータの量によって異なります。

. Element UI またはを使用して、クラスタからノードを削除します https://docs.netapp.com/us-en/element-software/docs/api/reference_element_api_removenodes.html["「 RemoveNodes 」"^] API メソッド。
. インベントリファイルで定義したホスト（ノード）に ping を実行して、 Ansible がそれらのホストと通信できることを確認します。
. 次のように、ノードから SolidFire ESDS を削除します。
+
[listing]
----
yum remove solidfire-element
----
. 次の手順でディレクトリから永続データを削除します。
+
[listing]
----
rm -rf /opt/sf
----




== 詳細については、こちらをご覧ください

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire のリソースページ"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["以前のバージョンの NetApp SolidFire 製品および Element 製品に関するドキュメント"^]

