---
permalink: api/concept_element_api_asynchronous_methods.html 
sidebar: sidebar 
keywords: async,asynchronous,methods,API 
summary: 一部の API メソッドは非同期です。つまり、 API メソッドで実行される処理は、メソッドが戻るときにまだ完了していない可能性があります。非同期メソッドは、処理のステータスを照会して確認できるハンドルを返します。一部の処理のステータス情報には、進捗状況が含まれることがあります。 
---
= 非同期メソッド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一部の API メソッドは非同期です。つまり、 API メソッドで実行される処理は、メソッドが戻るときにまだ完了していない可能性があります。非同期メソッドは、処理のステータスを照会して確認できるハンドルを返します。一部の処理のステータス情報には、進捗状況が含まれることがあります。

非同期処理を照会すると、次のいずれかの結果が返されます。

* 「ドライブ追加」：システムがドライブをクラスタに追加しています。
* 「 BulkVolume 」：システムは、バックアップやリストアなどのボリューム間でコピー操作を実行しています。
* Clone ：システムはボリュームを複製しています。
* 「削除」 : クラスタからドライブを削除する準備として、ドライブからデータをコピーしています。
* RtfiPendingNode: クラスタにノードを追加する前に、互換性のあるソフトウェアをノードにインストールしています。


非同期メソッドを使用したり実行中の非同期処理のステータスを取得したりするときは、次の点に注意してください。

* 非同期メソッドについては、個々のメソッドの説明を参照してください。
* 非同期メソッドは「 asyncHandle 」を返します。これは、 API メソッドを発行することで得られるハンドルです。このハンドルを使用して、非同期処理のステータスまたは結果をポーリングできます。
* 個々の非同期メソッドの結果は、 GetAsyncResult メソッドを使用して取得できます。GetAsyncResult を使用して完了済みの処理を照会すると、結果が返されます。その結果はシステムから自動的に破棄されます。GetAsyncResult を使用して未完了の処理を照会すると、結果は返されますが破棄されません。
* 実行中または完了済みの非同期メソッドすべてのステータスおよび結果を取得するには、 ListAsyncResults メソッドを使用します。この場合、完了済みの処理の結果は破棄されません。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["以前のバージョンの NetApp SolidFire 製品および Element 製品に関するドキュメント"^]

