---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: ListAuthSessionsByUsername メソッドを使用すると、指定したユーザのすべての認証セッションを一覧表示できます。AccessGroup ClusterAdmins/Administrator 権限を持たない発信者は、自身のセッションだけを表示できます。ClusterAdmins/Administrator 権限を持つ呼び出し側は、任意のユーザに属するセッションを表示できます。 
---
= ListAuthSessionsByUsername のユーザ名
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 ListAuthSessionsByUsername 」メソッドを使用すると、指定したユーザのすべての認証セッションを一覧表示できます。AccessGroup ClusterAdmins/Administrator 権限を持たない発信者は、自身のセッションだけを表示できます。ClusterAdmins/Administrator 権限を持つ呼び出し側は、任意のユーザに属するセッションを表示できます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
使用します
 a| 
表示するユーザセッションの認証方式。このパラメータを指定できるのは、 ClusterAdmins または Administrator AccessGroup 内の呼び出し元だけです。有効な値は次のとおりです。

* *authMethod=Cluster* は、 ClusterAdmin ユーザ名を指定します。
* *authMethod=LDAP* には、ユーザの LDAP DN を指定します。
* * authMethod=IDP * には、ユーザの IdP UUID または NameID を指定します。どちらのオプションも返すように IdP が設定されていない場合は、セッションの作成時に発行されたランダム UUID を指定します。

 a| 
使用します
 a| 
なし
 a| 
はい。



 a| 
ユーザ名
 a| 
ユーザの一意の識別子。
 a| 
文字列
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
セッション
 a| 
認証セッションのセッション情報のリスト。
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== 新規導入バージョン

12.0
