---
permalink: api/reference_element_api_removenodes.html 
sidebar: sidebar 
keywords: node,nodes,cluster,remove,removing,removenodes 
summary: RemoveNodes を使用すると、クラスタで不要になった 1 つ以上のノードを削除できます。 
---
= RemoveNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RemoveNodes を使用すると、クラスタに参加しなくなった 1 つ以上のノードを削除できます。

ノードを削除する前に、 RemoveDrives メソッドを使用してノードに含まれるすべてのドライブを削除する必要があります。RemoveDrives プロセスが完了してすべてのデータがノードから移行されるまで、ノードを削除することはできません。ノードを削除すると、削除したノードは Pending 状態のノードとして登録されます。ノードは再度追加するか、シャットダウンできます（ノードをシャットダウンすると、 Pending 状態のノードのリストから削除されます）。



== クラスタマスターノードの削除

RemoveNodes を使用してクラスタマスターノードを削除すると、応答を返す前にメソッドがタイムアウトすることがあります。メソッドがノードの削除に失敗した場合は、メソッドを再度実行してください。クラスタマスターノードを他のノードと一緒に削除する場合は、クラスタマスターノードだけを別の呼び出しで削除する必要があります。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ignoreEnsembleToleranceChange
 a| 
ノードを削除するときにアンサンブルのノード障害許容値に対する変更を無視します。

複数のノードで障害が発生した場合にノードを削除すると、アンサンブルのノード障害許容値が低下するデータ保護方式がストレージクラスタで使用されていると、ノードの削除がエラーで失敗します。このパラメータを true に設定すると、ノード削除が正常に実行されるようにアンサンブルのトレランスチェックを無効にできます。
 a| 
ブール値
 a| 
いいえ
 a| 
いいえ



 a| 
ノード
 a| 
削除するノードの ID のリスト。
 a| 
整数の配列
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドには戻り値はありません。



== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "RemoveNodes",
   "params": {
     "nodes"  : [3,4,5]
   },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id" : 1
  "result" : {},
}
----


== 新規導入バージョン

9.6
