---
permalink: api/reference_element_api_getvolumeefficiency.html 
sidebar: sidebar 
keywords: volume,volumes,get,getting,stats,measurements,efficiency,GetVolumeEfficiency 
summary: GetVolumeEfficiency メソッドを使用すると、ボリュームの情報を取得できます。容量の計算には、この API メソッドのパラメータとして指定したボリュームのみが使用されます。 
---
= GetVolumeEfficiency を使用します
:icons: font
:imagesdir: ../media/


[role="lead"]
GetVolumeEfficiency メソッドを使用すると、ボリュームに関する情報を取得できます。容量の計算には、この API メソッドのパラメータとして指定したボリュームのみが使用されます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ボリューム ID
 a| 
容量を計算するボリュームを指定します。
 a| 
整数
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
圧縮
 a| 
単一のボリュームのデータを圧縮することで節約されるスペース量。値は比率で示され、「 1 」はデータが圧縮されずに格納されたことを意味します。
 a| 
浮動小数点



 a| 
重複排除
 a| 
1 つのボリュームでデータを重複排除することによって節約される容量。比率として示されます。
 a| 
浮動小数点



 a| 
missingVolumes
 a| 
効率性に関するデータを照会できなかったボリューム。原因としては、ガベージコレクション（ GC ）から 1 時間経過していない、一時的なネットワーク接続の切断、または GC サイクル後のサービスの再起動があります。
 a| 
整数の配列



 a| 
シンプロビジョニング
 a| 
使用済みスペースとデータの格納用に割り当てられたスペースの比率。比率として示されます。
 a| 
浮動小数点



 a| 
タイムスタンプ
 a| 
GC 後に効率性に関するデータが収集された最後の時刻。
 a| 
ISO 8601 形式の日付文字列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "GetVolumeEfficiency",
   "params": {
      "volumeID": 606
   },
   "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.001591240821456,
       "deduplication": 1,
       "missingVolumes": [],
       "thinProvisioning": 1.009861932938856,
       "timestamp": "2014-03-10T16:06:33Z"
   }
}
----


== 新規導入バージョン

9.6
