---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: StartVolumePairing メソッドを使用すると、別のボリュームとのペアリングに使用されるボリュームからエンコードされたキーを作成できます。このメソッドで作成されるキーは、 CompleteVolumePairing メソッドでボリュームペアリングを確立するために使用されます。 
---
= StartVolumePairing を参照してください
:icons: font
:imagesdir: ../media/


[role="lead"]
「 artVolumePairing 」メソッドを使用すると、別のボリュームとのペアリングに使用されるボリュームからエンコードされたキーを作成できます。このメソッドで作成されるキーは、「 CompleteVolumePairing 」メソッドでボリュームペアリングを確立するために使用されます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
モード
 a| 
ペアリングプロセスを開始するボリュームのモード。ボリュームがソースボリュームの場合のみ、モードを設定できます。有効な値は次のとおり

* Async ：ローカルで書き込みが完了した時点で、書き込みが確認されます。ターゲットクラスタに書き込みがレプリケートされるのを待たずに、書き込み完了として通知されます。（ mode パラメータを指定しない場合のデフォルト）
* 'sync' ：ソースは、データがローカルクラスタとリモートクラスタの両方に格納された時点で、書き込みを確認します。
* 「 snapmirror shotsOnly 」：ソースクラスタで作成された Snapshot のみがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。

 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
ボリューム ID
 a| 
ペアリングプロセスを開始するボリュームの ID 。
 a| 
整数
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
volumePairingKey のように指定します
 a| 
によって使用される文字列 xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] API メソッド。
 a| 
文字列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
