---
permalink: api/reference_element_api_getaccountefficiency.html 
sidebar: sidebar 
keywords: accounts,account,efficiency,get,getting,GetAccountEfficiency 
summary: GetAccountEfficiency を使用すると、ボリュームアカウントの効率性に関する統計を取得できます。このメソッドは、パラメータとして指定したアカウントについてのみ、効率性に関する情報を返します。 
---
= GetAccountEfficiency
:icons: font
:imagesdir: ../media/


[role="lead"]
GetAccountEfficiency を使用すると、ボリュームアカウントの効率性に関する統計を取得できます。このメソッドは、パラメータとして指定したアカウントについてのみ、効率性に関する情報を返します。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
アカウント ID
 a| 
効率性に関する統計を取得するボリュームアカウントを指定します。
 a| 
整数
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
圧縮
 a| 
アカウント内のすべてのボリュームの、データ圧縮によって削減された容量。値は比率で示され、「 1 」はデータが圧縮されずに格納されたことを意味します。
 a| 
浮動小数点



 a| 
重複排除
 a| 
アカウントのすべてのボリュームの、データの重複排除によって削減された容量。比率として示されます。
 a| 
浮動小数点



 a| 
missingVolumes
 a| 
効率性に関するデータを照会できなかったボリューム。原因としては、ガベージコレクション（ GC ）サイクルから 1 時間経過していない、一時的なネットワーク接続の切断、または GC サイクル後のサービスの再起動があります。
 a| 
整数の配列



 a| 
シンプロビジョニング
 a| 
使用済みスペースとデータの格納用に割り当てられたスペースの比率。比率として示されます。
 a| 
浮動小数点



 a| 
タイムスタンプ
 a| 
ガベージコレクション（ GC ）後に効率性に関するデータが収集された前回の時刻（ UTC+0 形式）。
 a| 
ISO 8601 形式の日付文字列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "GetAccountEfficiency",
   "params": {
     "accountID": 3
   },
   "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.020468042933262,
       "deduplication": 2.042488619119879,
       "missingVolumes": [],
       "thinProvisioning": 1.010087163391013,
       "timestamp": "2014-03-10T14:06:02Z"
   }
}
----


== 新規導入バージョン

9.6
