---
permalink: api/reference_element_api_setprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,setting protection domains 
summary: SetProtectionDomainLayout メソッドを使用すると、カスタム保護ドメインにノードを割り当てることができます。 
---
= SetProtectionDomainLayout の略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 setProtectionDomainLayout 」メソッドを使用すると、カスタム保護ドメインにノードを割り当てることができます。

クラスタ内のすべてのアクティブノードに関する情報を指定する必要があります。また、アクティブでないノードについては情報を指定できません。同じシャーシ内のすべてのノードを同じカスタム保護ドメインに割り当てる必要があります。すべてのノードに同じ protectionDomainType を指定する必要があります。ノードやシャーシなど、カスタムではない protectionDomainTypes は含めないでください。これらのいずれかを指定すると、カスタムの保護ドメインは無視され、該当するエラーが返されます。


NOTE: カスタム保護ドメインは、次の構成ではサポートされません。

* 共有シャーシを含むストレージクラスタ
* 2 ノードストレージクラスタ


メソッドを使用すると、これらの構成のストレージクラスタでエラーが返されます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
protectionDomainLayout の略
 a| 
各ノードの保護ドメイン情報。
 a| 
の JSON リスト link:reference_element_api_nodeprotectiondomains.html["nodeProtectionDomains"] オブジェクト。
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
protectionDomainLayout の略
 a| 
各ノードとそれに関連付けられた保護ドメインのリスト。
 a| 
の JSON リスト link:reference_element_api_nodeprotectiondomains.html["nodeProtectionDomains"] オブジェクト。

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "id": 1,
  "method": "SetProtectionDomainLayout",
  "params": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== 新規導入バージョン

12.0
