---
permalink: api/reference_element_api_addvirtualnetwork.html 
sidebar: sidebar 
keywords: addvirtualnetwork,cluster,add,adding,virtual,network 
summary: AddVirtualNetwork メソッドを使用して、クラスタ構成に新しい仮想ネットワークを追加できます。 
---
= AddVirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 AddVirtualNetwork 」メソッドを使用して、クラスタ構成に新しい仮想ネットワークを追加できます。

仮想ネットワークを追加すると、各ノードのインターフェイスが作成され、その各インターフェイスに仮想ネットワーク IP アドレスが必要となります。この API メソッドのパラメータとして指定する IP アドレスの数は、クラスタ内のノードの数以上であることが必要です。仮想ネットワークアドレスは一括でプロビジョニングされ、個々のノードに自動的に割り当てられます。仮想ネットワークアドレスをノードに手動で割り当てる必要はありません。


NOTE: AddVirtualNetwork メソッドは、新しい仮想ネットワークを作成するためだけに使用されます。既存の仮想ネットワークに変更を加える場合は、を使用します xref:reference_element_api_modifyvirtualnetwork.adoc[ModifyVirtualNetwork] メソッド



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
アドレスブロック
 a| 
仮想ネットワークに含める一意の IP アドレス範囲。オブジェクトの必須のメンバーは次のとおりです。

* start ： IP アドレス範囲の開始アドレス文字列
* size ：ブロックに含める IP アドレスの数整数

 a| 
JSON オブジェクトの配列
 a| 
なし
 a| 
はい。



 a| 
属性（ Attributes ）
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSON オブジェクト
 a| 
なし
 a| 
いいえ



 a| 
ゲートウェイ
 a| 
仮想ネットワークのゲートウェイの IP アドレスです。このパラメータは、 namespace パラメータを true に設定した場合のみ有効です。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
名前
 a| 
新しい仮想ネットワークのユーザ定義名。
 a| 
文字列
 a| 
なし
 a| 
はい。



 a| 
ネームスペース
 a| 
true に設定すると、ネームスペースとそこに含まれる仮想ネットワークが作成および構成されることで、ルーティング可能ストレージ VLAN 機能が有効になります。
 a| 
ブール値
 a| 
なし
 a| 
いいえ



 a| 
ネットマスク
 a| 
作成中の仮想ネットワークに一意のネットワークマスク。
 a| 
文字列
 a| 
なし
 a| 
はい。



 a| 
svip
 a| 
作成する仮想ネットワークに一意のストレージ IP アドレス。
 a| 
文字列
 a| 
なし
 a| 
はい。



 a| 
virtualNetworkTag
 a| 
一意の仮想ネットワーク（ VLAN ）タグ。サポートされる値は 1~4094 です。
 a| 
整数
 a| 
なし
 a| 
はい。

|===
* 注： * namespace を false に設定するときは、仮想ネットワークごとに仮想ネットワークのパラメータを一意にする必要があります。



== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
virtualNetworkID
 a| 
新しい仮想ネットワークの仮想ネットワーク ID 。
 a| 
整数

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "AddVirtualNetwork",
  "params": {
    "virtualNetworkTag": 2010,
    "name": "network1",
    "addressBlocks" : [
        { "start": "192.86.5.1", "size": 10 },
        { "start": "192.86.5.50", "size": 20 }
    ],
    "netmask" : "255.255.192.0",
    "gateway" : "10.0.1.254",
    "svip" : "192.86.5.200",
    "attributes" : {}
    "namespace" : true
  },
"id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id": 1,
   "result":
      {
        "virtualNetworkID": 5
   }
}
----


== 新規導入バージョン

9.6
