---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: ListVolumes メソッドを使用すると、クラスタ内のボリュームのリストを取得できます。パラメータを使用して、リストで返すボリュームを指定できます。 
---
= ListVolumes の場合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ListVolumes メソッドを使用すると、クラスタ内のボリュームのリストを取得できます。パラメータを使用して、リストで返すボリュームを指定できます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
アカウント
 a| 
ここで指定したアカウントが所有するボリュームのみが返されます。volumeIDs パラメータと同時に指定することはできません。
 a| 
整数の配列
 a| 
なし
 a| 
いいえ



 a| 
includeVirtualVolumes などです
 a| 
デフォルトでは仮想ボリュームは応答に含まれます。仮想ボリュームを除外するには、 false に設定します。
 a| 
ブール値
 a| 
正しいです
 a| 
いいえ



 a| 
障害があります
 a| 
ペアリングされているボリュームまたはペアリングされていないボリュームを返します有効な値は次のとおり

* true ：ペアリングされているすべてのボリュームを返します。
* false ：ペアリングされていないすべてのボリュームを返します。

 a| 
ブール値
 a| 
なし
 a| 
いいえ



 a| 
制限（ Limit ）
 a| 
返されるボリューム数を設定できます。volumeIDs パラメータと同時に指定することはできません。
 a| 
整数
 a| 
10000
 a| 
いいえ



 a| 
startVolumeID
 a| 
ID の値が指定した値以上のボリュームのみが返されます。volumeIDs パラメータと同時に指定することはできません。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
ボリューム ID
 a| 
ボリューム ID のリスト。このパラメータを指定すると、他のパラメータはこのパラメータで指定したボリュームに対してのみ適用されます。accounts 、 startVolumeID 、 limit パラメータと同時に指定することはできません。
 a| 
整数の配列
 a| 
いいえ
 a| 
いいえ



 a| 
ボリューム名
 a| 
ボリューム名が一致するボリュームのオブジェクト情報のみが返されます。
 a| 
文字列
 a| 
いいえ
 a| 
いいえ



 a| 
ボリュームステータス
 a| 
ステータス値が等しいボリュームのみが返されます。有効な値は次のとおり

* 作成中です
* スナップショット
* アクティブ
* 削除済み

 a| 
文字列
 a| 
いいえ
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
個のボリューム
 a| 
ボリュームのリスト。
 a| 
xref:reference_element_api_volume.adoc[ボリューム] 配列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== 新規導入バージョン

9.6
