---
permalink: api/reference_element_api_modifyvolumepair.html 
sidebar: sidebar 
keywords: volume,pair,pairs,modify,modifying,edit,editing,changing,change,modifyvolumepair,paired 
summary: ModifyVolumePair メソッドを使用すると、ボリュームのペア間のレプリケーションを一時停止またはリスタートできます。このメソッドは、ソースボリューム（読み取り / 書き込みアクセス権のあるボリューム）に対して設定されます。 
---
= ModifyVolumePair を使用します
:icons: font
:imagesdir: ../media/


[role="lead"]
「ボリュームペア」メソッドを使用すると、ボリュームペア間のレプリケーションを一時停止または再開できます。このメソッドは、ソースボリューム（読み取り / 書き込みアクセス権のあるボリューム）に対して設定されます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===


| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ボリューム ID
 a| 
変更するボリュームの識別番号。
 a| 
整数
 a| 
なし
 a| 
はい。



 a| 
pausedManual
 a| 
リモートレプリケーションは、ソース（読み取り / 書き込み）ボリュームで一時停止または再開できます。有効な値は次のとおり

* true ：ボリュームのレプリケーションを一時停止します。
* false ：ボリュームのレプリケーションを再開します。


値を指定しない場合、レプリケーションは変更されません。
 a| 
ブール値
 a| 
なし
 a| 
いいえ



 a| 
モード
 a| 
ボリュームのレプリケーションモード。有効な値は次のとおり

* Async ：ローカルクラスタへの書き込みが完了した時点で、ターゲットクラスタに書き込みがレプリケートされるのを待たずに、書き込み完了として通知されます。
* Sync ：ソースのデータがローカルクラスタとリモートクラスタの両方に格納された時点で、書き込み完了として通知されます。
* SnapshotsOnly ：ソースクラスタで作成された Snapshot だけがレプリケートされます。ソースボリュームのアクティブな書き込みはレプリケートされません。

 a| 
文字列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには戻り値はありません。



== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "ModifyVolumePair",
  "params": {
    "pausedManual": false,
    "volumeID": 5,
    "mode": "sync"
   },
  "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id" : 1,
   "result" : {}
}
----


== 新規導入バージョン

9.6
