---
permalink: api/reference_element_api_createvolume.html 
sidebar: sidebar 
keywords: create,volume,volumes,creating,CreateVolume 
summary: CreateVolume メソッドを使用すると、クラスタに新しい空のボリュームを作成できます。作成したボリュームはすぐに iSCSI 経由で接続できます。 
---
= CreateVolume を使用します
:icons: font
:imagesdir: ../media/


[role="lead"]
CreateVolume メソッドを使用すると、クラスタ上に新しい空のボリュームを作成できます。ボリュームが作成されるとすぐに、そのボリュームを iSCSI 経由で接続できます。

QoS 値を指定せずに作成したボリュームには、デフォルト値が使用されます。GetDefaultQoS メソッドを使用すると、ボリュームのデフォルト値を表示できます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


| 「 access 」をクリックします | ボリュームのアクセスモード。このパラメータを指定した場合、サポートされる値は「 SnapMirrorTarget 」のみです。 | 文字列 | なし | いいえ 


| 「 accountID` 」 | このボリュームを所有するアカウントの ID 。 | 整数 | なし | はい。 


| 「 associateWithQoSPolicy 」と入力します  a| 
指定した QoS ポリシーにボリュームを関連付けます。有効な値は次のとおり

* `true` ： QoSPolicy パラメータで指定された QoS ポリシーにボリュームを関連付けます。
* `false` ： QoSPolicy パラメータで指定された QoS ポリシーにボリュームを関連付けないでください。false の場合、 QoSPolicy パラメータで QoS ポリシーを指定したかどうかに関係なく、既存のポリシーの関連付けが削除されます。

| ブール値 | 正しいです | いいえ 


| 「 attributes 」 | JSON オブジェクト形式の名前と値のペアのリスト。属性の合計サイズは、 JSON 形式の文字を含めて、 1000 B 未満または 1KB 未満にする必要があります。 | JSON オブジェクト | なし | いいえ 


| enable512e  a| 
512 バイトのセクターエミュレーションを有効にします。有効な値は次のとおり

* 「真」：ボリュームは 512 バイトのセクターエミュレーションを提供します。
* false` ： 512e エミュレーションは有効になっていません。

| ブール値 | なし | はい。 


| 「 enableSnapMirrorReplication 」と入力します  a| 
ボリュームを SnapMirror エンドポイントでのレプリケーションに使用できるかどうかを指定します。有効な値は次のとおり

* 「真」
* 「偽」

| ブール値 | いいえ | いいえ 


| 「 50 サイズ」 | ボリュームでサポートされる FIFO （ First-In First-Out ）スナップショットの最大数を指定します。FIFO スナップショットと非 FIFO スナップショットはどちらも、ボリューム上で使用可能なスナップショットスロットの同じプールを使用することに注意してください。このオプションを使用して、使用可能なスナップショットスロットの FIFO スナップショットの消費を制限します。省略した場合、デフォルト値は 24 です。 | 整数 | 24 | いいえ 


| 「 inFifoSize 」のように表示されます | ボリュームによって予約された FIFO （ First-In First-Out ）スナップショットスロットの最小数を指定します。これにより、 FIFO 以外のスナップショットが意図せずに FIFO スロットを過剰に消費しないボリュームで FIFO スナップショットと非 FIFO スナップショットの両方を使用する場合に、保証されます。また、少なくともこの多くの FIFO スナップショットが常に利用可能であることを保証します。FIFO と非 FIFO のスナップショットは同じプールを共有するため、「 m inFifoSize 」は、可能な非 FIFO スナップショットの合計数を同じ量だけ減らします。省略した場合、デフォルト値は 0 です。 | 整数 | 0 | いいえ 


| 「 name 」 | ボリュームアクセスグループの名前（ユーザが指定可能）。固有である必要はありませんが、一意にすることを推奨します1~64 文字で指定します。 | 文字列 | なし | はい。 


| 「 qos 」と入力します  a| 
このボリュームの初期 QoS 設定。指定しない場合はデフォルト値が使用されます。有効な値は次のとおり

* 「 IOPS 」
* 「最大軸 IOPS 」
* 「 burstIOPS 」

| QoS オブジェクト | なし | いいえ 


| 「 qosPolicyID 」 | 指定したボリュームに適用する QoS 設定が定義されたポリシーの ID 。このパラメータは 'qos' パラメータと同時に指定することはできません | 整数 | なし | いいえ 


| 合計サイズ | ボリュームの合計サイズ（バイト）。サイズは最も近い MB 単位に切り上げられます。 | 整数 | なし | はい。 
|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
ボリューム
 a| 
作成されたボリュームの情報を含むオブジェクト。
 a| 
xref:reference_element_api_volume.adoc[ボリューム]



 a| 
ボリューム ID
 a| 
作成されたボリュームの ID 。
 a| 
整数



 a| 
カーブ（ Curve ）
 a| 
curve は一連のキーと値のペアです。キーはバイト単位の I/O サイズです。値は、特定の I/O サイズで IOP を実行する際のコストを表します。curve は、 100 IOPS での 4 、 096 バイトの処理セットと比較して計算されます。
 a| 
JSON オブジェクト

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "CreateVolume",
   "params": {
      "name": "mysqldata",
      "accountID": 1,
      "totalSize": 107374182400,
      "enable512e": false,
      "attributes": {
         "name1": "value1",
         "name2": "value2",
         "name3": "value3"
      },
      "qos": {
         "minIOPS": 50,
         "maxIOPS": 500,
         "burstIOPS": 1500,
         "burstTime": 60
      }
   },
   "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
    "id": 1,
    "result": {
        "curve": {
            "4096": 100,
            "8192": 160,
            "16384": 270,
            "32768": 500,
            "65536": 1000,
            "131072": 1950,
            "262144": 3900,
            "524288": 7600,
            "1048576": 15000
        },
        "volume": {
            "access": "readWrite",
            "accountID": 1,
            "attributes": {
                "name1": "value1",
                "name2": "value2",
                "name3": "value3"
            },
            "blockSize": 4096,
            "createTime": "2016-03-31T22:20:22Z",
            "deleteTime": "",
            "enable512e": false,
            "iqn": "iqn.2010-01.com.solidfire:mysqldata.677",
            "name": "mysqldata",
            "purgeTime": "",
            "qos": {
                "burstIOPS": 1500,
                "burstTime": 60,
                "curve": {
                    "4096": 100,
                    "8192": 160,
                    "16384": 270,
                    "32768": 500,
                    "65536": 1000,
                    "131072": 1950,
                    "262144": 3900,
                    "524288": 7600,
                    "1048576": 15000
                },
                "maxIOPS": 500,
                "minIOPS": 50
            },
            "scsiEUIDeviceID": "6a796179000002a5f47acc0100000000",
            "scsiNAADeviceID": "6f47acc1000000006a796179000002a5",
            "sliceCount": 0,
            "status": "active",
            "totalSize": 107374182400,
            "virtualVolumeID": null,
            "volumeAccessGroups": [],
            "volumeID": 677,
            "volumePairs": []
        },
        "volumeID": 677
    }
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS の設定]
