---
permalink: api/reference_element_api_initiator.html 
sidebar: sidebar 
keywords: object,objects,initiator 
summary: initiator オブジェクトには、 iSCSI イニシエータまたは Fibre Channel イニシエータの情報が含まれます。IQN 識別子または WWPN 識別子が含まれる場合もあります。ListInitiators メソッドを使用すると、システムで認識されているすべてのイニシエータのリストを取得できます。イニシエータオブジェクトを使用して、ボリュームアクセスグループ経由での一連のボリュームへの SCSI イニシエータアクセスを設定します。イニシエータは一度に 1 つのボリュームアクセスグループのメンバーにしかできません。CreateInitiators メソッドおよび ModifyInitiators メソッドを使用して 1 つ以上の virtualNetworkID を指定することで、イニシエータアクセスを 1 つ以上の VLAN に制限できます。仮想ネットワークを指定しない場合、イニシエータはすべてのネットワークにアクセスできます。 
---
= イニシエータ
:icons: font
:imagesdir: ../media/


[role="lead"]
initiator オブジェクトには、 iSCSI イニシエータまたは Fibre Channel イニシエータの情報が含まれます。IQN 識別子または WWPN 識別子が含まれる場合もあります。ListInitiators メソッドを使用すると、システムで認識されているすべてのイニシエータのリストを取得できます。イニシエータオブジェクトを使用して、ボリュームアクセスグループ経由での一連のボリュームへの SCSI イニシエータアクセスを設定します。イニシエータは一度に 1 つのボリュームアクセスグループのメンバーにしかできません。イニシエータアクセスを 1 つ以上の VLAN に制限するには、「 CreateInitiators 」および「 ModyInitiators 」メソッドを使用して 1 つ以上の virtualNetworkID を指定します。仮想ネットワークを指定しない場合、イニシエータはすべてのネットワークにアクセスできます。



== オブジェクトメンバー

このオブジェクトのメンバーは次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
エイリアス
 a| 
イニシエータに割り当てられているフレンドリ名（存在する場合）。
 a| 
文字列



 a| 
属性（ Attributes ）
 a| 
このイニシエータに割り当てられた一連の JSON 属性。属性が割り当てられていない場合は空です。
 a| 
JSON オブジェクト



 a| 
chapUsername のコマンド
 a| 
このイニシエータの一意の CHAP ユーザ名。
 a| 
文字列



 a| 
イニシエータ ID
 a| 
イニシエータの数値識別子。
 a| 
整数



 a| 
イニシエータ名
 a| 
IQN または WWPN 形式のイニシエータ名。
 a| 
文字列



 a| 
イニシエータシークレット
 a| 
イニシエータの認証に使用する CHAP シークレット。
 a| 
文字列



 a| 
requireChap
 a| 
このイニシエータに対して CHAP を必須にする場合は true 。
 a| 
ブール値



 a| 
targetSecret
 a| 
ターゲットの認証に使用する CHAP シークレット（相互 CHAP 認証を使用する場合）。
 a| 
文字列



 a| 
virtualNetworkID
 a| 
このイニシエータに関連付けられている仮想ネットワーク識別子のリスト。1 つ以上のが定義されている場合、このイニシエータは指定された仮想ネットワークにのみログインできます。仮想ネットワークが定義されていない場合、イニシエータはすべてのネットワークにログインできます。
 a| 
整数



 a| 
volumeAccessGroups
 a| 
このイニシエータが属するボリュームアクセスグループ ID のリスト。
 a| 
整数の配列

|===


== 詳細については、こちらをご覧ください

xref:reference_element_api_listinitiators.adoc[ListInitiators の 1 つです]
