---
permalink: api/reference_element_api_startbulkvolumewrite.html 
sidebar: sidebar 
keywords: volume,bulk,start,starting,write,session,startbulkvolumewrite 
summary: StartBulkVolumeWrite メソッドを使用すると、指定したボリュームの一括ボリューム書き込みセッションを開始できます。 
---
= StartBulkVolumeWrite
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 artBulkVolumeWrite 」メソッドを使用すると、指定したボリュームの一括ボリューム書き込みセッションを開始できます。

1 つのボリュームで同時に実行できる一括ボリュームプロセスは 2 つだけです。セッションを初期化すると、外部バックアップ元から Element ストレージボリュームにデータが書き込まれます。外部データは、 Element ストレージノードで実行されている Web サーバからアクセスされます。外部データアクセスに関するサーバ操作の情報は、ストレージシステムで実行中のスクリプトによって渡されます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
の形式で入力し
 a| 
ボリュームデータの形式。次のいずれかです。

* uncompressed ：ボリュームのすべてのバイトが圧縮されずに返されます。
* ネイティブ : 非透過的なデータが返されますこれは ' サイズが小さく ' 後続のボリュームの一括書き込みでより効率的に保存および書き込みが行われます

 a| 
文字列
 a| 
なし
 a| 
はい。



 a| 
ボリューム ID
 a| 
書き込むボリュームの ID 。
 a| 
整数
 a| 
なし
 a| 
はい。



 a| 
スクリプト
 a| 
実行可能スクリプトの名前。スクリプト名を指定しない場合は、 Element ストレージノードにアクセスするためにキーと URL が必要です。スクリプトはプライマリノードに対して実行され、キーと URL がスクリプトに返されます。これにより、ローカル Web サーバにアクセスできるようになります。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
scriptParameters
 a| 
スクリプトに渡す JSON パラメータ。
 a| 
JSON オブジェクト
 a| 
なし
 a| 
いいえ



 a| 
属性（ Attributes ）
 a| 
一括ボリュームジョブの JSON 属性。
 a| 
JSON オブジェクト
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
asyncHandle
 a| 
完了を確認する非同期プロセスの ID 。
 a| 
整数



 a| 
キーを押します
 a| 
セッションを一意に識別する判読不明なキー。
 a| 
文字列



 a| 
URL
 a| 
ノードの Web サーバにアクセスするための URL 。
 a| 
文字列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "StartBulkVolumeWrite",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
   },
   "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== 新規導入バージョン

9.6
