---
permalink: api/reference_element_api_syncjob.html 
sidebar: sidebar 
keywords: object,objects,syncjob 
summary: syncJob オブジェクトには、クラスタで実行中のクローニング、リモートレプリケーション、またはスライスの同期化ジョブに関する情報が含まれます。 
---
= syncJob
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syncJob オブジェクトには、クラスタで実行中のクローニング、リモートレプリケーション、またはスライスの同期化ジョブに関する情報が含まれます。

「 ListSyncJobs 」 API メソッドを使用して同期情報を取得できます。



== オブジェクトメンバー

このオブジェクトのメンバーは次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
blocksPerSecond のように入力します
 a| 
1 秒間にソースクラスタからターゲットクラスタに転送されるデータブロックの数。type メンバーが remote に設定されている場合のみ表示されます。
 a| 
整数



 a| 
ブランチタイプ（ BranchType ）
 a| 
リモートレプリケーションの同期化ジョブにのみ返されます。有効な値は次のとおり

* スナップショット
* ボリューム

 a| 
文字列



 a| 
bytesPerSecond のように指定します
 a| 
クローンが 1 秒あたりに処理するバイト数。type メンバーが clone または slice に設定されている場合のみ表示されます。
 a| 
浮動小数点



 a| 
クローン ID
 a| 
実行中のクローン処理の ID 。type メンバーが clone に設定されている場合にのみ表示されます。
 a| 
整数



 a| 
currentBytes
 a| 
クローンがソースボリュームで処理したバイト数。type メンバーが clone または slice に設定されている場合のみ表示されます。
 a| 
整数



 a| 
dstServiceID
 a| 
ボリュームのプライマリレプリカをホストするサービス ID 。type メンバーが remote に設定されている場合のみ表示されます。
 a| 
整数



 a| 
dstVolumeID
 a| 
デスティネーションボリュームの ID 。type メンバーが clone または remote に設定されている場合のみ表示されます。
 a| 
整数



 a| 
elapsedTime
 a| 
同期ジョブが開始されてからの経過時間（秒）。
 a| 
同期操作のタイプに応じた浮動小数点数または整数



 a| 
groupCloneID
 a| 
実行中のグループクローン処理の ID 。
 a| 
整数



 a| 
ノード ID
 a| 
クローンを実行するノードを指定します。type メンバーが clone に設定されている場合にのみ表示されます。
 a| 
整数



 a| 
PercentComplete
 a| 
同期ジョブが完了した割合。
 a| 
同期操作のタイプに応じた浮動小数点数または整数



 a| 
残り時間
 a| 
処理が完了するまでの推定時間（秒）。
 a| 
浮動小数点



 a| 
スライス ID
 a| 
同期するスライスドライブの ID 。
 a| 
整数



 a| 
段階
 a| 
type メンバーが remote または clone に設定されている場合のみ表示されます。有効な値は次のとおり

* metadata ：レプリケーションはリモートクラスタに転送する必要のあるデータを特定中です。レプリケーションプロセスのこの段階では、ステータスは報告されません。
* data ：レプリケーションはリモートクラスタにデータを一括で転送中です。
* whole ：スライス同期化ジョブのスライスの下位互換性を示します。

 a| 
文字列



 a| 
Snapshot ID
 a| 
クローン作成元の Snapshot の ID 。type メンバーが clone に設定されている場合にのみ表示されます。
 a| 
整数



 a| 
srcServiceID
 a| 
ソースサービス ID 。
 a| 
整数



 a| 
srcVolumeID
 a| 
ソースボリュームの ID 。
 a| 
整数



 a| 
TotalBytes
 a| 
クローンの総バイト数。type メンバーが clone または slice に設定されている場合のみ表示されます。
 a| 
整数



 a| 
を入力します
 a| 
同期処理のタイプ。有効な値は次のとおり

* クローン
* スライス
* ブロック
* リモート

 a| 
文字列

|===


== 詳細については、こちらをご覧ください

xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
