---
permalink: api/reference_element_api_testconnectmvip.html 
sidebar: sidebar 
keywords: management,connection,test,testing,mvip,testconnectmvip 
summary: TestConnectMvip メソッドを使用すると、ストレージクラスタへの管理接続をテストできます。テストでは、 MVIP に対して ping を実行し、シンプルな API メソッドを実行して接続を検証します。 
---
= TestConnectMvip のように入力します
:icons: font
:imagesdir: ../media/


[role="lead"]
「 TestConnectMvip 」メソッドを使用すると、ストレージクラスタへの管理接続をテストできます。テストでは、 MVIP に対して ping を実行し、シンプルな API メソッドを実行して接続を検証します。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


| MVIP | この値を渡して別の MVIP の管理接続をテストすることができます。ターゲットクラスタへの接続をテストするときは、この値を指定する必要はありません。 | 文字列 | なし | いいえ 
|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


| 詳細  a| 
テスト処理に関する情報（ JSON オブジェクト）。

* 'connected` ：テストが MVIP に接続できるかどうかを示します（ブーリアン）。
* `m vip`: テスト対象の MVIP ( 文字列 )
* `pingBytes: 56 バイトと 1500 バイトの ping テストの詳細 ( オブジェクト )
+
** `56`: 56 バイトの ping テストの結果 (JSON オブジェクト ):
+
*** individualResponseTimes : 各アンサンブルノードからの応答時間のリスト ( 文字列配列 )
*** individualStatus` ：各アンサンブルノードからの ping ステータスのリスト（ブーリアンの配列）。
*** 'RespondseTime`: ping の平均応答時間 ( 文字列 )
*** 'uccessful ': ping テストが成功したかどうかを示します ( ブール型 )


** 1500`: 1500 バイトの ping テストの結果 (JSON オブジェクト ):
+
*** individualResponseTimes : 各アンサンブルノードからの応答時間のリスト ( 文字列配列 )
*** individualStatus` ：各アンサンブルノードからの ping ステータスのリスト（ブーリアンの配列）。
*** 'RespondseTime`: ping の平均応答時間 ( 文字列 )
*** 'uccessful ': ping テストが成功したかどうか ( ブール値 )


** ``uration`: テストの実行に必要な時間の長さ ( 文字列 )
** 「フル」 : テストの結果 ( 文字列 )



| JSON オブジェクト 
|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "TestConnectMvip",
   "params": {
       "mvip" : "172.27.62.50"
       },
    "id":1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "mvip": "172.27.62.50",
      "pingBytes": {
        "1500": {
          "individualResponseTimes": [
            "00:00:00.000250",
            "00:00:00.000206",
            "00:00:00.000200",
            "00:00:00.000199",
            "00:00:00.000199"
         ],
          "individualStatus": [
             true,
             true,
             true,
             true,
             true
         ],
         "responseTime": "00:00:00.000211",
         "successful": true
       },
       "56": {
          "individualResponseTimes": [
            "00:00:00.000217",
            "00:00:00.000122",
            "00:00:00.000117",
            "00:00:00.000119",
            "00:00:00.000121"
         ],
         "individualStatus": [
            true,
            true,
            true,
            true,
            true
         ],
         "responseTime": "00:00:00.000139",
         "successful": true
        }
      }
    },
    "duration": "00:00:00.271244",
    "result": "Passed"
  }
}
----


== 新規導入バージョン

9.6
