---
permalink: api/reference_element_api_app_a_cluster_fault_codes.html 
sidebar: sidebar 
keywords: cluster,fault,codes,code,message,alert,error 
summary: ストレージクラスタで管理者の注意が必要なエラーや状態が発生すると、クラスタ障害が生成されます。ListClusterFaults メソッドを使用すると、ストレージクラスタの解決済みおよび未解決の障害の最新のリストを取得できます。 
---
= クラスタ障害コード
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージクラスタで管理者の注意が必要なエラーや状態が発生すると、クラスタ障害が生成されます。「 ListClusterFaults 」メソッドを使用すると、ストレージクラスタの解決済みおよび未解決の障害の最新のリストを取得できます。

NetApp Element ストレージクラスタの障害の詳細と有効な解決策を次に示します。

* * authenticationServiceFault*
+
1 つ以上のクラスタノードの認証サービスが正常に機能していません。

+
ネットアップサポートにお問い合わせください。

* * 利用可能な VirtualNetworkIPAddressesLow *
+
IP アドレスブロック内の仮想ネットワークアドレスの数が少なくなっています。

+
この問題を解決するには、仮想ネットワークアドレスのブロックに IP アドレスを追加してください。

* * blockClusterFull *
+
単一ノードの損失をサポートするのに十分なブロックストレージの空き容量がありません。クラスタフルレベルの詳細については、「 GetClusterFullThreshold 」 API メソッドを参照してください。このクラスタ障害は、次のいずれかの状態を示します。

+
** stage3Low （警告）：ユーザ定義のしきい値が超えています。Cluster Full の設定を調整するか、ノードを追加します。
** stage4Critical （エラー）： 1 ノードの障害からリカバリするための十分なスペースがありません。ボリューム、 Snapshot 、およびクローンは作成できません。
** stage5CompletelyConsumed （ Critical ） 1 ：書き込みまたは新しい iSCSI 接続は許可されません。現在の iSCSI 接続は維持されます。クラスタに容量を追加するまで書き込みは失敗します。この問題を解決するには、ボリュームをパージまたは削除するか、ストレージクラスタに別のストレージノードを追加してください。


* * ブロックが劣化しました *
+
障害により、ブロックデータの完全なレプリケートが行われなくなりました。

+
|===
| 重大度 | 説明 


 a| 
警告
 a| 
アクセス可能なブロックデータの完全なコピーは 2 つだけです。



 a| 
エラー
 a| 
アクセス可能なブロックデータの完全なコピーは 1 つだけです。



 a| 
重要
 a| 
ブロックデータの完全なコピーにはアクセスできません。

|===
+
* 注意： * 警告ステータスは、トリプル Helix システムでのみ発生します。

+
この問題を解決するには、オフラインのノードまたはブロックサービスをリストアするか、ネットアップサポートにお問い合わせください。

* * blockServiceTooFull*
+
ブロックサービスが大量のスペースを使用しています。

+
この問題を解決するには、ボリュームをパージまたは削除するか、ストレージクラスタに別のストレージノードを追加してください。

* * clockSkewExceedsFaultThreshold *
+
クラスタマスターとトークンを提供しているノードの間の時間差が推奨されるしきい値を超えている。

+
ストレージクラスタは、ノード間の時間スキューを自動的に修正できません。この問題を解決するには、インストール時のデフォルトではなく、使用するネットワーク内の NTP サーバを使用してください。すでに内部の NTP サーバを使用している場合は、ネットアップサポートにお問い合わせください。

* * clusterCannotSync*
+
クラスタブロックデータがデグレード状態になっており、ブロックデータの完全な冗長性をリストアする自動修復プロセスを続行できません。ノードまたはブロックサービスが多すぎるか、クラスタブロックサービスがいっぱいです。

+
この問題を解決するには、ブロック容量を追加するか、ネットアップサポートにお問い合わせください。

* * clusterFull *
+
ストレージクラスタ内の空きストレージスペースが不足しています。

+
この問題を解決するには、ストレージを追加してください。

* * clusterIOPSAreOverProvised*
+
ストレージクラスタの IOPS がオーバープロビジョニングされています。QoS の最小 IOPS の合計が、クラスタの想定 IOPS を上回っています。すべてのボリュームで同時に最小 QoS を維持することができません。

+
この問題を解決するには、ボリュームの最小 QoS IOPS 設定を引き下げてください。

* *disableDriveSecurityFailed*
+
保存データの暗号化機能を無効にすると、ドライブのセキュリティを無効にできません。ドライブのセキュリティは引き続き有効になっています。

+
ドライブのセキュリティを無効にできなかった理由が障害の詳細に表示されています。理由に基づいた問題の調査が必要になる場合があります。セキュリティを正常に無効にできないディスクをリカバリする必要がある場合は、次の手順を実行します。

+
.. ドライブを「 available 」ステータスにして、論理的に削除します。
.. ドライブで完全消去を実行します。
.. ドライブを「 active 」ステータスにします。上記の手順で問題が解決しない場合は、ドライブを交換します。


* * 接続解除されたクラスタペア *
+
クラスタペアが切断されているか、正しく設定されていません。

+
クラスタのネットワーク接続を確認してください。

* * disconnectedRemoteNode * を実行します
+
リモートノードが切断されているか、正しく設定されていません。ノード間のネットワーク接続を確認してください。

* * 切断された SnapMirrorEndpoint *
+
リモート SnapMirror エンドポイントが切断されているか、正しく設定されていません。クラスタとリモート SnapMirrorEndpoint の間のネットワーク接続を確認してください。

* * 走行可能 *
+
ストレージクラスタ内に追加可能なドライブがあります。通常は、すべてのストレージクラスタにすべてのドライブが追加されており、利用可能な状態のドライブはありません。この問題が予期せずに発生する場合は、ネットアップサポートにお問い合わせください。

+
この問題を解決するには、使用可能なドライブをすべてストレージクラスタに追加してください。

* * driveFailed *
+
次のいずれかの状態のドライブで障害が発生すると、クラスタはこのエラーを返します。

+
** ドライブマネージャがドライブにアクセスできません。
** スライスサービスまたはブロックサービスで障害が発生した回数が多すぎます。おそらくドライブの読み取りまたは書き込みの失敗が原因で再起動できません。
** ドライブがありません。
** ノードのマスターサービスにアクセスできません（ノード内のすべてのドライブが見つからないか障害状態であるとみなされます）。
** ドライブがロックされており、そのドライブの認証キーを取得できません。
** ドライブがロックされているためロック解除処理が失敗します。この問題を解決するには：
** ノードのネットワーク接続を確認してください。
** ドライブを交換します。
** 認証キーが使用可能であることを確認します。


* * driveHealthFault *
+
ドライブが SMART ヘルスチェックに失敗したため、ドライブの機能が低下しました。この障害には、 Critical 重大度レベルがあります。

+
** シリアル付きドライブ： < シリアル番号 > 、スロット： < ノードスロット >< ドライブスロット > 、 SMART 全体のヘルスチェックに失敗しました。この問題を解決するには、ドライブを交換してください。


* * driveWearFault *
+
ドライブの残存寿命がしきい値を下回っていますが、まだ機能しています。この障害には、重大度レベルとして「重大」と「警告」の 2 つのレベルがあります。

+
** シリアル付きドライブ： <serial number> in slot ： <node slot><drive slot> には、重大な摩耗度レベルがあります。
** Serial Number > in slot ： < ノードスロット >< ドライブスロット > のドライブの摩耗リザーブが少ない。この問題を解決するには、ドライブをすぐに交換してください。


* * duplicateClusterMasterCandidates *
+
ストレージクラスタマスターの候補が複数あります。

+
ネットアップサポートにお問い合わせください。

* * enableDriveSecurityFailed*
+
保存データの暗号化機能を有効にすると、ドライブのセキュリティを有効にできません。

+
セキュリティを有効にするために正しいキーが使用されていることを確認します。セキュリティを正常に有効にできないディスクをリカバリする必要がある場合は、次の手順を実行します。

+
.. ドライブを「 available 」ステータスにして、論理的に削除します。
.. ドライブで完全消去を実行します。
.. ドライブを「 active 」ステータスにします。上記の手順で問題が解決しない場合は、ドライブを交換します。


* * ensembleDegraded *
+
いずれかのアンサンブルノードでネットワーク接続または電源が失われています。

+
この問題を解決するには、該当するノードのネットワーク接続または電源を復旧してください。

* * 例外 *
+
通常とは異なる障害が発生しました。これらの障害は、障害キューから自動的に消去されることはありません。

+
ネットアップサポートにお問い合わせください。

* * 失敗した SpaceTooFull *
+
ブロックサービスがデータ書き込み要求に応答していません。スライスサービスが失敗した書き込みを格納するためのスペースが不足します。

+
ネットアップサポートにお問い合わせください。

* * fanSensor *
+
ファンセンサーに障害が発生しているか、ファンセンサーがありません。

+
ノード内の障害が発生したハードウェアを交換します。それでも問題が解決しない場合は、ネットアップサポートにお問い合わせください。

* * fibreChannelAccessDegraded *
+
Fibre Channel ノードが自身のストレージ IP アドレスでストレージクラスタ内の他のノードに応答していません。

+
クラスタのネットワーク接続を確認してください。

* * fibreChannelAccessUnavailable*
+
すべての Fibre Channel ノードが応答していません。ノード ID が表示されます。

+
クラスタのネットワーク接続を確認してください。

* * fibreChannelActiveIxL *
+
iXL Nexus 数は、サポートされるファイバチャネルノードあたりのアクティブセッション数が最大 8000 に近づいています。

+
** ベストプラクティスの上限は 5500 です。
** 警告の上限は 7500 です。
** 上限（必須ではない）は 8192 です。この問題を解決するには、 iXL Nexus の数をベストプラクティスの上限である 5500 未満に減らしてください。


* * fibreChannelConfig *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** PCI スロットに予期しないファイバチャネルポートがあります。
** 想定外の Fibre Channel HBA モデルが使用されています。
** Fibre Channel HBA のファームウェアに問題があります。
** Fibre Channel ポートがオンラインではありません。
** Fibre Channel パススルーを設定している永続的な問題があります。ネットアップサポートにお問い合わせください。


* * fibreChannelIOPS*
+
合計 IOPS 数がクラスタ内の Fibre Channel ノードの IOPS 制限に近づいています。制限は次のとおりです。

+
** FC0025 ： 450 、 000 IOPS 制限（ Fibre Channel ノードあたり 4K ブロックサイズ）
** FCN001 ： 625K OPS 制限（ Fibre Channel ノードあたり 4K ブロックサイズ）。この問題を解決するには、使用可能なすべての Fibre Channel ノードに負荷を分散してください。


* * fibreChannelStaticIxL *
+
iXL Nexus の数は、サポートされるファイバチャネルノードあたりの静的セッションの上限である 16000 に近づいています。

+
** ベストプラクティスの上限は 11000 です。
** 警告制限は 15000 です。
** 最大制限（強制）は 16384 です。この問題を解決するには、 iXL Nexus の数をベストプラクティスの上限である 11000 未満に減らしてください。


* * fileSystemCapacityLow *
+
いずれかのファイルシステムでスペースが不足しています。

+
この問題を解決するには、ファイルシステムに容量を追加してください。

* * FipsDrivesMismatch *
+
FIPS 対応ストレージノードに FIPS 非対応ドライブが挿入されているか、 FIPS 非対応ストレージノードに FIPS 対応ドライブが挿入されています。

+
該当するドライブを取り外すか交換してください。

* * FipsDrivesOutOfCompliance]
+
保存データの暗号化が無効になっているか、ストレージクラスタに FIPS 非対応のハードウェアが含まれていることが検出されました。

+
保存データの暗号化を有効にするか、 FIPS 非対応のハードウェアをストレージクラスタから取り外してください。

* * fipsSelfTestFailure*
+
FIPS のセルフテスト中に障害が検出されました。

+
ネットアップサポートにお問い合わせください。

* * ハードウェア構成の不一致 *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** 構成がノード定義と一致しません。
** このタイプのノードに対して正しくないドライブサイズが使用されています。
** ノードでサポート対象外のドライブが使用されています。
** ドライブファームウェアが一致しません。
** ドライブの暗号化対応が親ノードと一致しません。ネットアップサポートにお問い合わせください。


* *idPCertificateExpiration*
+
サードパーティのアイデンティティプロバイダで使用するクラスタのサービスプロバイダの SSL 証明書の有効期限が近づいているか、または有効期限が切れています。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===
| 重大度 | 説明 


 a| 
警告
 a| 
証明書は 30 日以内に期限切れになります。



 a| 
エラー
 a| 
証明書は 7 日以内に期限切れになります。



 a| 
重要
 a| 
証明書は 3 日以内に期限切れになるか、すでに期限切れになっています。

|===
+
この問題を解決するには、有効期限が切れる前に SSL 証明書を更新してください。更新された SSL 証明書を提供するには、 UpdateIdpConfiguration メソッドを「 refreshCertificateExpirationTime=true 」とともに使用します。

* * inconsistentBondModes *
+
VLAN デバイスのボンディングモードが見つかりません。想定されるボンディングモードと使用中のボンディングモードが表示されます。

+
この問題を解決するには、ノード Web UI でボンディングモードを変更してください。

* * inconsistentInterfaceConfiguration*
+
インターフェイスの設定が一貫していません。

+
この問題を解決するには、ストレージクラスタ内のノードインターフェイスの設定を同じにしてください。

* * inconsistentMtus *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** Bond1G mismatch ： Bond1G インターフェイス間で異なる MTU が設定されています。
** Bond10G mismatch ： Bond10G インターフェイス間で異なる MTU が設定されています。該当するノードと関連付けられている MTU 値が表示されます。


+
この問題を解決するには、ノード Web UI で MTU 設定を変更してください。

* * inconsistentRoutingRules*
+
このインターフェイスのルーティングルールが矛盾しています。

* * inconsistentSubnetMas*
+
VLAN デバイスのネットワークマスクが、内部的に記録された VLAN のネットワークマスクと一致しません。想定されるネットワークマスクと使用中のネットワークマスクが表示されます。

+
この問題を解決するには、 Element （ストレージクラスタ） Web UI でサブネットマスクを変更してください。

* * incorrectBondPortCount *
+
ボンドポートの数が正しくありません。

* * invalidConfiguredFibreChannelNodeCount *
+
想定される 2 つの Fibre Channel ノード接続のいずれかがデグレード状態です。この障害は、 Fibre Channel ノードが 1 つしか接続されていない場合に発生します。

+
この問題を解決するには、クラスタのネットワークの接続状態とケーブル配線を確認し、障害が発生したサービスがないかを確認してください。ネットワークやサービスに問題がない場合は、ネットアップサポートに連絡して Fibre Channel ノードを交換してください。

* *irqBalanceFailed*
+
割り込みのバランス調整中に例外が発生しました。

+
ネットアップサポートにお問い合わせください。

* * kmipCertificateFault （ルート認証局（ CA ）証明書の有効期限が近づいています） *
+
ルート認証局（ CA ）証明書の有効期限が近づいています。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===
| 重大度 | 説明 


 a| 
警告
 a| 
証明書は 30 日以内に期限切れになります。



 a| 
エラー
 a| 
証明書は 7 日以内に期限切れになります。



 a| 
重要
 a| 
証明書は 3 日以内に期限切れになります。

|===
+
この問題を解決するには、有効期限が切れる前に証明書を更新してください。ルート CA から、有効期限が 30 日以上ある新しい証明書を取得します。ModifyKeyServerKmip API メソッドを使用して、更新されたルート CA 証明書を提供します。

* * kmipCertificateFault （クライアント証明書の有効期限が近づいています） *
+
クライアント証明書の有効期限が近づいています。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===
| 重大度 | 説明 


 a| 
警告
 a| 
証明書は 30 日以内に期限切れになります。



 a| 
エラー
 a| 
証明書は 7 日以内に期限切れになります。



 a| 
重要
 a| 
証明書は 3 日以内に期限切れになります。

|===
+
この問題を解決するには、 GetClientCertificateSigningRequest メソッドを使用して新しい CSR を作成してください。30 日以上の有効期限を持つ CSR に署名を受けてから、 ModifyKeyServerKmip API メソッドを使用して、期限切れになる KMIP クライアント証明書を新しい証明書に置き換えます。

* * kmipCertificateFault （ルート認証局（ CA ）証明書の有効期限が切れています） *
+
ルート CA 証明書の有効期限が切れています。

+
ルート CA から、有効期限が 30 日以上ある新しい証明書を取得します。ModifyKeyServerKmip API メソッドを使用して、更新されたルート CA 証明書を提供します。

* * kmipCertificateFault （クライアント証明書の有効期限が切れています） *
+
クライアント証明書の有効期限が切れています。

+
GetClientCertificateSigningRequest API メソッドを使用して新しい CSR を作成し、新しい有効期限が 30 日以上あることを確認する署名を受けます。ModifyKeyServerKmip API メソッドを使用して、期限切れのクライアント証明書を新しい証明書に置き換えます。

* * kmipCertificateFault （ルート証明機関（ CA ）証明書が無効です） *
+
ルート CA 証明書が無効です。

+
正しい証明書が指定されていることを確認してください。必要に応じて、ルート CA から証明書を再取得します。ModifyKeyServerKmip API メソッドを使用して、正しい証明書をインストールします。

* * kmipCertificateFault （クライアント証明書が無効です） *
+
クライアント証明書が無効です。

+
正しい KMIP クライアント証明書がインストールされていることを確認してください。クライアント証明書のルート CA が外部キー管理サーバにインストールされている必要があります。クライアント証明書を更新する必要がある場合は、 ModifyKeyServerKmip API メソッドを使用します。

* * kmipServerFault （接続障害） *
+
1 つ以上のノードが外部キー管理サーバにアクセスできません。

+
キーサーバ ID は、障害の詳細に記載されています。サーバが機能しており、管理ネットワーク経由でアクセスできることを確認してください。一部のノードのみが外部キー管理サーバにアクセスできない場合は、障害の詳細にキーサーバにアクセスできないノードが表示されます。ネットワークまたは特定のノードレベルでトラブルシューティングを実行し、一部のノードのみが外部キー管理サーバにアクセスできる理由を特定します。

* * kmipServerFault （認証エラー） *
+
1 つ以上のノードを外部キー管理サーバで認証できません。

+
正しいルート CA および KMIP クライアント証明書が使用されていることを確認します。いずれかの証明書を更新する必要がある場合は、 ModifyKeyServerKmip メソッドを使用して正しい証明書をインストールします。

* * kmipServerFault （サーバエラー） *
+
外部キー管理サーバでエラーが発生しました。

+
エラーの詳細は、障害の詳細に記載されています。エラーに基づいて、外部キー管理サーバのトラブルシューティングが必要になる場合があります。

* * memyEccThreshold *
+
修正可能な ECC エラーまたは修正不可能な ECC エラーが多数検出されました。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===
| イベント | 重大度 | 説明 


 a| 
1 つの DIMM cErrorCount が cDimmCorrectableErrWarnThreshold に到達しました。
 a| 
警告
 a| 
DIMM のしきい値を超えている修正可能な ECC メモリエラー： <Processor><DIMM Slot>



 a| 
DIMM の cErrorFaultTimer が期限切れになるまで、 1 つの DIMM cErrorCount は cDimmCorrectableErrWarnThreshold よりも高くなります。
 a| 
エラー
 a| 
DIMM のしきい値を超えている修正可能な ECC メモリエラー： <Processor><DIMM>



 a| 
メモリコントローラが cMemCtlrCorrectableErrWarnThreshold より上の cErrorCount を報告し、 cMemCtlrCorrectableErrWarnDuration を指定します。
 a| 
警告
 a| 
修正可能な ECC メモリエラーがメモリコントローラのしきい値を超えています： <Processor><Memory Controller>



 a| 
メモリコントローラでは、メモリコントローラの cErrorFaultTimer の期限が切れるまで、メモリコントローラから cMemCtlrCorrectableErrWarnThreshold が報告されます。
 a| 
エラー
 a| 
DIMM のしきい値を超えている修正可能な ECC メモリエラー： <Processor><DIMM>



 a| 
1 つの DIMM がゼロより大きい uErrorCount を報告していますが、 cDimmUncorrectableErrFaultThreshold よりも小さくなっています。
 a| 
警告
 a| 
DIMM で修正不可能な ECC メモリエラーが検出されました： <Processor><DIMM Slot>



 a| 
1 つの DIMM で少なくとも cDimmUncorrectableErrFaultThreshold の uErrorCount が報告されます。
 a| 
エラー
 a| 
DIMM で修正不可能な ECC メモリエラーが検出されました： <Processor><DIMM Slot>



 a| 
メモリコントローラがゼロより大きい uErrorCount を報告していますが、 cMemCtlrUncorrectableErrFaultThreshold よりも小さくなっています。
 a| 
警告
 a| 
メモリコントローラで修正不可能な ECC メモリエラーが検出されました： <Processor><Memory Controller>



 a| 
メモリコントローラが少なくとも cMemCtlrUncorrectableErrFaultThreshold の uErrorCount を報告しています。
 a| 
エラー
 a| 
メモリコントローラで修正不可能な ECC メモリエラーが検出されました： <Processor><Memory Controller>

|===
+
この問題を解決するには、ネットアップサポートにお問い合わせください。

* * memoryUsageThreshold *
+
メモリ使用量が正常値を上回っています。この問題では、緊急性に基づいて次の重大度が使用されます。

+

NOTE: エラーの種類の詳細については、エラーの詳細 * の見出しを参照してください。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
システムメモリが不足しています。



 a| 
エラー
 a| 
システムメモリが非常に少なくなっています。



 a| 
重要
 a| 
システムメモリが完全に消費されています。

|===
+
この問題を解決するには、ネットアップサポートにお問い合わせください。

* * メタデータの ClusterFull *
+
単一ノードの損失をサポートするのに十分なメタデータストレージの空き容量がありません。クラスタフルのレベルの詳細については、 GetClusterFullThreshold API メソッドを参照してください。このクラスタ障害は、次のいずれかの状態を示します。

+
** stage3Low （警告）：ユーザ定義のしきい値が超えています。Cluster Full の設定を調整するか、ノードを追加します。
** stage4Critical （エラー）： 1 ノードの障害からリカバリするための十分なスペースがありません。ボリューム、 Snapshot 、およびクローンは作成できません。
** stage5CompletelyConsumed （ Critical ） 1 ：書き込みまたは新しい iSCSI 接続は許可されません。現在の iSCSI 接続は維持されます。クラスタに容量を追加するまで書き込みは失敗します。データをパージまたは削除するか、ノードを追加します。詳細については、「クラスタフルレベルについて」を参照してください。


+
この問題を解決するには、ボリュームをパージまたは削除するか、ストレージクラスタに別のストレージノードを追加してください。

* * mtuCheckFailure*
+
ネットワークデバイスに適切な MTU サイズが設定されていません。

+
この問題を解決するには、すべてのネットワークインターフェイスとスイッチポートでジャンボフレームが設定されている（ MTU が最大 9 、 000 バイト）ことを確認してください。

* * networkConfig *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** 想定されるネットワークインターフェイスが存在しません。
** ネットワークインターフェイスが重複しています。
** ネットワークインターフェイスは設定されていますが停止しています。
** ネットワークインターフェイスの再起動が必要です。ネットアップサポートにお問い合わせください。


* * 利用不可 VirtualNetworkIPAddresses*
+
IP アドレスのブロックに使用可能な仮想ネットワークアドレスがありません。

+
** virtualNetworkID # タグ（ ### ）には、使用可能なストレージ IP アドレスがありません。クラスタにノードを追加することはできません。この問題を解決するには、仮想ネットワークアドレスのブロックに IP アドレスを追加してください。


* * nodeHardwareFault （ネットワークインターフェイス <name> が停止しているか、ケーブルが接続されていません） *
+
ネットワークインターフェイスが停止しているか、ケーブルが取り外されています。

+
この問題を解決するには、ノードのネットワーク接続を確認してください。

* * nodeHardwareFault （ドライブ暗号化対応状態がスロット <node slot><drive slot> のドライブのノードの暗号化対応状態と一致しません） *
+
ドライブが、搭載されているストレージノードと暗号化機能が一致しません。

* * nodeHardwareFault （このノードタイプのスロット >< ドライブスロット > にあるドライブの < ドライブタイプ > ドライブサイズ < 実際のサイズ > が正しくありません。 < ドライブスロット > このノードタイプが想定される < 想定サイズ > ） *
+
ストレージノードに、このノードに対してサイズが正しくないドライブが含まれています。

* * nodeHardwareFault （サポートされていないドライブがスロット <node slot><drive slot> で検出されました。ドライブの統計情報と健全性情報が使用できません） *
+
ストレージノードに含まれているドライブはサポートされません。

* * nodeHardwareFault （スロット < ノードスロット >< ドライブスロット > のドライブでファームウェアバージョン < 想定バージョン > を使用している必要がありますが、サポートされていないバージョン < 実際のバージョン > を使用しています） *
+
ストレージノードに、サポート対象外のファームウェアバージョンを実行しているドライブが含まれています。

* * nodeMaintenanceMode*
+
ノードがメンテナンスモードになりました。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===
| 重大度 | 説明 


 a| 
警告
 a| 
ノードがまだメンテナンスモードになっていることを示します。



 a| 
エラー
 a| 
メンテナンスモードを無効にできなかったことを示します。通常は、スタンバイが失敗したかアクティブなスタンバイが原因です。

|===
+
この問題を解決するには、メンテナンスが完了したらメンテナンスモードを無効にしてください。エラーレベルの問題が解決しない場合は、ネットアップサポートにお問い合わせください。

* * nodeOffline *
+
Element ソフトウェアが指定されたノードと通信できません。

+
この問題を解決するには、クラスタのネットワークの接続状態とケーブル配線を確認してください。ネットワークに問題がない場合は、ネットアップサポートに連絡してノードを交換してください。

* * notUsingLACpBondMode *
+
LACP ボンディングモードが設定されていません。

+
この問題を解決するには、ストレージノードの導入時に LACP ボンディングを使用してください。 LACP を有効にして適切に設定していないと、クライアントでパフォーマンスの問題が発生する可能性があります。

* * ntpServerUnreachable*
+
ストレージクラスタが指定された NTP サーバと通信できません。

+
この問題を解決するには、 NTP サーバの設定、ネットワーク、およびファイアウォールを確認してください。

* * ntpTimeNotInSync *
+
ストレージクラスタと指定された NTP サーバで時刻に大きな差があります。ストレージクラスタはこの時間差を自動的に修正できません。

+
この問題を解決するには、インストール時のデフォルトではなく、使用するネットワーク内の NTP サーバを使用してください。内部の NTP サーバを使用しても問題が維持される場合は、ネットアップサポートにお問い合わせください。

* * nvramDeviceStatus *
+
NVRAM デバイスでエラーが発生しているか、障害が発生しているか、障害が発生しています。この問題には次の重大度があります。

+
|===
| 重大度 | 説明 


 a| 
警告
 a| 
ハードウェアによって警告が検出されました。この状態は、温度警告などの一時的なものです。

** nvmetimeError
** nvmetimeStatus
** energySourceLifetimeStatus
** energySourceTemperatureStatus
** warningThresholdExceeded




 a| 
エラー
 a| 
ハードウェアによってエラーまたは重大ステータスが検出されました。クラスタマスターがスライスドライブの処理を中止しようとします（ドライブ削除イベントが生成されます）。セカンダリスライスサービスを使用できない場合、ドライブは削除されません。警告レベルのエラーに加えて返されるエラー：

** NVRAM デバイスマウントポイントが存在しません。
** NVRAM デバイスパーティションが存在しません。
** NVRAM デバイスパーティションは存在しますが、マウントされていません。




 a| 
重要
 a| 
ハードウェアによってエラーまたは重大ステータスが検出されました。クラスタマスターがスライスドライブの処理を中止しようとします（ドライブ削除イベントが生成されます）。セカンダリスライスサービスを使用できない場合、ドライブは削除されません。

** 永続性ホスト
** armStatusSaveNArmed
** csaveStatusError


|===
+
ノード内の障害が発生したハードウェアを交換します。それでも問題が解決しない場合は、ネットアップサポートにお問い合わせください。

* * powerSupplyError *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** 電源装置がありません。
** 電源装置で障害が発生しました。
** 電源装置の入力が見つからないか、範囲外です。この問題を解決するには、冗長電源がすべてのノードに供給されていることを確認してください。問題が解決しない場合は、ネットアップサポートにお問い合わせください。


* * provisionedSpaceTooFull*
+
ストレージクラスタのプロビジョニング済み容量がいっぱいです。

+
この問題を解決するには、プロビジョニング済みスペースを追加するか、またはボリュームまたは Snapshot を削除およびパージしてください。

* * remoteRepAsyncDelayExceeded *
+
レプリケーションに設定されている非同期遅延を超えました。

* * remoteRepClusterFull *
+
ターゲットストレージクラスタがいっぱいのため、ボリュームがリモートレプリケーションを停止しました。

+
この問題を解決するには、ターゲットストレージクラスタのスペースを解放してください。

* * remoteRepSnapshotClusterFull *
+
ターゲットストレージクラスタがいっぱいのため、ボリュームが Snapshot のリモートレプリケーションを停止しました。

+
この問題を解決するには、ターゲットストレージクラスタのスペースを解放してください。

* * remoteRepSnapshotsExceededLimit *
+
ターゲットストレージクラスタのボリュームが Snapshot の上限を超えたため、ボリュームが Snapshot のリモートレプリケーションを停止しました。

+
この問題を解決するには、リモートクラスタ上の Snapshot をいくつか削除してください。

* * scheduleActionError *
+
スケジュールされたアクティビティの 1 つ以上を実行しましたが、失敗しました。

+
スケジュールされたアクティビティが再び実行されて成功するか、スケジュールされたアクティビティが削除されるか、またはアクティビティが一時停止されて再開されると、障害はクリアされます。

* * sensorReadingFailed*
+
ベースボード管理コントローラ（ BMC ）のセルフテストに失敗したか、センサーが BMC と通信できませんでした。

+
ネットアップサポートにお問い合わせください。

* * serviceNotRunning *
+
必要なサービスが実行されていません。

+
ネットアップサポートにお問い合わせください。

* * siceServiceTooFull*
+
スライスサービスに割り当てられたプロビジョニング済み容量が少なすぎます。

+
この問題を解決するには、ストレージノードを追加するか、ネットアップサポートにお問い合わせください。

* * sliceServiceUnhealthy * が表示されます
+
スライスサービスが正常な状態でないことが検出され、サービスが自動的に停止されました。

+
** 重大度 = 警告：対処は行われません。この警告期間は 6 分後に終了します。
** 重大度 = エラー：データの運用停止処理が自動的に実行され、他の正常なドライブにデータが再レプリケートされます。ネットワーク接続の問題とハードウェアエラーを確認します。特定のハードウェアコンポーネントで障害が発生した場合は、それ以外の障害が発生します。スライスサービスにアクセスできるかサービスが運用停止されると、障害は解消されます。


* * sshEnabled *
+
ストレージクラスタ内の 1 つ以上のノードで SSH サービスが有効になっています。

+
この問題を解決するには、ノードの SSH サービスを無効にしてください。

* * sslCertificateExpiration*
+
このノードに関連付けられている SSL 証明書の有効期限が近づいているか、期限が切れています。この問題では、緊急性に基づいて次の重大度が使用されます。

+
|===


| 重大度 | 説明 


 a| 
警告
 a| 
証明書は 30 日以内に期限切れになります。



 a| 
エラー
 a| 
証明書は 7 日以内に期限切れになります。



 a| 
重要
 a| 
証明書は 3 日以内に期限切れになるか、すでに期限切れになっています。

|===
+
この問題を解決するには、 SSL 証明書を更新してください。必要に応じて、ネットアップサポートにお問い合わせください。

* * strandedCapacity *
+
1 つのノードがストレージクラスタの容量の半分を超えています。

+
データの冗長性を維持するために、最大のノードの容量がシステムによって削減され、ブロック容量の一部が孤立（使用されない）状態になります。この問題を解決するには、既存のストレージノードにドライブを追加するか、クラスタにストレージノードを追加してください。

* * tempSensor *
+
温度センサーが正常よりも高い温度を報告しています。この問題は、 powerSupplyError または fanSensor とともに発生する可能性があります。

+
ストレージクラスタの近くに通気を妨げる障害物がないかどうかを確認してください。必要に応じて、ネットアップサポートにお問い合わせください。

* * アップグレード *
+
アップグレードが 24 時間以上実行中です。

+
この問題を解決するには、アップグレードを再開するか、ネットアップサポートにお問い合わせください。

* * unbalancedMixedNodes *
+
1 つのノードがストレージクラスタの容量の 1/3 以上を使用しています。

+
ネットアップサポートにお問い合わせください。

* * 無対応サービス *
+
システムサービスが応答しなくなりました。

+
ネットアップサポートにお問い合わせください。

* * virtualNetworkConfig *
+
このクラスタ障害は、次のいずれかの状態を示します。

+
** インターフェイスが存在しません。
** インターフェイス上のネームスペースが正しくありません。
** ネットワークマスクが正しくありません。
** IP アドレスが正しくありません。
** インターフェイスが稼働していません。
** ノード上に不要なインターフェイスがあります。ネットアップサポートにお問い合わせください。


* * volumesDegraded *
+
セカンダリボリュームのレプリケートと同期が完了していません。

+
この問題は、同期が完了すると解消されます。

+
問題が解消されない場合は、ネットワーク接続の問題やハードウェアエラーが発生していないか確認してください。

* * volumesOffline *
+
ストレージクラスタ内の 1 つ以上のボリュームがオフラインです。

+
ネットアップサポートにお問い合わせください。





== 詳細については、こちらをご覧ください

* xref:reference_element_api_getclusterfullthreshold.adoc[「 getClusterFullThreshold 」]
* xref:reference_element_api_listclusterfaults.adoc[ListClusterFaults]

