---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: ListDriveStats メソッドを使用すると、クラスタ内の複数のドライブに関するアクティビティ測定値の概要をリストできます。デフォルトでは、このメソッドはクラスタ内のすべてのドライブについて統計を返します。これらの測定値は、クラスタにドライブを追加したときからの累積値です。このメソッドが返す値には、ブロックドライブに固有な値とメタデータドライブに固有な値があります。 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ListDriveStats メソッドを使用すると、クラスタ内の複数のドライブに関するアクティビティ測定値の概要をリストできます。デフォルトでは、このメソッドはクラスタ内のすべてのドライブについて統計を返します。これらの測定値は、クラスタにドライブを追加したときからの累積値です。このメソッドが返す値には、ブロックドライブに固有な値とメタデータドライブに固有な値があります。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ドライブ
 a| 
ドライブの統計を返すドライブ ID （ driveID ）のリスト。このパラメータを省略すると、すべてのドライブの測定値が返されます。
 a| 
整数の配列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
driveStats
 a| 
各ドライブのドライブアクティビティ情報のリスト。
 a| 
xref:reference_element_api_drivestats.adoc[driveStats] 配列



 a| 
エラー
 a| 
driveID と関連するエラーメッセージのリスト。常に表示され、エラーがない場合は空です。
 a| 
JSON オブジェクトの配列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
