---
permalink: api/reference_element_api_volumestats.html 
sidebar: sidebar 
keywords: object,objects,volumeStats 
summary: volumeStats オブジェクトには、各ボリュームの統計データが含まれます。 
---
= ボリューム統計
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
volumeStats オブジェクトには、各ボリュームの統計データが含まれます。



== オブジェクトメンバー

次のメソッドを使用すると、一部またはすべてのボリュームに関する volumeStats オブジェクトを取得できます。

* xref:reference_element_api_getvolumestats.adoc[GetVolumeStats]
* xref:reference_element_api_listvolumestatsbyaccount.adoc[ListVolumeStatsByAccount]
* xref:reference_element_api_listvolumestatsbyvolume.adoc[ListVolumeStatsByVolume を参照してください]
* xref:reference_element_api_listvolumestatsbyvolumeaccessgroup.adoc[ListVolumeStatsByVolumeAccessGroup]


このオブジェクトのメンバーは次のとおりです。

[cols="20,50,15,15"]
|===
| 名前 | 説明 | 計算 | を入力します 


 a| 
アカウント ID
 a| 
ボリューム所有者のアカウントの ID 。
 a| 
該当なし
 a| 
整数



 a| 
実際の IOPS
 a| 
過去 500 ミリ秒の、ボリュームに対する実際の IOPS 。
 a| 
ポイントインタイム
 a| 
整数



 a| 
asyncDelay のような名前です
 a| 
ボリュームが最後にリモートクラスタと同期されてからの時間。ボリュームがペアリングされていない場合、値は null です。* 注：レプリケーションがアクティブな状態のターゲットボリュームの asyncDelay は常に 0 （ゼロ）です。レプリケーション中、ターゲットボリュームはシステムを認識し、 asyncDelay が常に正確であるものとします。
 a| 
該当なし
 a| 
ISO 8601 形式の期間を示す文字列または null



 a| 
平均 IOPSize
 a| 
直近 500 ミリ秒の、ボリュームに対する最新の I/O の平均サイズ（バイト）。
 a| 
ポイントインタイム
 a| 
整数



 a| 
バースタオシュはそれを
 a| 
ユーザが使用可能な IOP クレジットの合計数。ボリュームが設定された最大 IOPS に到達していない場合、クレジットは蓄積されます。
 a| 
該当なし
 a| 
整数



 a| 
クライアントキュー深度
 a| 
ボリュームに対する未処理の読み取り処理と書き込み処理の数。
 a| 
該当なし
 a| 
整数



 a| 
desiredMetadataHosts
 a| 
ボリュームメタデータをメタデータ（スライス）サービス間で移行する場合に移行するメタデータサービス。値「 null 」はボリュームが移行されていないことを意味します。
 a| 
該当なし
 a| 
JSON オブジェクト



 a| 
遅延時間
 a| 
過去 500 ミリ秒の、ボリュームに対する処理が完了した平均時間（マイクロ秒）。値「 0 」（ゼロ）は、ボリュームに対する I/O がないことを示します。
 a| 
ポイントインタイム
 a| 
整数



 a| 
メタデータホスト
 a| 
ボリュームメタデータが配置されているメタデータ（スライス）サービス。有効な値は次のとおり

* primary ：ボリュームをホストしているプライマリメタデータサービス。
* liveSecondaries ：現在の状態が「 live 」であるセカンダリメタデータサービス。
* deadSecondaries ：状態が「 dead 」であるセカンダリメタデータサービス。

 a| 
該当なし
 a| 
JSON オブジェクト



 a| 
正常化された IOPS
 a| 
過去 500 ミリ秒の、クラスタ全体の平均 IOPS 。
 a| 
ポイントインタイム
 a| 
整数



 a| 
ゼロ以外のロック
 a| 
前回のガベージコレクション完了後、データが含まれる 4KiB ブロックの総数。
 a| 
該当なし
 a| 
整数



 a| 
readBytes
 a| 
ボリューム作成以降の、ボリュームから読み取られた累積バイト総数。
 a| 
単調増加
 a| 
整数



 a| 
readBytesLastSample
 a| 
最新のサンプル期間中にボリュームから読み取られたバイト総数。
 a| 
ポイントインタイム
 a| 
整数



 a| 
readLatencyUSec
 a| 
過去 500 ミリ秒の、ボリュームへの読み取り処理を完了するまでの平均時間（マイクロ秒）。
 a| 
ポイントインタイム
 a| 
整数



 a| 
readLatencyUSecTotal
 a| 
ボリュームからの読み取り処理の実行に費やされた合計時間。
 a| 
単調増加
 a| 
整数



 a| 
readOps
 a| 
ボリューム作成以降の、ボリュームに対する読み取り処理の合計数。
 a| 
単調増加
 a| 
整数



 a| 
readOpsLastSample
 a| 
最新のサンプル期間中の読み取り処理の総数。
 a| 
ポイントインタイム
 a| 
整数



 a| 
samplePeriodMSec
 a| 
サンプル期間の長さ（ミリ秒単位）。
 a| 
該当なし
 a| 
整数



 a| 
sliceIopsStats
 a| 
ボリュームのI/O使用率の統計。Element 12.8以降で使用できます。sliceIopsStatsに指定できる値は次のとおりです。

* largeStatistics：より長い期間（通常は過去24時間）に測定されたボリュームのI/O統計。
* smallStatistics：より短い期間（通常は過去1時間）に測定されたボリュームのI/O統計。


largeStatisticsおよびsmallStatisticsに指定できる値は次のとおりです。

* averageReadIops：ボリュームの平均読み取りIOPS。
* averageTotalIops：ボリュームの平均合計（読み取り+書き込み）IOPS。
* averageWriteIops：ボリュームの平均書き込みIOPS。
* nSamples：統計計算に含まれるサンプルの数。
* peakReadIops：統計間隔で観察された最大読み取りIOPS。
* peakTotalIops：統計間隔で観察された最大合計IOPS。
* peakWriteIops：統計間隔で観察された最大書き込みIOPS。
* sliceID：ボリュームIDまたはスライスID

 a| 
ポイントインタイム
 a| 
JSON オブジェクト



 a| 
スロットル
 a| 
0~1 の浮動小数点数。データの再レプリケーション、一時的なエラー、 Snapshot の作成のために、クライアントの処理量を maxIOPS 未満に抑えている割合。
 a| 
該当なし
 a| 
浮動小数点



 a| 
タイムスタンプ
 a| 
現在の時刻（ UTC+0 形式）。
 a| 
該当なし
 a| 
ISO 8601 形式の日付文字列



 a| 
アン・アライナード・償還
 a| 
ボリューム作成以降の、ボリュームにアラインメントされていない読み取り処理の累積総数。
 a| 
単調増加
 a| 
整数



 a| 
アンアライナードライト
 a| 
ボリューム作成以降の、ボリュームに対するアラインメントされていない書き込み処理の累積総数。
 a| 
単調増加
 a| 
整数



 a| 
volumeAccessGroups
 a| 
ボリュームが属するボリュームアクセスグループの ID のリスト。
 a| 
該当なし
 a| 
整数の配列



 a| 
ボリューム ID
 a| 
ボリュームの ID 。
 a| 
該当なし
 a| 
整数



 a| 
ボリュームサイズ
 a| 
プロビジョニング済み容量の合計（バイト）。
 a| 
該当なし
 a| 
整数



 a| 
ボリューム利用率
 a| 
クライアントによるボリュームの入出力機能の使用状況を、ボリュームの Max IOPS の QoS 設定と比較する浮動小数点値。有効な値は次のとおり

* 0 ：クライアントはボリュームを使用していません。
* 0.01 ~ 0.99 ：クライアントはボリュームの IOPS 機能をフルに活用していません。
* 1.00 ：クライアントは、 Max IOPS 設定までボリュームをフルに利用しています。
* >1.00 ：クライアントは maxIOPS で設定された制限値を超えています。これは、 burstIOPS QoS 設定が maxIOPS よりも高い場合に可能です。たとえば、 maxIOPS が 1000 に設定され、 burstIOPS が 2000 に設定されている場合、クライアントがボリュームを完全に利用すると、「 volumeUtilization 」の値は 2.00 になります。

 a| 
該当なし
 a| 
浮動小数点



 a| 
writeBytes のこと
 a| 
ボリューム作成以降にボリュームに書き込まれた累積バイト総数。
 a| 
単調増加
 a| 
整数



 a| 
writeBytesLastSample
 a| 
最新のサンプル期間中にボリュームに書き込まれたバイト総数。
 a| 
単調増加
 a| 
整数



 a| 
writeLatencyUSec
 a| 
過去 500 ミリ秒の、ボリュームへの書き込み処理を完了するまでの平均時間（マイクロ秒）。
 a| 
ポイントインタイム
 a| 
整数



 a| 
writeLatencyUSecTotal
 a| 
ボリュームへの書き込み処理の実行に費やされた合計時間。
 a| 
単調増加
 a| 
整数



 a| 
writeOps
 a| 
ボリューム作成以降の、ボリュームに対する書き込み処理の累積総数。
 a| 
単調増加
 a| 
整数



 a| 
writeOpsLastSample
 a| 
最新のサンプル期間中の書き込み処理の総数。
 a| 
ポイントインタイム
 a| 
整数



 a| 
ゼロロック
 a| 
前回のガベージコレクション完了後、データが含まれない空の 4KiB ブロックの総数。
 a| 
ポイントインタイム
 a| 
整数

|===