---
permalink: api/reference_element_api_schedule.html 
sidebar: sidebar 
keywords: object,objects,schedule 
summary: schedule オブジェクトには、ボリュームの Snapshot を自動的に作成するために設定されたスケジュールの情報が含まれます。ListSchedules API メソッドを使用すると、すべてのスケジュールの情報を取得できます。 
---
= スケジュール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
schedule オブジェクトには、ボリュームの Snapshot を自動的に作成するために設定されたスケジュールの情報が含まれます。「 ListSchedules 」 API メソッドを使用すると、すべてのスケジュールのスケジュール情報を取得できます。



== オブジェクトメンバー

このオブジェクトのメンバーは次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
属性（ Attributes ）
 a| 
スケジュールの設定頻度を示します。有効な値は次のとおり

* 曜日
* 日にち
* 時間間隔

 a| 
JSON オブジェクト



 a| 
hasError
 a| 
スケジュールにエラーがあるかどうかを示します。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値



 a| 
時間
 a| 
次の Snapshot が作成されるまでの時間を表示します。有効な値は 0~24 です。
 a| 
整数



 a| 
lastRunStatus の順にクリックします
 a| 
最後にスケジュールされた Snapshot のステータスを示します。有効な値は次のとおり

* 成功
* 失敗しました

 a| 
文字列



 a| 
lastRunTimeStart の順にクリックします
 a| 
最後にスケジュールが開始された日時を示します。
 a| 
ISO 8601 形式の日付文字列



 a| 
分
 a| 
次の Snapshot が作成されるまでの分数を表示します。有効な値は 0~59 です。
 a| 
整数



 a| 
月日
 a| 
Snapshot を作成する日にち。
 a| 
配列



 a| 
一時停止中
 a| 
スケジュールが一時停止しているかどうか。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値



 a| 
繰り返し
 a| 
スケジュールを繰り返すかどうか。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値



 a| 
RunNextInterval をクリックします
 a| 
次にスケジューラがアクティブになったときにスケジュールを実行するかどうかを示します。true の場合、次にスケジューラがアクティブになったときにスケジュールが実行され、 false に戻ります。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値



 a| 
scheduleID です
 a| 
スケジュールの一意の ID 。
 a| 
整数



 a| 
scheduleInfo を指定します
 a| 
スケジュールに指定した一意の名前、作成した Snapshot の保持期間、 Snapshot 作成元のボリュームのボリューム ID が含まれます。有効な値：

* enableRemoteReplication ：リモート・レプリケーションにスナップショットを含めるかどうかを指定しますブール値
* `ensureSerialCreation`：以前のSnapshotレプリケーションが進行中の場合に、新しいSnapshotの作成を許可するかどうかを指定します。ブール値
* `name` ：使用するスナップショット名。文字列
* `retention`：Snapshotが保持されている時間。時間に応じて、次のいずれかの形式で表示されます。
+
** FIFO：スナップショットは先入れ先出し（FIFO）ベースで保持されます。空の場合、 Snapshot は無期限に保持されます。文字列
** HH：mm：ss


* volumeID ： Snapshot に含めるボリュームの ID整数
* `volums` ：グループ Snapshot に含めるボリューム ID のリスト。（整数の配列）。

 a| 
JSON オブジェクト



 a| 
スケジュール名
 a| 
スケジュールに割り当てる一意の名前。
 a| 
文字列



 a| 
スケジューラの種類
 a| 
現時点では、サポートされているスケジュールタイプは snapshot だけです。
 a| 
文字列



 a| 
snapMirrorLabel のことです
 a| 
作成された Snapshot またはグループ Snapshot に適用される snapMirrorLabel 。 scheduleInfo に含まれます。設定されていない場合、この値は null です。
 a| 
文字列



 a| 
開始日
 a| 
スケジュールが最初に開始された日、または開始される日。形式は、 UTC 時間形式です。
 a| 
ISO 8601 形式の日付文字列



 a| 
To BeDeleted
 a| 
スケジュールを削除対象としてマークするかどうか。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値



 a| 
平日
 a| 
Snapshot を作成する曜日を示します。
 a| 
配列

|===


== 詳細については、こちらをご覧ください

xref:reference_element_api_listschedules.adoc[ListSchedules （リストスケジュール]
