---
permalink: api/reference_element_api_modifyvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,modifying,modify,change,changing,edit,editing,modifyvolumes 
summary: ModifyVolumes メソッドを使用すると、最大で 500 個の既存のボリュームを一度に設定できます。変更はすぐに反映されます。指定したいずれかのボリュームの変更に ModifyVolumes が失敗した場合、どのボリュームも変更されません。 
---
= ModifyVolumes の場合に使用でき
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 modifyVolumes 」メソッドを使用すると、一度に最大 500 個の既存ボリュームを設定できます。変更はすぐに反映されます。「 modifyVolumes 」で指定されたボリュームのいずれかを変更できない場合、指定されたボリュームはどれも変更されません。

ボリュームを変更するときに QoS 値を指定しない場合、各ボリュームの QoS 値は変更されません。GetDefaultQoS メソッドを実行すると、新しく作成したボリュームのデフォルトの QoS 値を取得できます。

レプリケート中のボリュームのサイズを拡張する必要がある場合は、レプリケーションエラーを回避するために次の手順で実行します。

. replicationTarget アクセスが許可されたボリュームのサイズを拡張します。
. ソース、つまり readWrite アクセスが許可されたボリュームのサイズを拡張します。


ターゲットボリュームとソースボリュームを必ず同じサイズにしてください。


NOTE: アクセスステータスを locked または replicationTarget に変更すると、すべての既存の iSCSI 接続が終了します。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
にアクセスします
 a| 
ボリュームに許可するアクセス。有効な値は次のとおり

* `re adOnly` ：読み取り操作のみが許可されます。
* 「 readWrite 」：読み取りと書き込みが可能です。
* 'locked] ：読み取りや書き込みは許可されません。指定しない場合、アクセス値は変更されません。
* 「リプリケーションターゲット」：ペアリングされたボリュームセットのターゲットボリュームとしてボリュームを指定します。ボリュームがペアリングされていない場合、アクセスステータスは locked になります。値を指定しない場合、アクセス値は変更されません。

 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
アカウント ID
 a| 
ボリュームを再割り当てするアカウント ID 。指定しない場合は、以前のアカウント名が使用されます。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
associateWithQoSPolicy
 a| 
指定した QoS ポリシーにボリュームを関連付けます。有効な値は次のとおり

* `true` ： QoSPolicy パラメータで指定された QoS ポリシーにボリュームを関連付けます。
* `false` ： QoSPolicy パラメータで指定された QoS ポリシーにボリュームを関連付けないでください。false の場合、 QoSPolicy パラメータで QoS ポリシーを指定したかどうかに関係なく、既存のポリシーの関連付けが削除されます。

 a| 
ブール値
 a| 
なし
 a| 
いいえ



 a| 
属性（ Attributes ）
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSON オブジェクト
 a| 
なし
 a| 
いいえ



 a| 
CreateTime をクリックします
 a| 
新しいボリューム作成日として設定する ISO 8601 形式の日付文字列。setCreateTime を true に設定した場合は必須です。
 a| 
ISO 8601 形式の文字列
 a| 
なし
 a| 
いいえ



 a| 
dontMoveforIopsRebalance
 a| 
実際のIOPSでロードバランシングを行う際にボリュームを移動しないようにします。この設定はElement 12.8以降で使用でき、が有効な場合にのみ有効です。link:reference_element_api_enablefeature.html["VolumeLoadBalanceOnActualIOPS"]有効な値：

* `true`：実際のIOPSに基づいてボリュームの負荷が分散されません。
* `false`：ボリュームは実際のIOPSに基づいて負荷を分散します。


*注*：高可用性（ノード障害）のバランスは、および `dontMoveforIopsRebalance`よりも優先され `VolumeLoadBalanceOnActualIOPS`ます。
| ブール値 | いいえ | いいえ 


 a| 
enableSnapMirrorReplication
 a| 
ボリュームを SnapMirror エンドポイントでのレプリケーションに使用できるかどうかを指定します。有効な値は次のとおり

* 「真」
* 「偽」

 a| 
ブール値
 a| 
いいえ
 a| 
いいえ



| 50 サイズ | ボリュームでサポートされる FIFO （ First-In First-Out ）スナップショットの最大数を指定します。FIFO スナップショットと非 FIFO スナップショットはどちらも、ボリューム上で使用可能なスナップショットスロットの同じプールを使用することに注意してください。このオプションを使用して、使用可能なスナップショットスロットの FIFO スナップショットの消費を制限します。この値を現在の FIFO スナップショットカウントよりも小さく変更することはできません。 | 整数 | なし | いいえ 


| minFifoSize | FIFO （ First-In First-Out ）スナップショットだけに予約されているスナップショットスロットの数を指定します。FIFO スナップショットと非 FIFO スナップショットは同じプールを共有するため、 minFifoSize パラメータは、可能な非 FIFO スナップショットの合計数を同じ量だけ減らします。この値は、現在の FIFO 以外のスナップショット数と競合するように変更することはできません。 | 整数 | なし | いいえ 


 a| 
モード
 a| 
ボリュームのレプリケーションモード。有効な値は次のとおり

* 「 asynch` 」 : ターゲットに書き込む前に、データがソースに格納されていることをシステムが確認するのを待ちます。
* 「同期」：ソースからのデータ転送の確認応答を待機せずに、ターゲットへのデータの書き込みを開始します。

 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
QoS
 a| 
ボリュームの新しい QoS 設定。指定しない場合、 QoS 設定は変更されません。有効な値は次のとおり

* 「 IOPS 」
* 「最大軸 IOPS 」
* 「 burstIOPS 」

 a| 
xref:reference_element_api_qos.adoc[QoS]
 a| 
なし
 a| 
いいえ



 a| 
qosPolicyID
 a| 
指定したボリュームに適用する QoS 設定が定義されたポリシーの ID 。このパラメータは、 qos パラメータと同時に指定することはできません。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
setCreateTime
 a| 
true に設定すると、記録されているボリューム作成日が変更されます。
 a| 
ブール値
 a| 
なし
 a| 
いいえ



 a| 
合計サイズ
 a| 
ボリュームの新しいサイズ（バイト）。1 、 000 、 000 、 000 は 1GB に相当します。サイズは最も近い MB 単位に切り上げられます。このパラメータは、ボリュームのサイズを拡張する場合にのみ使用できます。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
ボリューム ID
 a| 
変更するボリュームの ID のリスト。
 a| 
整数の配列
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
ボリューム
 a| 
変更された各ボリュームの情報を含むオブジェクトの配列。
 a| 
xref:reference_element_api_volume.adoc[ボリューム] 配列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "ModifyVolumes",
  "params": {
    "volumeIDs": [319,22],
    "access": "readWrite",
    "dontMoveForIopsRebalance": false
  },
  "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "volumes":
      {
        "access":  "readWrite,
        "accountID": 22,
        "attributes": {},
        "blockSize": 4096,
        "createTime": "2024-04-01T19:39:40Z",
        "currentProtectionScheme": "doubleHelix",
        "deleteTime": "",
        "dontMoveForIopsRebalance": false,
        "enable512e": false,
        "enableSnapMirrorReplication": false,
        "fifoSize": 24,
        "iqn": "iqn.2010-01.com.solidfire:3eeu.suite40.319",
        "lastAccessTime": "2024-04-02T12:41:34Z",
        "lastAccessTimeIO": "2024-04-01T20:41:19Z",
        "minFifoSize": 0,
        "name": "suite40",
        "previousProtectionScheme": null,
        "purgeTime": "",
        "qos": {
          "burstIOPS": 27000,
          "burstTime": 60,
          "curve": {
            "1048576": 15000,
            "131072": 1950,
            "16384": 270,
            "262144": 3900,
            "32768": 500,
            "4096": 100,
            "524288": 7600,
            "65536": 1000,
            "8192": 160
          },
          "maxIOPS": 27000,
          "minIOPS": 500
        },
        "qosPolicyID": null,
        "scsiEUIDeviceID": "336565750000013ff47acc0100000000",
        "scsiNAADeviceID": "6f47acc100000000336565750000013f",
        "sliceCount": 1,
        "status": "active",
        "totalSize": 1000000716800,
        "virtualVolumeID": null,
        "volumeAccessGroups": [
        22
        ],
        "volumeConsistencyGroupUUID": "3003109e-6e75-444c-8cee-470d641a09c3",
        "volumeID": 319,
        "volumePairs": [],
        "
      }
  }
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS の設定]
