---
permalink: api/reference_element_api_listvolumestatsbyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,access,group,listvolumestatsbyvolumeaccessgroup,activity 
summary: ListVolumeStatsByVolumeAccessGroup メソッドを使用すると、指定したボリュームアクセスグループのメンバーであるすべてのボリュームのアクティビティ測定値の合計をリストできます。 
---
= ListVolumeStatsByVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 ListVolumeStatsByVolumeAccessGroup 」メソッドを使用すると、指定したボリュームアクセスグループのメンバーであるすべてのボリュームのアクティビティ測定値の合計をリストできます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
includeVirtualVolumes などです
 a| 
デフォルトでは仮想ボリュームは応答に含まれます。仮想ボリュームを除外するには、 false に設定します。
 a| 
ブール値
 a| 
正しいです
 a| 
いいえ



 a| 
volumeAccessGroups
 a| 
ボリュームアクティビティが返されるボリュームアクセスグループ ID の配列。省略すると、すべてのボリュームアクセスグループの統計が返されます。
 a| 
整数の配列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
ボリューム統計
 a| 
指定したボリュームアクセスグループ内のすべてのボリュームのボリュームアクティビティ情報のリスト。 * メモ：この値はアカウントが所有するすべてのボリュームの合計を表すため、各エントリのボリューム ID メンバーは 0 です。
 a| 
xref:reference_element_api_volumestats.adoc[ボリューム統計]

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "ListVolumeStatsByVolumeAccessGroup",
    "params": {"volumeAccessGroups": [1]},
    "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 0,
        "nonZeroBlocks": 149366393,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T21:04:10.712370Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 0,
        "volumeSize": 1073741824000,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 112777607
      }
    ]
  }
}
----


== 新規導入バージョン

9.6
