---
permalink: api/reference_element_api_addclusteradmin.html 
sidebar: sidebar 
keywords: addclusteradmin,cluster,admin,administrator,adding,add 
summary: AddClusterAdmin メソッドを使用して、新しいクラスタ管理者アカウントを追加できます。クラスタ管理者は、 API および管理ツールを使用してクラスタを管理できます。クラスタ管理者アカウントは標準のテナントアカウントと完全に別のもので、関連性はありません。 
---
= AddClusterAdmin
:icons: font
:imagesdir: ../media/


[role="lead"]
AddClusterAdmin メソッドを使用して、新しいクラスタ管理者アカウントを追加できます。クラスタ管理者は、 API および管理ツールを使用してクラスタを管理できます。クラスタ管理者アカウントは標準のテナントアカウントと完全に別のもので、関連性はありません。

各クラスタ管理者が使用できる API を限定できます。異なるユーザやアプリケーションに対しては、複数のクラスタ管理者アカウントを使用する必要があります。ベストプラクティスとして、各クラスタ管理者に必要な最小限の権限を付与することを推奨します。そうすることで、クレデンシャルの侵害が発生した場合の影響を軽減できます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
にアクセスします
 a| 
クラスタ管理者が使用できるメソッドを制御します。
 a| 
文字列の配列
 a| 
なし
 a| 
はい。



 a| 
アクセトゥーラ
 a| 
エンドユーザライセンス契約に同意します。システムにクラスタ管理者アカウントを追加するには、 true に設定します。省略するか false に設定すると、メソッド呼び出しは失敗します。
 a| 
ブール値
 a| 
なし
 a| 
はい。



 a| 
属性（ Attributes ）
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSON オブジェクト
 a| 
なし
 a| 
いいえ



 a| 
パスワード
 a| 
このクラスタ管理者の認証に使用するパスワード。
 a| 
文字列
 a| 
なし
 a| 
はい。



 a| 
ユーザ名
 a| 
このクラスタ管理者の一意のユーザ名。1~1024 文字で指定する必要があります。
 a| 
文字列
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
clusterAdminID
 a| 
新たに作成されたクラスタ管理者の ID 。
 a| 
整数

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "AddClusterAdmin",
  "params": {
    "username": "joeadmin",
    "password": "68!5Aru268)$",
    "attributes": {},
    "acceptEula": true,
    "access": ["volumes", "reporting", "read"]
  },
  "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id":1,
  "result" : {
    "clusterAdminID": 2
   }
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

xref:reference_element_api_app_b_access_control.adoc[Access Control の略]
