---
permalink: api/reference_element_api_getstoragecontainerefficiency.html 
sidebar: sidebar 
keywords: volume,virtual,container,volumes,get,getting,efficiency,vvol,GetStorageContainerEfficiency 
summary: GetStorageContainerEfficiency メソッドを使用すると、仮想ボリュームストレージコンテナの効率性に関する情報を取得できます。 
---
= GetStorageContainerEfficiency を使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
GetStorageContainerEfficiency メソッドを使用すると、仮想ボリュームストレージコンテナの効率性に関する情報を取得できます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
storageContainerID です
 a| 
効率性に関する情報を取得するストレージコンテナの ID 。
 a| 
整数
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
圧縮
 a| 
ストレージコンテナ内のすべての仮想ボリュームの、データ圧縮によって削減された容量。値は比率で示され、「 1 」はデータが圧縮されずに格納されたことを意味します。
 a| 
浮動小数点



 a| 
重複排除
 a| 
ストレージコンテナ内のすべての仮想ボリュームの、データの重複排除によって削減された容量。比率として示されます。
 a| 
浮動小数点



 a| 
missingVolumes
 a| 
効率性に関するデータを照会できなかった仮想ボリューム。原因としては、ガベージコレクション（ GC ）サイクルから 1 時間経過していない、一時的なネットワーク接続の切断、または GC サイクル後のサービスの再起動があります。
 a| 
整数の配列



 a| 
シンプロビジョニング
 a| 
使用済みスペースとデータの格納用に割り当てられたスペースの比率。比率として示されます。
 a| 
浮動小数点



 a| 
タイムスタンプ
 a| 
GC 後に効率性に関するデータが収集された最後の時刻。
 a| 
ISO 8601 形式の日付文字列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "GetStorageContainerEfficiency",
  "params": {
    "storageContainerID" : "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1"
  },
  "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "compression": 1,
    "deduplication": 1,
    "missingVolumes": [],
    "thinProvisioning": 1,
    "timestamp": "2016-04-12T15:39:49Z"
  }
}
----


== 新規導入バージョン

9.6
