---
permalink: api/reference_element_api_abortsnapmirrorrelationship.html 
sidebar: sidebar 
keywords:  
summary: Element ソフトウェア Web UI は、 AbortSnapMirrorRelationship メソッドを使用して、開始されてまだ完了していない SnapMirror 転送を停止します。 
---
= AbortSnapMirrorRelationship のこと
:icons: font
:imagesdir: ../media/


[role="lead"]
Element ソフトウェア Web UI は、「 AbortSnapMirrorRelationship 」メソッドを使用して、開始されてまだ完了していない SnapMirror 転送を停止します。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
snapMirrorEndpointID
 a| 
Element ストレージクラスタと通信するリモート ONTAP ストレージシステムのエンドポイント ID 。
 a| 
整数
 a| 
なし
 a| 
はい。



 a| 
デスティネーションボリューム
 a| 
SnapMirror 関係のデスティネーションボリューム。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
なし
 a| 
はい。



 a| 
clearCheckpoint
 a| 
再開チェックポイントを消去するかどうかを決定します。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値
 a| 
いいえ
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
snapMirrorRelationship のこと
 a| 
中止された SnapMirror 関係の情報を含むオブジェクト。
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship のこと]

|===


== 新規導入バージョン

10.1
