---
permalink: api/reference_element_api_clusterstats.html 
sidebar: sidebar 
keywords: objects,clusterStats 
summary: clusterStats オブジェクトには、クラスタの統計データが含まれます。このオブジェクトに含まれるボリューム関連の統計の多くは、クラスタ内のすべてのボリュームの平均値です。GetClusterStats メソッドを使用すると、クラスタの統計情報を取得できます。 
---
= clusterStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clusterStats オブジェクトには、クラスタの統計データが含まれます。このオブジェクトに含まれるボリューム関連の統計の多くは、クラスタ内のすべてのボリュームの平均値です。GetClusterStats メソッドを使用すると、クラスタの統計情報を取得できます。



== オブジェクトメンバー

このオブジェクトのメンバーは次のとおりです。

|===
| 名前 | 説明 | 計算 | を入力します 


 a| 
実際の IOPS
 a| 
直近 500 ミリ秒の、クラスタ全体の最新かつ実際の IOPS 。
 a| 
ポイントインタイム
 a| 
整数



 a| 
平均 IOPSize
 a| 
直近 500 ミリ秒の、クラスタへの最新の I/O の平均サイズ（バイト）。
 a| 
ポイントインタイム
 a| 
整数



 a| 
クライアントキュー深度
 a| 
クラスタに対する未処理の読み取り処理と書き込み処理の数。
 a| 
該当なし
 a| 
整数



 a| 
クラスタ利用率
 a| 
現在使用されているクラスタの最大 IOPS の割合。この値は、 clusterUtilization = normalizedIOPS/ maxIOPS （ GetClusterCapacity から）と計算されます。
 a| 
該当なし
 a| 
浮動小数点



 a| 
遅延時間
 a| 
過去 500 ミリ秒の、クラスタへの処理が完了した平均時間（マイクロ秒）。
 a| 
ポイントインタイム
 a| 
整数



 a| 
正常化された IOPS
 a| 
過去 500 ミリ秒の、クラスタ全体の平均 IOPS 。
 a| 
ポイントインタイム
 a| 
整数



 a| 
readBytes
 a| 
クラスタ作成以降にクラスタから読み取られた累積バイト総数。
 a| 
単調増加
 a| 
整数



 a| 
readBytesLastSample
 a| 
最新のサンプル期間中にクラスタから読み取られたバイト総数。
 a| 
ポイントインタイム
 a| 
整数



 a| 
readLatencyUSec
 a| 
直近 500 ミリ秒の、クラスタへの読み取り処理を完了するまでの平均時間（マイクロ秒）。
 a| 
ポイントインタイム
 a| 
整数



 a| 
readLatencyUSecTotal
 a| 
クラスタの作成以降に読み取り処理の実行に費やされた合計時間。
 a| 
単調増加
 a| 
整数



 a| 
readOps
 a| 
クラスタ作成以降にクラスタに対して行った読み取り処理の累積総数。
 a| 
単調増加
 a| 
整数



 a| 
readOpsLastSample
 a| 
最新のサンプル期間中の読み取り処理の総数。
 a| 
ポイントインタイム
 a| 
整数



 a| 
samplePeriodMSec
 a| 
サンプル期間の長さ（ミリ秒単位）。
 a| 
該当なし
 a| 
整数



 a| 
サービス数
 a| 
クラスタで実行されているサービスの数。servicesTotal と等しい場合、すべてのノードから有効な統計が収集されたことを示します。
 a| 
ポイントインタイム
 a| 
整数



 a| 
サービス合計
 a| 
クラスタで実行されていると想定されるサービスの総数。
 a| 
該当なし
 a| 
整数



 a| 
タイムスタンプ
 a| 
現在の時刻（ UTC+0 形式）。
 a| 
該当なし
 a| 
ISO 8601 形式の日付文字列



 a| 
アン・アライナード・償還
 a| 
クラスタ作成以降の、クラスタに対するアライメントされていない読み取り処理の累積総数。
 a| 
単調増加
 a| 
整数



 a| 
アンアライナードライト
 a| 
クラスタ作成以降の、クラスタに対するアライメントされていない書き込み処理の累積総数。
 a| 
単調増加
 a| 
整数



 a| 
writeBytes のこと
 a| 
クラスタ作成以降にクラスタに書き込まれた累積バイト総数。
 a| 
単調増加
 a| 
整数



 a| 
writeBytesLastSample
 a| 
最新のサンプル期間中にクラスタに書き込まれたバイト総数。
 a| 
単調増加
 a| 
整数



 a| 
writeLatencyUSec
 a| 
過去 500 ミリ秒の、クラスタへの書き込み処理を完了するまでの平均時間（マイクロ秒）。
 a| 
ポイントインタイム
 a| 
整数



 a| 
writeLatencyUSecTotal
 a| 
クラスタの作成以降に書き込み処理の実行に費やされた合計時間。
 a| 
単調増加
 a| 
整数



 a| 
writeOps
 a| 
クラスタ作成以降にクラスタに対して行った書き込み処理の累積総数。
 a| 
単調増加
 a| 
整数



 a| 
writeOpsLastSample
 a| 
最新のサンプル期間中の書き込み処理の総数。
 a| 
ポイントインタイム
 a| 
整数

|===


== 詳細については、こちらをご覧ください

xref:reference_element_api_getclusterstats.adoc[GetClusterStats から参照できます]
