---
permalink: api/reference_element_api_removedrives.html 
sidebar: sidebar 
keywords: cluster,drive,drives,remove,removing,removedrives 
summary: RemoveDrives メソッドを使用すると、クラスタの一部であるドライブをプロアクティブに削除できます。このメソッドは、クラスタの容量を減らしたり、サービス寿命の終わりに近づいているドライブの交換準備を行ったりするときに使用できます。ドライブをクラスタから削除する前に、ドライブ上のすべてのデータが削除され、クラスタ内の他のドライブに移行されます。 
---
= RemoveDrives の 2 つのコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `RemoveDrives` クラスタの一部であるドライブをプロアクティブに削除する方法。このメソッドは、クラスタの容量を減らしたり、サービス寿命の終わりに近づいているドライブの交換準備を行ったりするときに使用できます。 `RemoveDrives` クラスタ内の他のノードにブロックデータの3つ目のコピーを作成し、同期が完了するのを待ってからドライブを「使用可能」のリストに移動します。[使用可能]リストのドライブはシステムから完全に削除され、実行中のサービスやアクティブデータはありません。

RemoveDrives は非同期メソッドです削除するドライブの合計容量によっては、すべてのデータを移行するのに数分かかることがあります。

複数のドライブを削除する場合は '1 つのドライブごとに複数の個別メソッドを使用するのではなく '1 回の RemoveDrives メソッド呼び出しを使用してくださいこれにより、クラスタのストレージ負荷を一定にするために実施する必要のあるデータバランシングの量が減少します。

RemoveDrives を使用すると、「 failed 」ステータスのドライブも取り外すことができます。ステータスが「 failed 」のドライブを取り外しても、ドライブは「 Available 」または「 Active 」には戻りません。ドライブはクラスタ内で使用できません。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ドライブ
 a| 
クラスタから取り外すドライブ ID のリスト。
 a| 
整数の配列
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
asyncHandle
 a| 
処理結果の取得に使用されるハンドル値。
 a| 
整数

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "RemoveDrives",
   "params": {
      "drives"  : [3, 4, 5]
   },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id": 1,
   "result" : {
     "asyncHandle": 1
   }
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult]
* xref:reference_element_api_listdrives.adoc[ListDrives の 2 つのメソッド]

