---
permalink: api/reference_element_api_drive.html 
sidebar: sidebar 
keywords: objects,object,drive 
summary: drive オブジェクトには、クラスタ内の Active 状態のノードの個々のドライブに関する情報が含まれます。このオブジェクトには、ボリュームメタデータまたはブロックドライブとして追加されたドライブのほか、まだ追加されていないが使用可能なドライブの詳細が含まれます。ListDrives API メソッドを使用すると、以下の情報を取得できます。 
---
= ドライブ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
drive オブジェクトには、クラスタ内の Active 状態のノードの個々のドライブに関する情報が含まれます。このオブジェクトには、ボリュームメタデータまたはブロックドライブとして追加されたドライブのほか、まだ追加されていないが使用可能なドライブの詳細が含まれます。これらの情報は 'ListDrives' API メソッドを使用して取得できます



== オブジェクトメンバー

このオブジェクトのメンバーは次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
属性（ Attributes ）
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。このオブジェクトは常に null であり、変更できません。
 a| 
JSON オブジェクト



 a| 
容量
 a| 
ドライブの合計容量（バイト）。
 a| 
整数



 a| 
シャーシスロット
 a| 
HCI プラットフォームの場合、このドライブが配置されているサーバシャーシ内のノードのドライブレターとスロット番号です。ストレージプラットフォームの場合、スロット番号は「 slot 」の整数の文字列表現です。
 a| 
文字列



 a| 
driveFailureDetail
 a| 
ドライブのステータスが「 Failed 」の場合は、ドライブが障害状態とマークされた理由がこのフィールドに詳細に表示されます。
 a| 
文字列



 a| 
driveID
 a| 
このドライブの ID 。
 a| 
整数



 a| 
driveSecurityFaultReason
 a| 
ドライブセキュリティを有効または無効にできなかった場合は、失敗した理由。値が「 none 」の場合はエラーはありません。
 a| 
文字列



 a| 
キー ID
 a| 
キープロバイダがこのドライブのロックを解除するための認証キーを取得するために使用するキー ID 。
 a| 
UUID



 a| 
KeyProviderID
 a| 
このドライブのロックを解除するための認証キーのプロバイダを指定します。
 a| 
整数



 a| 
ノード ID
 a| 
このドライブが含まれるノードの ID 。
 a| 
整数



 a| 
SegmentFileSize の順に選択します
 a| 
ドライブのセグメントファイルサイズ（バイト）。
 a| 
整数



 a| 
Serial （シリアル）
 a| 
ドライブのシリアル番号。
 a| 
文字列



 a| 
スロット
 a| 
このドライブを配置するサーバシャーシのスロット番号です。 SATADimm デバイスが内部メタデータドライブとして使用されている場合には「 -1 」になります。
 a| 
整数



 a| 
ステータス
 a| 
ドライブのステータス。有効な値は次のとおり

* Available ：使用可能なドライブです。
* active ：アクティブドライブ。
* erasing ：ドライブは完全消去中です。このドライブ上のデータは完全に消去されます。
* failed ：障害が発生したドライブ。このドライブに以前保存されていたデータは、クラスタ内の他のドライブに移行されました。
* removing ：ドライブは現在消去中です。このドライブに以前保存されていたデータをクラスタ内の他のドライブに移行しています。

 a| 
文字列



 a| 
を入力します
 a| 
ドライブのタイプ。有効な値は次のとおり

* volume ：ボリュームメタデータを保存します。
* block ：ブロックデータを保存します。
* unknown ：まだアクティブではない、未特定のドライブタイプです。

 a| 
文字列



 a| 
使用可能容量
 a| 
ドライブの使用可能容量（バイト）。
 a| 
整数

|===


== 詳細については、こちらをご覧ください

xref:reference_element_api_listdrives.adoc[ListDrives の 2 つのメソッド]
