---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: TestPing メソッドを使用すると、 1G および 10G の両方のインターフェイスで、 ICMP パケットを使用してクラスタ内のすべてのノードへのネットワーク接続をテストできます。テストでは、ネットワーク設定の MTU 設定に基づいて、パケットごとに適切な MTU サイズを使用します。TestPing では、一時的な VLAN インターフェイスは作成されません。 
---
= TestPing です
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 TestPing 」メソッドを使用すると、 1G および 10G の両方のインターフェイスで、 ICMP パケットを使用してクラスタ内のすべてのノードへのネットワーク接続をテストできます。テストでは、ネットワーク設定の MTU 設定に基づいて、パケットごとに適切な MTU サイズを使用します。「 TestPing 」では、一時的な VLAN インターフェイスは作成されません。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
試行回数
 a| 
ping テストを繰り返す回数を指定します。
 a| 
整数
 a| 
5.
 a| 
いいえ



 a| 
ホスト
 a| 
ping を実行するデバイスのアドレスまたはホスト名をカンマで区切って指定します。ホストを指定しない場合は、ストレージクラスタ内のホストに対して ping が実行されます。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
インターフェイス
 a| 
ping の送信元となる既存の（ベース）インターフェイス。有効な値は次のとおり

* 「 Bond10G 」： Bond10G インターフェイスから ping を送信します。
* 「 Bond1G 」： Bond1G インターフェイスから ping を送信します。

 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
パケットサイズ
 a| 
各 IP に送信される ICMP パケットで送信するバイト数を指定します。ネットワーク設定で指定されている最大 MTU より小さい値を指定する必要があります。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
pingTimeoutMsec
 a| 
個々の ping 応答を待機する時間をミリ秒単位で指定します。
 a| 
整数
 a| 
500 ミリ秒
 a| 
いいえ



 a| 
禁止断片化
 a| 
ICMP パケットの DF （ Do not Fragment ）フラグを有効にします。
 a| 
ブール値
 a| 
いいえ
 a| 
いいえ



 a| 
sourceAddressV4
 a| 
ICMP ping パケットで使用する送信元 IPv4 アドレス。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
sourceAddressV6 と入力します
 a| 
ICMP ping パケットで使用する送信元 IPv6 アドレス。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
totalTimeoutSec
 a| 
ping の次の試行を発行するかプロセスを終了するまでに、 ping がシステム応答を待機する時間を秒単位で指定します。
 a| 
整数
 a| 
5.
 a| 
いいえ



 a| 
virtualNetworkTag
 a| 
ping パケットの送信時に使用する VLAN ID 。
 a| 
整数
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
詳細
 a| 
ノードが通信できた各 IP のリストと ping 応答の統計情報。
 a| 
JSON オブジェクト

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== 新規導入バージョン

5.0
