---
permalink: api/reference_element_api_enablemaintenancemode.html 
sidebar: sidebar 
keywords: maintenance,enable,mode 
summary: EnableMaintenanceMode メソッドを使用して、ストレージノードをメンテナンス用に準備できます。メンテナンスシナリオには、ノードの電源をオフにしたり再起動したりする必要のあるタスクが含まれます。 
---
= EnableMaintenanceMode のようになります
:icons: font
:imagesdir: ../media/


[role="lead"]
「 EnableMaintenanceMode 」メソッドを使用すると、ストレージ・ノードをメンテナンス用に準備できます。メンテナンスシナリオには、ノードの電源をオフにしたり再起動したりする必要のあるタスクが含まれます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
forceWithUnresolvedFaults
 a| 
クラスタ障害がブロックされている場合でも、このノードに対して強制的にメンテナンスモードを有効にします。
 a| 
ブール値
 a| 
いいえ
 a| 
いいえ



 a| 
ノード
 a| 
保守モードにするノード ID のリスト。一度に 1 つのノードのみがサポートされます。
 a| 
整数の配列
 a| 
なし
 a| 
はい。



 a| 
perMinutePrimarySwapLimit のように表示されます
 a| 
1 分間にスワップするプライマリスライスの数。指定しない場合、すべてのプライマリスライスが一度にスワップされます。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
タイムアウト
 a| 
メンテナンスモードが自動的に無効になるまで有効にしておく期間を指定します。時間文字列（ HH ： MM ： ss など）でフォーマットされます。指定しない場合、保守モードは明示的に無効にするまで有効なままになります。
 a| 
文字列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
asyncHandle
 a| 
GetAsyncResult メソッドを使用してこの asyncHandle を取得し、メンテナンスモードの移行が完了したかどうかを判断できます。
 a| 
整数



 a| 
currentMode です
 a| 
ノードの現在の保守モードの状態。有効な値は次のとおり

* 無効：メンテナンスは要求されていません。
* FailedToRecover ：ノードのメンテナンスモードからのリカバリに失敗しました。
* RecoveringFromMaintenance ：ノードはメンテナンスモードからリカバリ中です。
* 準備メンテナンス：ノードのメンテナンスを実施するための準備作業を実施します。
* ReadyForMaintenance ：ノードのメンテナンスを実行できる状態です。

 a| 
MaintenanceMode ( 文字列 )



 a| 
requestedMode
 a| 
ノードに対して要求されたメンテナンスモードの状態。有効な値は次のとおり

* 無効：メンテナンスは要求されていません。
* FailedToRecover ：ノードのメンテナンスモードからのリカバリに失敗しました。
* RecoveringFromMaintenance ：ノードはメンテナンスモードからリカバリ中です。
* 準備メンテナンス：ノードのメンテナンスを実施するための準備作業を実施します。
* ReadyForMaintenance ：ノードのメンテナンスを実行できる状態です。

 a| 
MaintenanceMode ( 文字列 )

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "EnableMaintenanceMode",
  "params": {
    "forceWithUnresolvedFaults": False,
    "nodes": [6],
    "perMinutePrimarySwapLimit" : 40,
    "timeout" : "01:00:05"
  },
"id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "ReadyForMaintenance",
        "asyncHandle": 1,
        "currentMode": "Disabled"
    }
}
----


== 新規導入バージョン

12.2



== 詳細については、こちらをご覧ください

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["NetApp HCI ストレージメンテナンスモードの概念"^]
