---
permalink: api/reference_element_api_deletevolumes.html 
sidebar: sidebar 
keywords: volumes,volume,delete,deleting,multiple,DeleteVolumes 
summary: DeleteVolumes メソッドを使用すると、複数のアクティブなボリューム（最大 500\ ）を削除対象としてマークできます。マークされたボリュームは、クリーンアップ間隔の経過後にパージされます \ （完全に削除されます \ ）。 
---
= DeleteVolumes
:icons: font
:imagesdir: ../media/


[role="lead"]
「ボリューム」メソッドを使用すると、複数（最大 500 個）のアクティブなボリュームを削除対象としてマークできます。マークされたボリュームは、クリーンアップ間隔の経過後にパージされます（完全に削除されます）。

ボリュームの削除を要求すると、ボリュームへのアクティブな iSCSI 接続はただちに終了します。ボリュームが削除対象としてマークされている間、接続は許可されません。マークされたボリュームは、ターゲットの検出要求では返されません。

削除対象としてマークされたボリュームの Snapshot は影響を受けません。Snapshot は、ボリュームがシステムからパージされるまで保持されます。削除対象としてマークされたボリュームで、ボリュームの一括読み取り / 書き込み処理が実行中の場合、その処理は停止します。

削除するボリュームが別のボリュームとペアになっている場合、ペアボリューム間のレプリケーションは中断されます。削除状態の間、そのボリュームのデータは転送されません。削除されたボリュームとペアになっていたリモートボリュームは PausedMisconfigured 状態になり、削除されたボリュームとの間ではデータは送受信されません。削除されたボリュームがパージされるまでは、ボリュームをリストアしてデータ転送を再開できます。削除されたボリュームがシステムからパージされると、ペアになっていたボリュームは StoppedMisconfigured 状態になり、ボリュームペアリングのステータスが削除されます。パージされたボリュームは完全に使用できなくなります。



== パラメータ

このメソッドの入力パラメータは次のとおりです。


NOTE: 次のパラメータのうち、少なくとも 1 つが必要です。また、どちらか一方だけを使用する必要があります（すべてのパラメータが相互に排他的です）。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ボリューム ID
 a| 
システムから削除するボリュームの ID のリスト。
 a| 
整数の配列
 a| 
なし
 a| 
注を参照してください。



 a| 
ボリュームアクセスグループ ID
 a| 
ボリュームアクセスグループ ID のリスト。このリストで指定したすべてのボリュームアクセスグループのすべてのボリュームがシステムから削除されます。
 a| 
整数の配列
 a| 
なし
 a| 
注を参照してください。



 a| 
アカウント ID
 a| 
アカウント ID のリスト。指定したアカウントのすべてのボリュームがシステムから削除されます。
 a| 
整数の配列
 a| 
なし
 a| 
注を参照してください。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
個のボリューム
 a| 
削除されたボリュームに関する情報。
 a| 
xref:reference_element_api_volume.adoc[ボリューム]



 a| 
カーブ（ Curve ）
 a| 
curve は一連のキーと値のペアです。キーはバイト単位の I/O サイズです。値は、特定の I/O サイズで IOP を実行する際のコストを表します。curve は、 100 IOPS での 4 、 096 バイトの処理セットと比較して計算されます。
 a| 
JSON オブジェクト

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "DeleteVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----

{
  "id" : 1,
  "result": {
    "volumes" : [ {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {},
      "blockSize": 4096,
      "createTime": "2015-03-06T18:50:56Z",
      "deleteTime": "",
      "enable512e": False,
      "iqn": "iqn.2010-01.com.solidfire:pzsr.vclient-030-v00001.1",
      "name": "vclient-030-v00001",
      "qos": {
        "burstIOPS": 15000,
        "burstTime": 60,
        "curve": {},
        "maxIOPS": 15000,
        "minIOPS": 100
      },
      "purgeTime": "",
      "sliceCount": 1,
      "scsiEUIDeviceID": "707a737200000001f47acc0100000000",
      "scsiNAADeviceID": "6f47acc100000000707a737200000001",
      "status": "active",
      "totalSize": 10000003072,
      "virtualVolumeID": 5,
      "volumeAccessGroups": [],
      "volumePairs": [],
      "volumeID": 1
    } ]
  }
}
----


== 新規導入バージョン

9.6
