---
permalink: api/reference_element_api_modifygroupsnapshot.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,group,snapshot,modifygroupsnapshot 
summary: ModifyGroupSnapshot を使用すると、 Snapshot のグループの属性を変更できます。また、このメソッドを使用すると、読み取り / 書き込みボリューム（ソース）で作成された Snapshot を、ターゲットストレージシステムにリモートでレプリケートできます。 
---
= ModifyGroupSnapshot の追加
:icons: font
:imagesdir: ../media/


[role="lead"]
「 ModyGroupSnapshot 」を使用して、スナップショットのグループの属性を変更できます。また、このメソッドを使用すると、読み取り / 書き込み（ソース）ボリュームで作成された Snapshot を、ターゲットストレージシステムにリモートでレプリケートできます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===


| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
enableRemoteReplication
 a| 
作成した Snapshot をリモートクラスタにレプリケートできるようにします。有効な値は次のとおり

* True ：スナップショットはリモート・ストレージにレプリケートされます
* 'false': スナップショットはリモート・ストレージにレプリケートされません

 a| 
ブール値
 a| 
いいえ
 a| 
いいえ



 a| 
有効期限
 a| 
Snapshot を削除するまでの時間を指定します。保持とともに使用することはできません。元の Snapshot の有効期限または保持期間がどちらも指定されていない場合、 Snapshot は期限切れになりません。時刻の形式は、時間ベースの期限を表す ISO 8601 形式の日付文字列であり、それ以外の場合は期限切れになりません。値が null の場合 ' スナップショットは永続的に保持されますFIFO の値を設定すると、ボリューム上の他の FIFO スナップショットと比較して、 FIFO （ First-In First-Out ）ベースでスナップショットが保持されます。使用可能な FIFO 領域がない場合、 API は失敗します。
 a| 
ISO 8601 形式の日付文字列
 a| 
なし
 a| 
いいえ



 a| 
名前
 a| 
グループ Snapshot の名前。名前を入力しない場合、グループ Snapshot の作成日時が使用されます。最大文字数は 255 文字です。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
groupSnapshotID
 a| 
Snapshot のグループの ID 。
 a| 
文字列
 a| 
なし
 a| 
はい。



 a| 
snapMirrorLabel のことです
 a| 
SnapMirror エンドポイントでの Snapshot 保持ポリシーを指定するために SnapMirror ソフトウェアで使用されるラベル。
 a| 
文字列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
groupSnapshot
 a| 
変更されたグループ Snapshot の情報を含むオブジェクト。
 a| 
xref:reference_element_api_groupsnapshot.adoc[groupSnapshot]

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "id": 695,
  "method": "ModifyGroupSnapshot",
  "params": {
    "groupSnapshotID": 3,
    "enableRemoteReplication": true,
    "expirationTime": "2016-04-08T22:46:25Z"
  }
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 695,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-06T17:31:41Z",
      "groupSnapshotID": 3,
      "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-06T17:31:41Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2016-04-08T22:46:25Z",
          "groupID": 3,
          "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
          "name": "grpsnap1-2",
          "snapshotID": 2,
          "snapshotUUID": "719b162c-e170-4d80-b4c7-1282ed88f4e1",
          "status": "done",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "grpsnap1",
      "status": "done"
    }
  }
}
----


== 新規導入バージョン

9.6
