---
permalink: api/reference_element_api_getsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,information,info,get,getting 
summary: GetSnmpInfo メソッドを使用すると、現在の簡易ネットワーク管理プロトコル（ SNMP ）の設定情報を取得できます。 
---
= GetSnmpInfo を追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 GetSnmpInfo 」メソッドを使用すると、現在の簡易ネットワーク管理プロトコル（ SNMP ）の設定情報を取得できます。



== パラメータ


NOTE: Element バージョン 8.0 以降のバージョンでは、 GetSnmpInfo は廃止されています。。 xref:reference_element_api_getsnmpstate.adoc[GetSnmpState] および xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL の場合] メソッドは、 GetSnmpInfo メソッドに代わるものです。

このメソッドには入力パラメータはありません。



== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
ネットワーク
 a| 
SNMP で有効なネットワークとアクセスタイプのリスト。* 注： * ネットワークは、 SNMP v3 が無効な場合にのみ表示されます。
 a| 
xref:reference_element_api_network_snmp.adoc[ネットワーク]



 a| 
有効
 a| 
クラスタ内のノードが SNMP 用に設定されているかどうか。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値



 a| 
snmpV3Enabled を使用します
 a| 
クラスタ内のノードが SNMP v3 用に設定されている場合。有効な値は次のとおり

* 正しいです
* いいえ

 a| 
ブール値



 a| 
usmUsers
 a| 
SNMP v3 が有効になっている場合は、 SNMP のユーザアクセスパラメータのリストがクラスタから返されます。このパラメータは networks パラメータの代わりに返されます。
 a| 
xref:reference_element_api_usmuser.adoc[usmUser]

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "GetSnmpInfo",
   "params": {},
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
   "id" : 1,
   "result" : {
      "enabled" : true,
      "networks" : [
         {
            "access" : "rosys",
            "cidr" : 0,
            "community" : "public",
            "network" : "localhost"
         }
      ]
   }
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

* xref:reference_element_api_getsnmpstate.adoc[GetSnmpState]
* xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL の場合]

