---
permalink: api/reference_element_api_deletevolume.html 
sidebar: sidebar 
keywords: volume,volumes,delete,deleting,DeleteVolume 
summary: DeleteVolume メソッドを使用すると、アクティブなボリュームを削除対象としてマークできます。マークされたボリュームは、クリーンアップ間隔の経過後にパージされます \ （完全に削除されます \ ）。 
---
= DeleteVolume
:icons: font
:imagesdir: ../media/


[role="lead"]
「ボリュームの削除」メソッドを使用すると、アクティブなボリュームを削除対象としてマークできます。マークされたボリュームは、クリーンアップ間隔の経過後にパージされます（完全に削除されます）。

ボリュームの削除を要求すると、ボリュームへのアクティブな iSCSI 接続はただちに終了します。ボリュームがこの状態になっている間、接続は許可されません。マークされたボリュームは、ターゲットの検出要求では返されません。

削除対象としてマークされたボリュームの Snapshot は影響を受けません。Snapshot は、ボリュームがシステムからパージされるまで保持されます。削除対象としてマークされたボリュームで、ボリュームの一括読み取り / 書き込み処理が実行中の場合、その処理は停止します。

削除するボリュームが別のボリュームとペアになっている場合、ペアボリューム間のレプリケーションは中断されます。削除状態の間、そのボリュームのデータは転送されません。削除されたボリュームとペアになっていたリモートボリュームは PausedMisconfigured 状態になり、削除されたボリュームとの間ではデータは送受信されません。削除されたボリュームがパージされるまでは、ボリュームをリストアしてデータ転送を再開できます。削除されたボリュームがシステムからパージされると、ペアになっていたボリュームは StoppedMisconfigured 状態になり、ボリュームペアリングのステータスが削除されます。パージされたボリュームは完全に使用できなくなります。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ボリューム ID
 a| 
削除するボリュームの ID 。
 a| 
整数
 a| 
なし
 a| 
はい。

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
ボリューム
 a| 
削除されたボリュームの情報を含むオブジェクト。
 a| 
xref:reference_element_api_volume.adoc[ボリューム]



 a| 
ボリューム ID
 a| 
削除されたボリュームの ID 。
 a| 
整数



 a| 
カーブ（ Curve ）
 a| 
curve は一連のキーと値のペアです。キーはバイト単位の I/O サイズです。値は、特定の I/O サイズで IOP を実行する際のコストを表します。curve は、 100 IOPS での 4 、 096 バイトの処理セットと比較して計算されます。
 a| 
JSON オブジェクト

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "DeleteVolume",
   "params": {
      "volumeID"  : 5
   },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "volume": {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
      },
      "blockSize": 4096,
      "createTime": "2016-03-28T16:16:13Z",
      "deleteTime": "2016-03-31T22:59:42Z",
      "enable512e": true,
      "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
      "name": "1459181777648",
      "purgeTime": "2016-04-01T06:59:42Z",
      "qos": {
        "burstIOPS": 150,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 100,
        "minIOPS": 60
      },
      "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
      "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
      "sliceCount": 1,
      "status": "deleted",
      "totalSize": 1000341504,
      "virtualVolumeID": null,
      "volumeAccessGroups": [
        1
      ],
      "volumeID": 5,
      "volumePairs": []
    }
  }
}
----


== 新規導入バージョン

9.6
