---
permalink: api/reference_element_api_modifyclusterfullthreshold.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,cluster,full,fullness,threshold,modifyclusterfullthreshold 
summary: ModifyClusterFullThreshold メソッドを使用すると、ストレージクラスタの容量が一定の利用率に近づいた場合にイベントを生成するレベルを変更できます。このしきい値設定を使用すると、警告が生成されるまでの間使用可能なブロックストレージの許容量を指定できます。 
---
= ModifyClusterFullThreshold のでした
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 modifyClusterFullThreshold 」メソッドを使用すると、ストレージクラスタの容量が一定の利用率に近づいた場合にイベントを生成するレベルを変更できます。このしきい値設定を使用すると、警告が生成されるまでの間使用可能なブロックストレージの許容量を指定できます。

たとえば、「 Error 」レベルのブロックストレージ利用率まで残り 3% でアラートを表示するには、 stage3BlockThresholdPercent パラメータに「 3 」と入力します。このレベルに達すると、クラスタ管理コンソールのイベントログにアラートが送信されます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。


NOTE: 少なくとも 1 つのパラメータを選択する必要があります。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
最大 MetadataOverProvisionFactor
 a| 
使用可能なスペースに対して、メタデータスペースをプロビジョニングできる回数。たとえば、 100TiB 分のボリュームを格納するのに十分なメタデータスペースがある場合、この数値を「 5 」に設定すると、 500TiB 分のボリュームを作成できます。
 a| 
整数
 a| 
5.
 a| 
いいえ



 a| 
stage2AwareThreshold の値
 a| 
クラスタ内で容量が残っているノードの数。この値を超えると、容量の通知がトリガーされます。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
stage3BlockThresholdPercent
 a| 
ブロックストレージ利用率が「 Error 」しきい値まであと何パーセントになった時点でクラスタの「 Warning 」アラートをトリガーするか。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
stage3MetadataThresholdPercent
 a| 
メタデータ・ストレージの使用率が ' エラー ' しきい値を下回ったため ' システムはクラスタの警告をトリガーします
 a| 
整数
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
blockFullness
 a| 
クラスタの現在のブロックフルレベル。

* stage1Happy ：アラートまたはエラー状態はありません。Web UI の「 * Healthy * 」状態に相当します。
* stage2Aware ：アラートまたはエラー状態はありません。Web UI の「 * Healthy * 」状態に相当します。
* stage3Low ： 2 つのノードで時間をおいて障害が発生した場合、冗長データ保護は提供されません。Web UI の * Warning * 状態に相当します。このレベルは Web UI で設定できます（デフォルトでは、このアラートは Error 状態の 3% 下の容量でトリガーされます）。
* stage4Critical ： 1 つのノードの障害からの冗長データ保護は提供されません。新しいボリュームやクローンを作成することはできません。Element UI の * Error * 状態に相当します。
* stage5CompletelyConsumed ：すべての容量が消費されています。クラスタは読み取り専用になり、 iSCSI 接続は維持されますが、書き込みはすべて中断されます。Element UI の * Critical * 状態に相当します。

 a| 
文字列



 a| 
使用率
 a| 
「 blockFullness 」と「 metadataFullness 」のうち、より容量が不足している方の値が反映されます。
 a| 
文字列



 a| 
最大 MetadataOverProvisionFactor
 a| 
使用可能なスペースに対して、メタデータスペースをプロビジョニングできる回数。たとえば、 100TiB 分のボリュームを格納するのに十分なメタデータスペースがある場合、この数値を「 5 」に設定すると、 500TiB 分のボリュームを作成できます。
 a| 
整数



 a| 
メタデータの容量が不足しています
 a| 
クラスタの現在のメタデータフルレベル。

* stage1Happy ：アラートまたはエラー状態はありません。Web UI の「 * Healthy * 」状態に相当します。
* stage2Aware ：アラートまたはエラー状態はありません。Web UI の「 * Healthy * 」状態に相当します。
* stage3Low ： 2 つのノードで時間をおいて障害が発生した場合、冗長データ保護は提供されません。Web UI の * Warning * 状態に相当します。このレベルは Web UI で設定できます（デフォルトでは、このアラートは Error 状態の 3% 下の容量でトリガーされます）。
* stage4Critical ： 1 つのノードの障害からの冗長データ保護は提供されません。新しいボリュームやクローンを作成することはできません。Element UI の * Error * 状態に相当します。
* stage5CompletelyConsumed ：すべての容量が消費されています。クラスタは読み取り専用になり、 iSCSI 接続は維持されますが、書き込みはすべて中断されます。Element UI の * Critical * 状態に相当します。

 a| 
文字列



 a| 
sliceReserveUsedThresholdPct を使用します
 a| 
エラー状態。予約されたスライス使用率が返された sliceReserveUsedThresholdPct の値よりも大きい場合、システムアラートがトリガーされます。
 a| 
整数



 a| 
stage2AwareThreshold の値
 a| 
認識状態。「ステージ 2 」のクラスタのしきい値レベルに設定された値。
 a| 
整数



 a| 
stage2BlockThresholdBytes
 a| 
ステージ 2 のスペース不足状態になるクラスタで使用されているバイト数。
 a| 
整数



 a| 
stage2MetadataThresholdBytes
 a| 
ステージ 2 のスペース不足が発生するクラスタで使用されているメタデータのバイト数。
 a| 



 a| 
stage3BlockThresholdBytes
 a| 
クラスタで使用されているストレージバイトのうち、「ステージ 3 のスペース不足」状態になるストレージバイトの数。
 a| 
整数



 a| 
stage3BlockThresholdPercent
 a| 
ステージ 3 に設定されたパーセント値。この割合に達すると、アラートログに警告が記録されます。
 a| 
整数



 a| 
stage3LowThreshold をクリックします
 a| 
エラー状態。クラスタの容量低下が原因でシステムアラートが作成されるしきい値。
 a| 
整数



 a| 
stage3MetadataThresholdBytes
 a| 
ステージ 3 のスペース不足状態になる、クラスタで使用されているメタデータのバイト数。
 a| 



 a| 
stage4BlockThresholdBytes
 a| 
ステージ 4 のスペース不足が発生する、クラスタで使用されているストレージのバイト数。
 a| 
整数



 a| 
stage4CriticalThreshold
 a| 
エラー状態。クラスタの容量の深刻な低下を警告するためにシステムアラートが作成されるしきい値。
 a| 
整数



 a| 
stage4MetadataThresholdBytes
 a| 
ステージ 4 のスペース不足状態になる、クラスタで使用されているメタデータのバイト数。
 a| 



 a| 
stage5BlockThresholdBytes
 a| 
ステージ 5 のスペース不足が発生する、クラスタで使用されているストレージのバイト数。
 a| 
整数



 a| 
stage5MetadataThresholdBytes
 a| 
ステージ 5 のスペース不足状態になる、クラスタで使用されているメタデータのバイト数。
 a| 



 a| 
sumTotalClusterBytes
 a| 
クラスタの物理容量（バイト単位）。
 a| 
整数



 a| 
sumTotalMetadataClusterBytes
 a| 
メタデータの格納に使用できるスペースの総容量。
 a| 
整数



 a| 
sumUsedClusterBytes の値
 a| 
クラスタで使用されているストレージのバイト数。
 a| 
整数



 a| 
sumUsedMetadataClusterBytes
 a| 
ボリュームドライブでメタデータの格納に使用されているスペースの量。
 a| 
整数

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method" : "ModifyClusterFullThreshold",
   "params" : {
              "stage3BlockThresholdPercent" : 3
              },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "blockFullness": "stage1Happy",
    "fullness": "stage3Low",
    "maxMetadataOverProvisionFactor": 5,
    "metadataFullness": "stage3Low",
    "sliceReserveUsedThresholdPct": 5,
    "stage2AwareThreshold": 3,
    "stage2BlockThresholdBytes": 2640607661261,
    "stage3BlockThresholdBytes": 8281905846682,
    "stage3BlockThresholdPercent": 3,
    "stage3LowThreshold": 2,
    "stage4BlockThresholdBytes": 8641988709581,
    "stage4CriticalThreshold": 1,
    "stage5BlockThresholdBytes": 12002762096640,
    "sumTotalClusterBytes": 12002762096640,
    "sumTotalMetadataClusterBytes": 404849531289,
    "sumUsedClusterBytes": 45553617581,
    "sumUsedMetadataClusterBytes": 31703113728
  }
}
----


== 新規導入バージョン

9.6
