---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: ModifyVirtualNetwork メソッドを使用して、既存の仮想ネットワークの属性を変更できます。 
---
= ModifyVirtualNetwork
:icons: font
:imagesdir: ../media/


[role="lead"]
「 modifyVirtualNetwork 」メソッドを使用して、既存の仮想ネットワークの属性を変更できます。

このメソッドを使用すると、アドレスブロックの追加や削除、ネットマスクの変更、仮想ネットワークの名前や概要の変更を行うことができます。また、ネームスペースの有効化と無効化、および仮想ネットワークでネームスペースが有効な場合のゲートウェイの追加と削除にも使用できます。


NOTE: このメソッドにはパラメータとして virtualNetworkID または virtualNetworkTag のいずれか一方が必要です。

注意

ネームスペースパラメータを変更して既存の仮想ネットワークのルーティング可能ストレージ VLAN 機能を有効または無効にすると、その仮想ネットワークで処理されているすべてのトラフィックが中断します。スケジュールされたメンテナンス時間中にネームスペースパラメータを変更することを推奨します。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===


| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
virtualNetworkID
 a| 
変更する仮想ネットワークの一意の識別子。これは、クラスタによって割り当てられる仮想ネットワーク ID です。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
virtualNetworkTag
 a| 
変更する仮想ネットワークを特定するネットワークタグ。
 a| 
整数
 a| 
なし
 a| 
いいえ



 a| 
アドレスブロック
 a| 
この仮想ネットワークに設定する新しいアドレスブロック。既存のオブジェクトに追加する新しいアドレスブロックを指定したり、削除が必要な未使用のアドレスブロックを除いたブロックを指定したりできます。また、既存のアドレスブロックのサイズを拡張または縮小することもできます。仮想ネットワークオブジェクトの開始アドレスブロックのサイズは増やすことはできますが、減らすことはできません。このオブジェクトの必須のメンバーは次のとおりです。

* start ： IP アドレス範囲の開始アドレス文字列
* size ：ブロックに含める IP アドレスの数整数

 a| 
JSON オブジェクト
 a| 
なし
 a| 
いいえ



 a| 
ゲートウェイ
 a| 
仮想ネットワークのゲートウェイの IP アドレスです。このパラメータは、 namespace パラメータを true に設定した場合のみ有効です。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
属性（ Attributes ）
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSON オブジェクト
 a| 
なし
 a| 
いいえ



 a| 
名前
 a| 
仮想ネットワークの新しい名前。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
ネームスペース
 a| 
true に設定すると、仮想ネットワークが再作成されてその仮想ネットワークを含むネームスペースが設定されることで、ルーティング可能ストレージ VLAN 機能が有効になります。false に設定すると、仮想ネットワークの VRF 機能が無効になります。この値を変更すると、この仮想ネットワークを通過するトラフィックが中断されます。
 a| 
ブール値
 a| 
なし
 a| 
いいえ



 a| 
ネットマスク
 a| 
この仮想ネットワークの新しいネットワークマスク。
 a| 
文字列
 a| 
なし
 a| 
いいえ



 a| 
svip
 a| 
この仮想ネットワークのストレージ仮想 IP アドレス。仮想ネットワークの SVIP は変更できません。別の SVIP アドレスを使用するには、新しい仮想ネットワークを作成する必要があります。
 a| 
文字列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには戻り値はありません。



== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== 新規導入バージョン

9.6
