---
permalink: api/reference_element_api_purgedeletedvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,purge,purging,multiple,deleted,purgedeletedvolumes 
summary: PurgeDeletedVolumes メソッドを使用すると、削除されたボリュームをただちに完全にパージできます。このメソッドを使用すると、一度に最大 500 個のボリュームをパージできます。 
---
= PurgeDeletedVolumes の場合
:icons: font
:imagesdir: ../media/


[role="lead"]
PurgeDeletedVolumes メソッドを使用すると、削除されたボリュームをただちに完全にパージできます。このメソッドを使用すると、一度に最大 500 個のボリュームをパージできます。

パージする前に '`eleeteVolumes] を使用してボリュームを削除する必要がありますボリュームは一定期間の経過後に自動的にパージされるため、通常はこのメソッドを使用する必要はありません。


NOTE: 一度に大量のボリュームをパージする場合や、各ボリュームをパージする際に多数の Snapshot が関連付けられている場合は、メソッドが失敗してエラー「 xDBConnectionLoss 」が返されることがあります。この場合は、ボリューム数を減らしてもう一度メソッド呼び出しを実行してください。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


| ボリューム ID | システムからパージするボリュームの ID のリスト。 | 整数の配列 | いいえ | いいえ 


| アカウント ID | アカウント ID のリスト。指定したすべてのアカウントのすべてのボリュームがシステムからパージされます。 | 整数の配列 | いいえ | いいえ 


| ボリュームアクセスグループ ID | ボリュームアクセスグループ ID のリスト。指定したすべてのボリュームアクセスグループのすべてのボリュームがシステムからパージされます。 | 整数の配列 | いいえ | いいえ 
|===
* 注： * メソッド呼び出しごとに、上記のパラメータのうち 1 つだけを指定できます。複数のパラメータを指定した場合やパラメータを指定しなかった場合は、エラーが発生します。



== 戻り値

このメソッドには戻り値はありません。



== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "PurgeDeletedVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id" : 1,
  "result": {}
}
----


== 新規導入バージョン

9.6



== 詳細については、こちらをご覧ください

xref:reference_element_api_deletevolumes.adoc[DeleteVolumes]
