---
permalink: api/reference_element_api_authsessioninfo.html 
sidebar: sidebar 
keywords: objects,object,authSessionInfo 
summary: authSessionInfo オブジェクトには、認証セッションに関する情報が含まれています。 
---
= authSessionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
authSessionInfo オブジェクトには、認証セッションに関する情報が含まれています。



== オブジェクトメンバー

このオブジェクトのメンバーは次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
AccessGroupList ( アクセスグループリスト )
 a| 
ユーザのアクセスグループのリスト。
 a| 
文字列の配列



 a| 
使用します
 a| 
クラスタ管理者ユーザが使用する認証のタイプ。有効な値は次のとおり

* LDAP - LDAP で認証されています。
* クラスタ - クラスタデータベースに保存されているユーザ名とパスワードを使用して認証されます。
* IdP - サードパーティのアイデンティティプロバイダを使用して認証されています。

 a| 
文字列



 a| 
クラスタ管理者 ID
 a| 
このセッションに関連付けられているクラスタ管理者 ID のリスト。LDAP またはサードパーティのアイデンティティプロバイダ（ IdP ）に関連するセッションの場合、このセッションに関連付けられている一致するクラスタ管理者 ID のアグリゲートリストが表示されます。
 a| 
整数の配列



 a| 
finalTimeout
 a| 
セッションが無効になる時刻。セッションが作成されたときに設定され、変更できません。
 a| 
文字列



 a| 
idpConfigVersion
 a| 
セッション作成時の IDP 設定バージョン。
 a| 
整数



 a| 
lastAccessTimeout の値
 a| 
非アクティブのためにセッションが無効になった時間。セッションが使用できるようにアクセスされたときの新しい値に設定されます。これは、 finalTimeout に達したためにセッションが無効になった時間までです。
 a| 
文字列



 a| 
sessionCreationTime に追加します
 a| 
セッションが作成された時刻。
 a| 
文字列



 a| 
SessionID
 a| 
このセッションの UUID 。
 a| 
UUID



 a| 
ユーザ名
 a| 
このセッションに関連付けられているユーザ名。LDAP に関連するセッションの場合は、ユーザの LDAP DN になります。サードパーティ IdP に関連するセッションの場合、セッション内の処理の監査に使用する任意の名前と値のペアを指定します。クラスタ管理者名と同じである必要はありません。たとえば、 SAML Subject NameID は、 IdP の設定と SAML アサーションの結果コンテンツによって決まります。
 a| 
文字列

|===