---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: ListEvents メソッドを使用すると、クラスタで検出されたイベントを古いイベントから新しいイベントの順にリストできます。 
---
= ListEvents の場合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 ListEvents 」メソッドを使用すると、クラスタで検出されたイベントを古いイベントから新しいイベントの順にリストできます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
driveID
 a| 
このドライブ ID を含むイベントのみが返されます。
 a| 
整数
 a| 
0
 a| 
いいえ



 a| 
endEventID のこと
 a| 
返されるイベント ID 範囲の終了値を指定します。
 a| 
整数
 a| 
無制限
 a| 
いいえ



 a| 
endPublishTime
 a| 
この時点より前に発行されたイベントのみが返されます。
 a| 
文字列
 a| 
0
 a| 
いいえ



 a| 
endReportTime
 a| 
この時点より前に報告されたイベントのみが返されます。
 a| 
文字列
 a| 
0
 a| 
いいえ



 a| 
EventType ( イベントタイプ
 a| 
返されるイベントのタイプを指定します。を参照してください xref:reference_element_api_event.adoc[イベント] を参照してください。
 a| 
文字列
 a| 
0
 a| 
いいえ



 a| 
最大イベント数
 a| 
返されるイベントの最大数を指定します。
 a| 
整数
 a| 
無制限
 a| 
いいえ



 a| 
ノード ID
 a| 
このノード ID を含むイベントのみが返されます。
 a| 
整数
 a| 
 a| 



 a| 
サービス ID
 a| 
このサービス ID を含むイベントのみが返されます。
 a| 
 a| 
 a| 



 a| 
startEventID のあとに
 a| 
返されるイベント範囲の開始位置を指定します。
 a| 
整数
 a| 
0
 a| 
いいえ



 a| 
startPublishTime を参照してください
 a| 
この時点よりあとに発行されたイベントのみが返されます。
 a| 
文字列
 a| 
0
 a| 
いいえ



 a| 
startReportTime です
 a| 
この時点よりあとに報告されたイベントのみが返されます。
 a| 
文字列
 a| 
0
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| 名前 | 説明 | を入力します 


 a| 
イベント
 a| 
イベントのリスト。
 a| 
xref:reference_element_api_event.adoc[イベント] 配列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== 新規導入バージョン

9.6
