---
permalink: api/reference_element_api_removeinitiatorsfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: initiators,initiator,volume,access,group,remove,removing,removeinitiatorsfromvolumeaccessgroup 
summary: RemoveInitiatorsFromVolumeAccessGroup メソッドを使用すると、指定したボリュームアクセスグループからイニシエータを削除できます。 
---
= RemoveInitiatorsFromVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RemoveInitiatorsFromVolumeAccessGroup メソッドを使用すると、指定したボリュームアクセスグループからイニシエータを削除できます。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 説明 | を入力します | デフォルト値 | 必須 


 a| 
ボリュームアクセスグループ ID
 a| 
イニシエータを削除するボリュームアクセスグループの ID 。
 a| 
整数
 a| 
なし
 a| 
はい。



 a| 
イニシエータ
 a| 
ボリュームアクセスグループに含めるイニシエータの ID または名前（ IQN および WWPN ）のリスト。イニシエータ名のリストを渡した場合、存在しないイニシエータは作成されます。イニシエータ ID のリストを渡した場合、存在しないイニシエータにはエラーが返されます。イニシエータ名を渡すことは推奨されていません。可能な場合はイニシエータ ID を使用し
 a| 
整数の配列（推奨）または文字列の配列（非推奨）
 a| 
なし
 a| 
いいえ



 a| 
deleteOrphanInitiators
 a| 
ボリュームアクセスグループから削除したあとにイニシエータオブジェクトを削除するかどうかを指定します。有効な値は次のとおり

* true ：ボリュームアクセスグループから削除したあとにイニシエータオブジェクトを削除します。
* false ：ボリュームアクセスグループから削除したあとにイニシエータオブジェクトを削除しません。これがデフォルトです。

 a| 
ブール値
 a| 
いいえ
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 説明 | を入力します 


 a| 
volumeAccessGroup の場合
 a| 
新たに変更されたボリュームアクセスグループの情報を含むオブジェクト。
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup の場合]

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
  "id": 13171,
  "method": "RemoveInitiatorsFromVolumeAccessGroup",
  "params": {
    "initiators": [114,115],
    "volumeAccessGroupID": 96
  }
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 13171,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [],
      "initiators": [],
      "name": "test",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== 新規導入バージョン

9.6
